### ISSUE TITLE
Use keras.layers.convolutional.UpSampling2D replace upSamleLike

### ISSUE THREAD

**Issue by taqikoma** [fizyr/keras-retinanet#1023]
Firstly, thanks for your great work!
Today, I want to use "tensorflow/model_optimazition" to compress the model. But it recommand to use Keras or Tensorflow to build model only.
So I use keras.layers.convolutional.UpSampling2D to replace upSamleLike, the following error occured:
Input 1 has shape [2 17 31 512] and doesn't match input 0 with shape [2 16 30 256].

Then I use:
    target_shape = keras.backend.shape(C4)
    P5_upsampled = tensorflow.image.resize_images(P5_upsampled, (target_shape[1], target_shape[2]), method='nearest')
to make the two tensor have same shape.

But another error occured:
Traceback (most recent call last):
  File "keras_retinanet/bin/train.py", line 515, in <module>
    main()
  File "keras_retinanet/bin/train.py", line 470, in main
    config=args.config
  File "keras_retinanet/bin/train.py", line 120, in create_models
    model          = model_with_weights(backbone_retinanet(num_classes, num_anchors=num_anchors, modifier=modifier), weights=weights, skip_mismatch=True)
  File "keras_retinanet/bin/../../keras_retinanet/models/vgg.py", line 33, in retinanet
    return vgg_retinanet(*args, backbone=self.backbone, **kwargs)
  File "keras_retinanet/bin/../../keras_retinanet/models/vgg.py", line 99, in vgg_retinanet
    return retinanet.retinanet(inputs=inputs, num_classes=num_classes, backbone_layers=layer_outputs, **kwargs)
  File "keras_retinanet/bin/../../keras_retinanet/models/retinanet.py", line 339, in retinanet
    return keras.models.Model(inputs=inputs, outputs=pyramids, name=name)
  File "/home/ibd/anaconda3/envs/pruning/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/ibd/anaconda3/envs/pruning/lib/python3.6/site-packages/keras/engine/network.py", line 93, in __init__
    self._init_graph_network(*args, **kwargs)
  File "/home/ibd/anaconda3/envs/pruning/lib/python3.6/site-packages/keras/engine/network.py", line 231, in _init_graph_network
    self.inputs, self.outputs)
  File "/home/ibd/anaconda3/envs/pruning/lib/python3.6/site-packages/keras/engine/network.py", line 1366, in _map_graph_network
    tensor_index=tensor_index)
  File "/home/ibd/anaconda3/envs/pruning/lib/python3.6/site-packages/keras/engine/network.py", line 1353, in build_map
    node_index, tensor_index)
  File "/home/ibd/anaconda3/envs/pruning/lib/python3.6/site-packages/keras/engine/network.py", line 1353, in build_map
    node_index, tensor_index)
  File "/home/ibd/anaconda3/envs/pruning/lib/python3.6/site-packages/keras/engine/network.py", line 1353, in build_map
    node_index, tensor_index)
  [Previous line repeated 1 more time]
  File "/home/ibd/anaconda3/envs/pruning/lib/python3.6/site-packages/keras/engine/network.py", line 1325, in build_map
    node = layer._inbound_nodes[node_index]
AttributeError: 'NoneType' object has no attribute '_inbound_nodes'

**Comment by hgaiser** [comment]
Yeah, `UpsampleLike` was made for the reason that Upsample2D doesn't always produce the output we want, hence your mismatching shapes. Using resize_images might work, but you can't call tensorflow ops directly in Keras. They have to be wrapped in a `keras.Layer`, which is basically what `UpsampleLike` does if you look at the implementation.

Anyway, since this is not an issue with our code, I will close this.
