### ISSUE TITLE
multiprocessing: getting MemoryError(full RAM usage) when workers >= 1

### ISSUE THREAD

**Issue by mailcorahul** [fizyr/keras-retinanet#1081]
Whenever I train keras-retinanet with workers >= 1, my RAM usage increases gradually during an epoch and eventually the training gets killed when RAM gets completely used up. 

Below is the traceback:

Epoch 1/50
 1157/16173 [=>............................] - ETA: 6:09:58 - loss: 3.0908 - regression_loss: 2.4085 - classification_loss: 0.6823multiprocessing.pool.RemoteTraceback:

"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/opt/infilect/dev/envs/object_detection_framework/retina_net/lib/python3.5/site-packages/keras/utils/data_utils.py", line 401, in get_index
    return _SHARED_SEQUENCES[uid][i]
  File "keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py", line 337, in __getitem__
    inputs, targets = self.compute_input_output(group)
  File "keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py", line 321, in compute_input_output
    targets = self.compute_targets(image_group, annotations_group)
  File "keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py", line 296, in compute_targets
    self.num_classes()
  File "keras_retinanet/bin/../../keras_retinanet/utils/anchors.py", line 97, in anchor_targets_bbox
    positive_indices, ignore_indices, argmax_overlaps_inds = compute_gt_annotations(anchors, annotations['bboxes'], negative_overlap, positive_overlap)
  File "keras_retinanet/bin/../../keras_retinanet/utils/anchors.py", line 143, in compute_gt_annotations
    overlaps = compute_overlap(anchors.astype(np.float64), annotations.astype(np.float64))
  File "keras_retinanet/utils/compute_overlap.pyx", line 27, in keras_retinanet.utils.compute_overlap.compute_overlap
    cdef np.ndarray[double, ndim=2] overlaps = np.zeros((N, K), dtype=np.float64)
MemoryError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "keras_retinanet/bin/train.py", line 566, in <module>
    main()
  File "keras_retinanet/bin/train.py", line 561, in main
    initial_epoch=initial_epoch
  File "/opt/infilect/dev/envs/object_detection_framework/retina_net/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/opt/infilect/dev/envs/object_detection_framework/retina_net/lib/python3.5/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/opt/infilect/dev/envs/object_detection_framework/retina_net/lib/python3.5/site-packages/keras/engine/training_generator.py", line 181, in fit_generator
    generator_output = next(output_generator)
  File "/opt/infilect/dev/envs/object_detection_framework/retina_net/lib/python3.5/site-packages/keras/utils/data_utils.py", line 601, in get
    six.reraise(*sys.exc_info())
  File "/opt/infilect/dev/envs/object_detection_framework/retina_net/lib/python3.5/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/infilect/dev/envs/object_detection_framework/retina_net/lib/python3.5/site-packages/keras/utils/data_utils.py", line 595, in get
    inputs = self.queue.get(block=True).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
MemoryError
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7f89d66f5320>>
Traceback (most recent call last):
  File "/opt/infilect/dev/envs/object_detection_framework/retina_net/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 738, in __del__
TypeError: 'NoneType' object is not callable

@hgaiser any idea why this is happening? this forces me to set workers=0 for all of my training runs.

**Comment by mak4alex** [comment]
provide hardware configuration, training options and image size

**Comment by mailcorahul** [comment]
output of lshw -short:

H/W path    Device  Class      Description
                    system     Computer
/0                  bus        Motherboard
/0/0                memory     29GiB System memory
/0/1                processor  Intel(R) Xeon(R) CPU @ 2.20GHz
/0/100              bridge     440FX - 82441FX PMC [Natoma]
/0/100/1            bridge     82371AB/EB/MB PIIX4 ISA
/0/100/1.3          bridge     82371AB/EB/MB PIIX4 ACPI
/0/100/3            generic    Virtio SCSI
/0/100/4            display    GK210GL [Tesla K80]
/0/100/5            display    GK210GL [Tesla K80]
/0/100/6    ens6    network    Virtio network device

machine has two 12GB Tesla K80 GPUs. Note the training run uses only one GPU.

output of lscpu:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    2
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU @ 2.20GHz
Stepping:              0
CPU MHz:               2200.000
BogoMIPS:              4400.00
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              56320K
NUMA node0 CPU(s):     0-7
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities


training command used:

keras_retinanet/bin/train.py --image-min-side 1500 --image-max-side 2200 csv /opt/infilect/dev/datasets/object_detection/sku_110k_corrected/records/retina_net/train.csv /opt/infilect/dev/datasets/object_detection/sku_110k_corrected/records/retina_net/cls_to_id.csv --val-annotations /opt/infilect/dev/datasets/object_detection/sku_110k_corrected/records/retina_net/val.csv --test-annotations /opt/infilect/dev/datasets/object_detection/sku_110k_corrected/records/retina_net/test.csv

image size: 2200x1500 (max-side X min-side)

@mak4alex

**Comment by hgaiser** [comment]
Could you provide a reproducible setting so that I can test this? Ideally you can provide a container (Docker?) that sets everything up and runs a training process.

**Comment by hgaiser** [comment]
Any update on this ?

**Comment by mailcorahul** [comment]
@hgaiser will get back to you by the end of this week. sorry for the delay.

**Comment by hgaiser** [comment]
Any update on this? Is this still a problem?

**Comment by wendaomu** [comment]
I meet the same problems, when using multi-processing

**Comment by AutumnZ-94** [comment]
For me the problems is stuck at the epoch init and not starting the training, without error raised.
