### ISSUE TITLE
IndexError: index 8589940219 is out of bounds for axis 0 with size 188748

### ISSUE THREAD

**Issue by CanshangD** [fizyr/keras-retinanet#1084]
### I train the model with my own dataset,the code stop trainning in the epoch 4 with the IndexError . The dataset should be okay. I don't know what went wrong.

**Log：**

Epoch 00003: saving model to ./snapshots/resnet101_pascal_03.h5
Epoch 4/20
2344/5084 [============>.................] - ETA: 21:35 - loss: 0.5476 - regression_loss: 0.4314 - classification_loss: 0.1163Traceback (most recent call last):
  File "train.py", line 514, in <module>
    main()
  File "train.py", line 509, in main
    validation_data=validation_generator
  File "/home/jijia/anaconda3/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/jijia/anaconda3/lib/python3.5/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/jijia/anaconda3/lib/python3.5/site-packages/keras/engine/training_generator.py", line 181, in fit_generator
    generator_output = next(output_generator)
  File "/home/jijia/anaconda3/lib/python3.5/site-packages/keras/utils/data_utils.py", line 601, in get
    six.reraise(*sys.exc_info())
  File "/home/jijia/anaconda3/lib/python3.5/site-packages/six.py", line 686, in reraise
    raise value
  File "/home/jijia/anaconda3/lib/python3.5/site-packages/keras/utils/data_utils.py", line 595, in get
    inputs = self.queue.get(block=True).get()
  File "/home/jijia/anaconda3/lib/python3.5/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/home/jijia/anaconda3/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/jijia/anaconda3/lib/python3.5/site-packages/keras/utils/data_utils.py", line 401, in get_index
    return _SHARED_SEQUENCES[uid][i]
  File "../../keras_retinanet/preprocessing/generator.py", line 334, in __getitem__
    inputs, targets = self.compute_input_output(group)
  File "../../keras_retinanet/preprocessing/generator.py", line 318, in compute_input_output
    targets = self.compute_targets(image_group, annotations_group)
  File "../../keras_retinanet/preprocessing/generator.py", line 293, in compute_targets
    self.num_classes()
  File "../../keras_retinanet/utils/anchors.py", line 95, in anchor_targets_bbox
    positive_indices, ignore_indices, argmax_overlaps_inds = compute_gt_annotations(anchors, annotations['bboxes'], negative_overlap, positive_overlap)
  File "../../keras_retinanet/utils/anchors.py", line 141, in compute_gt_annotations
    max_overlaps = overlaps[np.arange(overlaps.shape[0]), argmax_overlaps_inds]
IndexError: index 8589940219 is out of bounds for axis 0 with size 188748

**Comment by hgaiser** [comment]
That seems like a strange error to me. Can you make a minimum example dataset where this error occurs, so that I can replicate it?

**Comment by CanshangD** [comment]
@hgaiser I retrained the model and the error disappeared. It was a strange problem. :)

**Comment by hgaiser** [comment]
Alright, then I'll close this.
