### ISSUE TITLE
TypeError: data type not understood

### ISSUE THREAD

**Issue by icoicqico** [fizyr/keras-retinanet#1114]
C:\Untitled Folder\kk\keras_retinanet\initializers.py in __call__(self, shape, dtype)
     35     def __call__(self, shape, dtype=None):
     36         # set bias to -log((1 - p)/p) for foreground
---> 37         result = np.ones(shape, dtype=dtype) * -math.log((1 - self.probability) / self.probability)
     38 
     39         return result

c:\users\captain\appdata\local\programs\python\python36\lib\site-packages\numpy\core\numeric.py in ones(shape, dtype, order)
    212 
    213     """
--> 214     a = empty(shape, dtype, order)
    215     multiarray.copyto(a, 1, casting='unsafe')
    216     return a

TypeError: data type not understood

**Comment by SourceCodeCat** [comment]
well if it is failing at  this point :  'empty(shape, dtype, order)'  take a look to your dataset and make sure it is no sparse (probably there is one or several rows with empty values), also try to stick to the annotation format for the dataset  here is a small piece of my dataset

> train/329f6972a0418e19.jpg,617,313,727,455,Glove
> train/30246299fe555676.jpg,342,609,772,856,Skirt
> train/30246299fe555676.jpg,235,9,932,789,Jacket
> train/30246299fe555676.jpg,235,16,912,837,Jeans

each comma separated column stands for:

> path/to/image.jpg, x1, y1, x2, y2, class_name

hope this helps.

**Comment by icoicqico** [comment]
> well if it is failing at this point : 'empty(shape, dtype, order)' take a look to your dataset and make sure it is no sparse (probably there is one or several rows with empty values), also try to stick to the annotation format for the dataset here is a small piece of my dataset
> 
> > train/329f6972a0418e19.jpg,617,313,727,455,Glove
> > train/30246299fe555676.jpg,342,609,772,856,Skirt
> > train/30246299fe555676.jpg,235,9,932,789,Jacket
> > train/30246299fe555676.jpg,235,16,912,837,Jeans
> 
> each comma separated column stands for:
> 
> > path/to/image.jpg, x1, y1, x2, y2, class_name
> 
> hope this helps.

Thanks for reply, but I already trained my model and it works very well, I just want to convert it to tensorflow lite version, and I import the load model and all required packages from retinanet.

**Comment by hgaiser** [comment]
I'm not sure what it takes to convert to TF lite, it might not work out of the box. I'll leave this open for a while in case someone wants to reply.

**Comment by LaurensHagendoorn** [comment]
I don't know about that last error, but the first one I also got on converting the repo to tf2, I'm guessing that when you use tf.keras, it passes a default of tf.float32 as dtype, instead of just float32, tf.float32 is unknown to numpy. You can change the initialiser to use tf.ones rather than np.ones

**Comment by icoicqico** [comment]
I have changed np.ones to tf.ones, and got another error.
     24 
     25 converter=tf.lite.TFLiteConverter.from_keras_model_file('resnet50_csv_08.h5',custom_objects
---> 26                                                         =backbone('resnet50').custom_objects)
     27 tflite_model = converter.convert()
     28 open("converted_model.tflite", "wb").write(tflite_model)

c:\users\captain\appdata\local\programs\python\python36\lib\site-packages\tensorflow\lite\python\lite.py in from_keras_model_file(cls, model_file, input_arrays, input_shapes, output_arrays, custom_objects)
    745     _keras.backend.clear_session()
    746     _keras.backend.set_learning_phase(False)
--> 747     keras_model = _keras.models.load_model(model_file, custom_objects)
    748     sess = _keras.backend.get_session()
    749 

c:\users\captain\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\keras\saving\save.py in load_model(filepath, custom_objects, compile)
    144       h5py is not None and (
    145           isinstance(filepath, h5py.File) or h5py.is_hdf5(filepath))):
--> 146     return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
    147 
    148   if isinstance(filepath, six.string_types):

c:\users\captain\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py in load_model_from_hdf5(filepath, custom_objects, compile)
    210     model_config = json.loads(model_config.decode('utf-8'))
    211     model = model_config_lib.model_from_config(model_config,
--> 212                                                custom_objects=custom_objects)
    213 
    214     # set weights

c:\users\captain\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\keras\saving\model_config.py in model_from_config(config, custom_objects)
     53                     '`Sequential.from_config(config)`?')
     54   from tensorflow.python.keras.layers import deserialize  # pylint: disable=g-import-not-at-top
---> 55   return deserialize(config, custom_objects=custom_objects)
     56 
     57 

c:\users\captain\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\keras\layers\serialization.py in deserialize(config, custom_objects)
     87       module_objects=globs,
     88       custom_objects=custom_objects,
---> 89       printable_module_name='layer')

c:\users\captain\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    190             custom_objects=dict(
    191                 list(_GLOBAL_CUSTOM_OBJECTS.items()) +
--> 192                 list(custom_objects.items())))
    193       with CustomObjectScope(custom_objects):
    194         return cls.from_config(cls_config)

c:\users\captain\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\keras\engine\network.py in from_config(cls, config, custom_objects)
   1129         if layer in unprocessed_nodes:
   1130           for node_data in unprocessed_nodes.pop(layer):
-> 1131             process_node(layer, node_data)
   1132 
   1133     name = config.get('name')

c:\users\captain\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\keras\engine\network.py in process_node(layer, node_data)
   1085         flat_input_tensors = nest.flatten(input_tensors)
   1086         if len(flat_input_tensors) == 1:
-> 1087           layer(flat_input_tensors[0], **kwargs)
   1088         else:
   1089           layer(input_tensors, **kwargs)

c:\users\captain\appdata\local\programs\python\python36\lib\site-packages\keras\engine\base_layer.py in __call__(self, inputs, **kwargs)
    441 
    442             # Handle mask propagation.
--> 443             previous_mask = _collect_previous_mask(inputs)
    444             user_kwargs = copy.copy(kwargs)
    445             if not is_all_none(previous_mask):

c:\users\captain\appdata\local\programs\python\python36\lib\site-packages\keras\engine\base_layer.py in _collect_previous_mask(input_tensors)
   1309             inbound_layer, node_index, tensor_index = x._keras_history
   1310             node = inbound_layer._inbound_nodes[node_index]
-> 1311             mask = node.output_masks[tensor_index]
   1312             masks.append(mask)
   1313         else:

AttributeError: 'Node' object has no attribute 'output_masks'

**Comment by LaurensHagendoorn** [comment]
Well, it looks like you got further along, this is probably some tf-lite stuff, I can't really help you with that, I'm guessing a lot of layers in keras-retinanet are not supported

**Comment by ghunkins** [comment]
I'm having this issue as well. Would be great for a tutorial on how to convert to `TensorflowLite` (if it's supported @ this time.

**Comment by hgaiser** [comment]
I've never worked it it, it's not officially supported from our side.

**Comment by 2696120622** [comment]
> I don't know about that last error, but the first one I also got on converting the repo to tf2, I'm guessing that when you use tf.keras, it passes a default of tf.float32 as dtype, instead of just float32, tf.float32 is unknown to numpy. You can change the initialiser to use tf.ones rather than np.ones

Thanks a lot.

**Comment by Phisches** [comment]
> Well, it looks like you got further along, this is probably some tf-lite stuff, I can't really help you with that, I'm guessing a lot of layers in keras-retinanet are not supported

Hi, 
I have also encountered the error that icoicqico  is seeing.
However, I see it unrelated to tf-lite but when loading the Retina Net model with tf.keras.
I would expect that to work in principle, since Retinanet and TF2.Keras both implement the Keras API?

The relevant code should be:

[from tensorflow import keras
myCustomObjects = backbone('resnet50').custom_objects
model = keras.models.load_model("/tmp/model_conv.h5", myCustomObjects) ](url)

with this stack trace

```
Traceback (most recent call last):
  File "loadKeras.py", line 42, in <module>
    model = keras.models.load_model("/tmp/model_conv.h5", myCustomObjects) 
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/saving/save.py", line 146, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 168, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/saving/model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/layers/serialization.py", line 102, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 191, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/engine/network.py", line 906, in from_config
    config, custom_objects)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/engine/network.py", line 1852, in reconstruct_from_config
    process_node(layer, node_data)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/engine/network.py", line 1799, in process_node
    output_tensors = layer(input_tensors, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 75, in symbolic_fn_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/base_layer.py", line 475, in __call__
    previous_mask = _collect_previous_mask(inputs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/base_layer.py", line 1441, in _collect_previous_mask
    mask = node.output_masks[tensor_index]
AttributeError: 'Node' object has no attribute 'output_masks'
```

**Seems to me like a problem with TF2**, but I am really just starting with tensor flow.
What do you think?
Any ideas how to fix that?

Thanks.
