### ISSUE TITLE
AssertionError: Input is not a training model (no 'regression' and 'classification' outputs were found, outputs are: ['filtered_detections', 'filtered_detections', 'filtered_detections'])

### ISSUE THREAD

**Issue by AndreaPi** [fizyr/keras-retinanet#1196]
I'm running the (nearly) latest version of master, forked this morning. I run it in a Docker container built with the following `Dockerfile`:

```
FROM tensorflow/tensorflow:1.15.0-py3

# set proxy
ENV http_proxy=...
ENV https_proxy=...
ENV no_proxy=...

# install required Ubuntu packages
RUN apt-get -y update && apt-get -y install \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    git

# copy files to install keras-retinanet
COPY keras_retinanet /keras-retinanet/keras_retinanet
COPY setup.* /keras-retinanet/
COPY requirements.txt /keras-retinanet/requirements.txt


# install requirements
RUN pip3 install -r /keras-retinanet/requirements.txt

# finally, install keras-retinanet
RUN cd /keras-retinanet && pip3 install . 

CMD /bin/bash
```

I run the command

```
retinanet-train --no-resize --batch-size=1 --steps=50 --epochs=10 --snapshot /ws/snapshots/resnet50_coco_best_v2.1.0.h5 --tensorboard-dir /ws/snapshots/logs/$(date +%m-%d-%H%M) --snapshot-path /ws/snapshots csv /data/train_annotations.csv /data/classes.csv
```

which results in error

```
/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py:341: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
Traceback (most recent call last):
  File "/usr/local/bin/retinanet-train", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/keras_retinanet/bin/train.py", line 472, in main
    prediction_model = retinanet_bbox(model=model, anchor_params=anchor_params)
  File "/usr/local/lib/python3.6/dist-packages/keras_retinanet/models/retinanet.py", line 327, in retinanet_bbox
    assert_training_model(model)
  File "/usr/local/lib/python3.6/dist-packages/keras_retinanet/models/__init__.py", line 114, in assert_training_model
    "Input is not a training model (no 'regression' and 'classification' outputs were found, outputs are: {}).".format(model.output_names)
AssertionError: Input is not a training model (no 'regression' and 'classification' outputs were found, outputs are: ['filtered_detections', 'filtered_detections', 'filtered_detections']).
```

What's happening? 
Ubuntu version:
```
Ubuntu 18.04.3 LTS \n \l
```
Python:
```
Python 3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0] on linux
```
Keras:
```
'2.3.1'
```
Tensorflow:
```
'1.15.0'
```

**Comment by AndreaPi** [comment]
PS file `resnet50_coco_best_v2.1.0.h5` was downloaded (as always) from [here](https://github.com/fizyr/keras-retinanet/releases/download/0.5.1/resnet50_coco_best_v2.1.0.h5)

**Comment by hgaiser** [comment]
You can't resume from a converted weights file, you have to use `--weights` instead of `--snapshot`. The difference being that `--snapshot` resumes training from where you left off, so it requires a non-converted model.

**Comment by AndreaPi** [comment]
You're right, my mistake. I was fooled by this warning

```
/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py:341: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
```

which I thought meant that the model was not converted, instead it says *not compiled*, which is different. Thanks!
