### ISSUE TITLE
ResNet50RetinaNet

### ISSUE THREAD

**Issue by PEE8** [fizyr/keras-retinanet#1205]
It gives as follows Reloaded modules: anchors
tracking <tf.Variable 'Variable:0' shape=(9, 4) dtype=float32, numpy=
array([[-22.627417, -11.313708,  22.627417,  11.313708],
       [-28.50876 , -14.25438 ,  28.50876 ,  14.25438 ],
       [-35.918785, -17.959393,  35.918785,  17.959393],
       [-16.      , -16.      ,  16.      ,  16.      ],
       [-20.158737, -20.158737,  20.158737,  20.158737],
       [-25.398417, -25.398417,  25.398417,  25.398417],
       [-11.313708, -22.627417,  11.313708,  22.627417],
       [-14.25438 , -28.50876 ,  14.25438 ,  28.50876 ],
       [-17.959393, -35.918785,  17.959393,  35.918785]], dtype=float32)> anchors
tracking <tf.Variable 'Variable:0' shape=(9, 4) dtype=float32, numpy=
array([[-45.254833, -22.627417,  45.254833,  22.627417],
       [-57.01752 , -28.50876 ,  57.01752 ,  28.50876 ],
       [-71.83757 , -35.918785,  71.83757 ,  35.918785],
       [-32.      , -32.      ,  32.      ,  32.      ],
       [-40.317474, -40.317474,  40.317474,  40.317474],
       [-50.796833, -50.796833,  50.796833,  50.796833],
       [-22.627417, -45.254833,  22.627417,  45.254833],
       [-28.50876 , -57.01752 ,  28.50876 ,  57.01752 ],
       [-35.918785, -71.83757 ,  35.918785,  71.83757 ]], dtype=float32)> anchors
tracking <tf.Variable 'Variable:0' shape=(9, 4) dtype=float32, numpy=
array([[ -90.50967 ,  -45.254833,   90.50967 ,   45.254833],
       [-114.03504 ,  -57.01752 ,  114.03504 ,   57.01752 ],
       [-143.67514 ,  -71.83757 ,  143.67514 ,   71.83757 ],
       [ -64.      ,  -64.      ,   64.      ,   64.      ],
       [ -80.63495 ,  -80.63495 ,   80.63495 ,   80.63495 ],
       [-101.593666, -101.593666,  101.593666,  101.593666],
       [ -45.254833,  -90.50967 ,   45.254833,   90.50967 ],
       [ -57.01752 , -114.03504 ,   57.01752 ,  114.03504 ],
       [ -71.83757 , -143.67514 ,   71.83757 ,  143.67514 ]],
      dtype=float32)> anchors
tracking <tf.Variable 'Variable:0' shape=(9, 4) dtype=float32, numpy=
array([[-181.01933,  -90.50967,  181.01933,   90.50967],
       [-228.07008, -114.03504,  228.07008,  114.03504],
       [-287.35028, -143.67514,  287.35028,  143.67514],
       [-128.     , -128.     ,  128.     ,  128.     ],
       [-161.2699 , -161.2699 ,  161.2699 ,  161.2699 ],
       [-203.18733, -203.18733,  203.18733,  203.18733],
       [ -90.50967, -181.01933,   90.50967,  181.01933],
       [-114.03504, -228.07008,  114.03504,  228.07008],
       [-143.67514, -287.35028,  143.67514,  287.35028]], dtype=float32)> anchors
tracking <tf.Variable 'Variable:0' shape=(9, 4) dtype=float32, numpy=
array([[-362.03867, -181.01933,  362.03867,  181.01933],
       [-456.14017, -228.07008,  456.14017,  228.07008],
       [-574.70056, -287.35028,  574.70056,  287.35028],
       [-256.     , -256.     ,  256.     ,  256.     ],
       [-322.5398 , -322.5398 ,  322.5398 ,  322.5398 ],
       [-406.37466, -406.37466,  406.37466,  406.37466],
       [-181.01933, -362.03867,  181.01933,  362.03867],
       [-228.07008, -456.14017,  228.07008,  456.14017],
       [-287.35028, -574.70056,  287.35028,  574.70056]], dtype=float32)> anchors
Traceback (most recent call last):

  File "<ipython-input-3-1f92bb8456a1>", line 1, in <module>
    runfile('C:/Users/Prisilla/Desktop/CNN11/Bounding Boxes/Satellite_images/New/ResNet50RetinaNet.py', wdir='C:/Users/Prisilla/Desktop/CNN11/Bounding Boxes/Satellite_images/New')

  File "C:\Users\Prisilla\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\Prisilla\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Prisilla/Desktop/CNN11/Bounding Boxes/Satellite_images/New/ResNet50RetinaNet.py", line 32, in <module>
    model = models.load_model(model_path, backbone_name='resnet50')

  File "C:\Users\Prisilla\Desktop\CNN11\Bounding Boxes\Satellite_images\New\models\__init__.py", line 84, in load_model
    return keras.models.load_model(filepath, custom_objects=backbone(backbone_name).custom_objects)

  File "C:\Users\Prisilla\Anaconda3\lib\site-packages\keras\engine\saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)

  File "C:\Users\Prisilla\Anaconda3\lib\site-packages\keras\engine\saving.py", line 584, in load_model
    model = _deserialize_model(h5dict, custom_objects, compile)

np.array values with few errors
Is this partially correct what i obtained?

**Comment by PEE8** [comment]
from losses import smooth_l1

ImportError: cannot import name 'smooth_l1' from 'losses' (C:\Users\Prisilla\Anaconda3\lib\site-packages\keras\losses.py)

Why does this occurs --raising error  even thou losses.py in the same directory of ResNet50RetinaNet.
And i didnot use import keras but it is considering keras/lib/.....
