### ISSUE TITLE
Training the model

### ISSUE THREAD

**Issue by PEE8** [fizyr/keras-retinanet#1225]
I have downloaded the train.py from the keras-retinanet and trying to  train the model for the first time..

(base) C:\Users\Prisilla\Desktop\CNN11\ERetinanet\es_retinanet>python keras_reti
nanet/bin/train.py --weights resnet50_coco_best_v2.1.0.h5 --steps 400 --epochs 2
0 --snapshot-path snapshots csv dataset/train.csv  dataset/classes.csv
Using TensorFlow backend.

It gives error as

Traceback (most recent call last):
  File "keras_retinanet/bin/train.py", line 493, in <module>
    main()
  File "keras_retinanet/bin/train.py", line 408, in main
    backbone = models.backbone(args.backbone)
NameError: name 'models' is not defined

**Comment by PEE8** [comment]
type
from keras_retinanet import models
it resolves
