### ISSUE TITLE
module import fails train.py

### ISSUE THREAD

**Issue by Szymswiat** [fizyr/keras-retinanet#1226]
I'm unable to launch training due to following error:
Using TensorFlow backend.
Traceback (most recent call last):
  File "keras_retinanet/bin/train.py", line 35, in <module>
    from .. import layers  # noqa: F401
  File "keras_retinanet/bin/../../keras_retinanet/layers/__init__.py", line 1, in <module>
    from ._misc import RegressBoxes, UpsampleLike, Anchors, ClipBoxes  # noqa: F401
  File "keras_retinanet/bin/../../keras_retinanet/layers/_misc.py", line 19, in <module>
    from ..utils import anchors as utils_anchors
  File "keras_retinanet/bin/../../keras_retinanet/utils/anchors.py", line 20, in <module>
    from ..utils.compute_overlap import compute_overlap
ModuleNotFoundError: No module named 'keras_retinanet.utils.compute_overlap'

**Comment by ssusie** [comment]
Running

python setup.py build_ext --inplace

before running the train.py helps.
