### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by kawshik8** [fizyr/keras-retinanet#123]
Traceback (most recent call last):
  File "examples/train_csv.py", line 26, in <module>
    from keras_retinanet.preprocessing.csv_generator import CSVGenerator
  File "build/bdist.linux-x86_64/egg/keras_retinanet/preprocessing/csv_generator.py", line 18, in <module>
  File "build/bdist.linux-x86_64/egg/keras_retinanet/preprocessing/generator.py", line 25, in <module>
  File "build/bdist.linux-x86_64/egg/keras_retinanet/utils/image.py", line 21, in <module>
  File "/usr/local/lib/python2.7/dist-packages/cv2/__init__.py", line 9, in <module>
    from .cv2 import *
ImportError: libSM.so.6: cannot open shared object file: No such file or directory

Help!

**Comment by hgaiser** [comment]
Seems your problem is with OpenCV, not keras-retinanet.
