### ISSUE TITLE
AttributeError: 'Node' object has no attribute 'output_masks' (TF2)

### ISSUE THREAD

**Issue by Phisches** [fizyr/keras-retinanet#1242]
Hi, I was following along [ issue #1114 "TypeError: data type not understood" ]( https://github.com/fizyr/keras-retinanet/issues/1114 )and like user icoicqico was running into a new problem after using the proposed fix in #1114

AttributeError: 'Node' object has no attribute 'output_masks' 

The assumption was that it is related to tf-lite:

> Well, it looks like you got further along, this is probably some tf-lite stuff, I can't really help you with that, I'm guessing a lot of layers in keras-retinanet are not supported

However, I see it unrelated to tf-lite but when loading the Retina Net model with tf.keras in TF2.
I would expect that to work in principle, since Retinanet and TF2.Keras both implement the Keras API?

The relevant code should be:

```
from tensorflow import keras
myCustomObjects = backbone('resnet50').custom_objects
model = keras.models.load_model("/tmp/model_conv.h5", myCustomObjects) 
```

with this stack trace

```
Traceback (most recent call last):
  File "loadKeras.py", line 42, in <module>
    model = keras.models.load_model("/tmp/model_conv.h5", myCustomObjects) 
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/saving/save.py", line 146, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 168, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/saving/model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/layers/serialization.py", line 102, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 191, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/engine/network.py", line 906, in from_config
    config, custom_objects)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/engine/network.py", line 1852, in reconstruct_from_config
    process_node(layer, node_data)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/keras/engine/network.py", line 1799, in process_node
    output_tensors = layer(input_tensors, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 75, in symbolic_fn_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/base_layer.py", line 475, in __call__
    previous_mask = _collect_previous_mask(inputs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/base_layer.py", line 1441, in _collect_previous_mask
    mask = node.output_masks[tensor_index]
AttributeError: 'Node' object has no attribute 'output_masks'
```

**Seems to me like a problem with TF2**, but I am really just starting with tensor flow.
What do you think?
Any ideas how to fix that?

By the way, I have cloned the repo with commit da8ceaf and have changed the initializer as proposed by [LaurensHagendoorn 
]( https://github.com/fizyr/keras-retinanet/issues/1114#issuecomment-533091841)
Thanks.

**Comment by hgaiser** [comment]
I don't think (unfortunately) that it is as simple as loading the model with `tf.keras` instead of `keras`. Is that what you are trying to do?

**Comment by Phisches** [comment]
Hi, I am afraid that is exactly what I tried to do ;-)
I think I tried to go a similar approach as  user icoicqico to load the model with tf.keras in the hope that I as a next step could export it as a tf.keras model that can be converted to TensorFlow Serving and TensorFlow Lite.
As I understand you, however loading the trained model with tf.keras will not be possible and the error is an expected outcome?

**Comment by hgaiser** [comment]
> Hi, I am afraid that is exactly what I tried to do ;-)
> I think I tried to go a similar approach as user icoicqico to load the model with tf.keras in the hope that I as a next step could export it as a tf.keras model that can be converted to TensorFlow Serving and TensorFlow Lite.
> As I understand you, however loading the trained model with tf.keras will not be possible and the error is an expected outcome?

If you successfully create a model using `tf.keras`, I think you can call `model.load_weights`, but you can't load the model. Alternatively you could try our new implementation using only tensorflow, but it is still WIP: https://github.com/fizyr/tf-retinanet

**Comment by RafayAK** [comment]
@Phisches @hgaiser Did you manage to find a solution to this. Having a hard time converting the model to TF format for serving.

Should I just create a Flask Server instead?

**Comment by poojaparameswaran99** [comment]
Hi, I am having the same issue. Is there no way to call output_masks via Node?
