### ISSUE TITLE
Tensorflow OOM when batch-size > 1

### ISSUE THREAD

**Issue by nicpayne713** [fizyr/keras-retinanet#1274]
It's possible I'm missing something here but I can't reliably run the training with --batch-size > 1. I've dug in a little bit and it looks like the train_generator actually just reads in all the data, defeating the purpose of the generator in the first place. I'm training on COCO,so if I understand what's happening, the training script performs 1 forward pass on 1 image, updates weights, then moves onto the second image, and so on. 

Can anyone point out what I'm missing?

Examples of logs (cut short because they're long)
2020-02-11 07:02:14.439386: I tensorflow/core/common_runtime/bfc_allocator.cc:917] 1 Chunks of size 186476288 totalling 177.84MiB
2020-02-11 07:02:14.439647: I tensorflow/core/common_runtime/bfc_allocator.cc:917] 1 Chunks of size 229740544 totalling 219.10MiB
2020-02-11 07:02:14.439904: I tensorflow/core/common_runtime/bfc_allocator.cc:917] 1 Chunks of size 922383360 totalling 879.65MiB
2020-02-11 07:02:14.440156: I tensorflow/core/common_runtime/bfc_allocator.cc:917] 1 Chunks of size 933913344 totalling 890.65MiB
2020-02-11 07:02:14.440409: I tensorflow/core/common_runtime/bfc_allocator.cc:921] Sum Total of in-use chunks: 2.60GiB
2020-02-11 07:02:14.440599: I tensorflow/core/common_runtime/bfc_allocator.cc:923] total_region_allocated_bytes_: 3153434880 memory_limit_: 3153435033 available bytes: 153 curr_region_allocation_bytes_: 6306870272
2020-02-11 07:02:14.441038: I tensorflow/core/common_runtime/bfc_allocator.cc:929] Stats: 
Limit:                  3153435033
InUse:                  2791257856
MaxInUse:               2791258368
NumAllocs:                    2798
MaxAllocSize:            933913344

2020-02-11 07:02:14.441574: W tensorflow/core/common_runtime/bfc_allocator.cc:424] ***********************_____*******************************************************************_____
2020-02-11 07:02:14.441849: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at constant_op.cc:172 : Resource exhausted: OOM when allocating tensor with shape[2871754,80] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "C:\miniconda3\envs\keras-retinanet-env\lib\site-packages\keras\engine\training_generator.py", line 220, in fit_generator
    reset_metrics=False)
  File "C:\miniconda3\envs\keras-retinanet-env\lib\site-packages\keras\engine\training.py", line 1514, in train_on_batch
    outputs = self.train_function(ins)
  File "C:\miniconda3\envs\keras-retinanet-env\lib\site-packages\tensorflow_core\python\keras\backend.py", line 3740, in __call__
    outputs = self._graph_fn(*converted_inputs)
  File "C:\miniconda3\envs\keras-retinanet-env\lib\site-packages\tensorflow_core\python\eager\function.py", line 1081, in __call__
    return self._call_impl(args, kwargs)
  File "C:\miniconda3\envs\keras-retinanet-env\lib\site-packages\tensorflow_core\python\eager\function.py", line 1121, in _call_impl
    return self._call_flat(args, self.captured_inputs, cancellation_manager)
  File "C:\miniconda3\envs\keras-retinanet-env\lib\site-packages\tensorflow_core\python\eager\function.py", line 1224, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager)
  File "C:\miniconda3\envs\keras-retinanet-env\lib\site-packages\tensorflow_core\python\eager\function.py", line 511, in call
    ctx=ctx)
  File "C:\miniconda3\envs\keras-retinanet-env\lib\site-packages\tensorflow_core\python\eager\execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.ResourceExhaustedError:  OOM when allocating tensor with shape[16,64,400,600] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node conv1/convolution (defined at \miniconda3\envs\keras-retinanet-env\lib\site-packages\tensorflow_core\python\framework\ops.py:1751) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
 [Op:__inference_keras_scratch_graph_25340]

Function call stack:
keras_scratch_graph

Edit for specs:
I've run this on my laptop and a DL station we have here.
Laptop is Windows 10, 32 gb RAM, Nvidia P1000 GPU. I'm running a Python 3.6 environment with tensorflow-gpu==2.0 and Keras 2.3.1.

Our DL station has 64 GB RAM, and a Titan RTX (which is why the OOM error makes 0 sense to me).

**Comment by hgaiser** [comment]
> It's possible I'm missing something here but I can't reliably run the training with --batch-size > 1. I've dug in a little bit and it looks like the train_generator actually just reads in all the data, defeating the purpose of the generator in the first place.

It only reads in all the annotations, not all the images. The annotations shouldn't take up that much memory (at worst 469Mb in case of COCO I would guess, since that is the file size of the annotations file).

> Our DL station has 64 GB RAM, and a Titan RTX (which is why the OOM error makes 0 sense to me).

The OOM error comes from the GPU, so it says it doesn't have enough memory there; the 64Gb is irrelevant for this error. The Titan RTX has 24Gb of memory, which should be more than enough for training with batch_size > 1. Is someone else perhaps also training on that GPU? What backbone are you using, did you change the default values for image sizes?

**Comment by nicpayne713** [comment]
Thanks for taking a look. I know it only reads in the annotations, and of course that isn't hogging hardly any memory. As far as our DL station goes, I'm the only one using it right now and I monitor it with netdata, so I'm sure no one else is using the card I am. I can actually run with batch_size up to 8, but once there the memory is totally maxed. I'm under the impression that a batch_size of 128 or so is fairly standard. I've looked at the Generator class and the CocoGenerator and it looks like it yields the right batch_size up to a point and then I lose it in the code. 
Am I missing something important where a small batch size still requires a large amount of GPU memory? I don't think the model itself is very big, and I'm really trying to get it running with mobilenet anyways, so I know the memory allocation for that is fairly small.

**Comment by hgaiser** [comment]
> I'm under the impression that a batch_size of 128 or so is fairly standard.

It's not for object detection, I would say a batch size of 2-4 is fairly standard.

Another thing you can try is disabling autotune. I is a feature of cuDNN that selects the best conv algorithm given a certain input shape, but it requires a fair amount of memory. You can disable it by setting the following environment variable: `TF_CUDNN_USE_AUTOTUNE=0`.

**Comment by nicpayne713** [comment]
The batch_size info is eye opening so thank you. I will try disabling autotune but it sounds like there's no issue and I've just had incorrect expectations. 
Thanks for the help, I'll close this issue.
