### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'kernel_size'

### ISSUE THREAD

**Issue by talibiqbal247** [fizyr/keras-retinanet#1278]
runfile('C:/Users/Shah Talib/Documents/Python Scripts/selfTryGAN.py', wdir='C:/Users/Shah Talib/Documents/Python Scripts')
2.3.1
(28, 28)
Traceback (most recent call last):

  File "<ipython-input-20-f6aceb88f640>", line 1, in <module>
    runfile('C:/Users/Shah Talib/Documents/Python Scripts/selfTryGAN.py', wdir='C:/Users/Shah Talib/Documents/Python Scripts')

  File "C:\Users\Shah Talib\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\Shah Talib\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Shah Talib/Documents/Python Scripts/selfTryGAN.py", line 36, in <module>
    model.add(Conv2D(64, kernal_size=3, activation='relu'))

  File "C:\Users\Shah Talib\Anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)

TypeError: __init__() missing 1 required positional argument: 'kernel_size'

**Comment by hgaiser** [comment]
This seems unrelated to our code since the error comes from your test script.
