### ISSUE TITLE
How to convert inference model to tf-lite format?

### ISSUE THREAD

**Issue by ouening** [fizyr/keras-retinanet#1279]
How can I convert the model to tflite?
```python
import tensorflow
model = tf.keras.models.load_model('resnet50_coco_best_v2.1.0.h5')
```
seems not working, errors occured:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-2-67b12d508c69> in <module>
----> 1 model = tf.keras.models.load_model('resnet50_coco_best_v2.1.0.h5')

e:\applications\wpy64-3741\python-3.7.4.amd64\lib\site-packages\tensorflow_core\python\keras\saving\save.py in load_model(filepath, custom_objects, compile)
    144   if (h5py is not None and (
    145       isinstance(filepath, h5py.File) or h5py.is_hdf5(filepath))):
--> 146     return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
    147
    148   if isinstance(filepath, six.string_types):

e:\applications\wpy64-3741\python-3.7.4.amd64\lib\site-packages\tensorflow_core\python\keras\saving\hdf5_format.py in load_model_from_hdf5(filepath, custom_objects, compile)
    166     model_config = json.loads(model_config.decode('utf-8'))
    167     model = model_config_lib.model_from_config(model_config,
--> 168                                                custom_objects=custom_objects)
    169
    170     # set weights

e:\applications\wpy64-3741\python-3.7.4.amd64\lib\site-packages\tensorflow_core\python\keras\saving\model_config.py in model_from_config(config, custom_objects)
     53                     '`Sequential.from_config(config)`?')
     54   from tensorflow.python.keras.layers import deserialize  # pylint: disable=g-import-not-at-top
---> 55   return deserialize(config, custom_objects=custom_objects)
     56
     57

e:\applications\wpy64-3741\python-3.7.4.amd64\lib\site-packages\tensorflow_core\python\keras\layers\serialization.py in deserialize(config, custom_objects)
    104       module_objects=globs,
    105       custom_objects=custom_objects,
--> 106       printable_module_name='layer')

e:\applications\wpy64-3741\python-3.7.4.amd64\lib\site-packages\tensorflow_core\python\keras\utils\generic_utils.py in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    301             custom_objects=dict(
    302                 list(_GLOBAL_CUSTOM_OBJECTS.items()) +
--> 303                 list(custom_objects.items())))
    304       with CustomObjectScope(custom_objects):
    305         return cls.from_config(cls_config)

e:\applications\wpy64-3741\python-3.7.4.amd64\lib\site-packages\tensorflow_core\python\keras\engine\network.py in from_config(cls, config, custom_objects)
    935     """
    936     input_tensors, output_tensors, created_layers = reconstruct_from_config(
--> 937         config, custom_objects)
    938     model = cls(inputs=input_tensors, outputs=output_tensors,
    939                 name=config.get('name'))

e:\applications\wpy64-3741\python-3.7.4.amd64\lib\site-packages\tensorflow_core\python\keras\engine\network.py in reconstruct_from_config(config, custom_objects, created_layers)
   1891   # First, we create all layers and enqueue nodes to be processed
   1892   for layer_data in config['layers']:
-> 1893     process_layer(layer_data)
   1894   # Then we process nodes in order of layer depth.
   1895   # Nodes that cannot yet be processed (if the inbound node

e:\applications\wpy64-3741\python-3.7.4.amd64\lib\site-packages\tensorflow_core\python\keras\engine\network.py in process_layer(layer_data)
   1873       from tensorflow.python.keras.layers import deserialize as deserialize_layer  # pylint: disable=g-import-not-at-top
   1874
-> 1875       layer = deserialize_layer(layer_data, custom_objects=custom_objects)
   1876       created_layers[layer_name] = layer
   1877

e:\applications\wpy64-3741\python-3.7.4.amd64\lib\site-packages\tensorflow_core\python\keras\layers\serialization.py in deserialize(config, custom_objects)
    104       module_objects=globs,
    105       custom_objects=custom_objects,
--> 106       printable_module_name='layer')

e:\applications\wpy64-3741\python-3.7.4.amd64\lib\site-packages\tensorflow_core\python\keras\utils\generic_utils.py in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    303                 list(custom_objects.items())))
    304       with CustomObjectScope(custom_objects):
--> 305         return cls.from_config(cls_config)
    306     else:
    307       # Then `cls` may be a function returning a class.

e:\applications\wpy64-3741\python-3.7.4.amd64\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py in from_config(cls, config)
    517         A layer instance.
    518     """
--> 519     return cls(**config)
    520
    521   def compute_output_shape(self, input_shape):

e:\applications\wpy64-3741\python-3.7.4.amd64\lib\site-packages\tensorflow_core\python\keras\layers\normalization.py in __init__(self, axis, momentum, epsilon, center, scale, beta_initializer, gamma_initializer, moving_mean_initializer, moving_variance_initializer, beta_regularizer, gamma_regularizer, beta_constraint, gamma_constraint, renorm, renorm_clipping, renorm_momentum, fused, trainable, virtual_batch_size, adjustment, name, **kwargs)
    196                **kwargs):
    197     super(BatchNormalizationBase, self).__init__(
--> 198         name=name, **kwargs)
    199     if isinstance(axis, list):
    200       self.axis = axis[:]

e:\applications\wpy64-3741\python-3.7.4.amd64\lib\site-packages\tensorflow_core\python\training\tracking\base.py in _method_wrapper(self, *args, **kwargs)
    455     self._self_setattr_tracking = False  # pylint: disable=protected-access
    456     try:
--> 457       result = method(self, *args, **kwargs)
    458     finally:
    459       self._self_setattr_tracking = previous_value  # pylint: disable=protected-access

e:\applications\wpy64-3741\python-3.7.4.amd64\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py in __init__(self, trainable, name, dtype, dynamic, **kwargs)
    184     }
    185     # Validate optional keyword arguments.
--> 186     generic_utils.validate_kwargs(kwargs, allowed_kwargs)
    187
    188     # Mutable properties

e:\applications\wpy64-3741\python-3.7.4.amd64\lib\site-packages\tensorflow_core\python\keras\utils\generic_utils.py in validate_kwargs(kwargs, allowed_kwargs, error_message)
    716   for kwarg in kwargs:
    717     if kwarg not in allowed_kwargs:
--> 718       raise TypeError(error_message, kwarg)

TypeError: ('Keyword argument not understood:', 'freeze')
```

**Comment by hgaiser** [comment]
We don't officially support converting to tflite, I don't know how to help you with this error.

**Comment by yuvalharpaz** [comment]
> We don't officially support converting to tflite, I don't know how to help you with this error.

@hgaiser Is there any conversion supported keras-retinanet model? If not, do you know which object detection model is supported?

**Comment by hgaiser** [comment]
> @hgaiser Is there any conversion supported keras-retinanet model? If not, do you know which object detection model is supported?

I don't know, I can imagine it is quite difficult because not all ops are supported in tflite. Also, tflite doesn't support unknown input sizes, which we do support in keras-retinanet.

**Comment by cbodenst** [comment]
@hgaiser 
I'm currently also trying to convert to tflite. Indeed It seems that some ops are not supported. The variable input size is not an issue, I will just convert it it to a model fixed input shape model.

Can you help me to figure out which layers might cause this issue:
```

Traceback (most recent call last):
  File "/usr/bin/toco_from_protos", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 93, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/usr/lib/python3.8/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/lib/python3.8/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/lib/python3.8/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/usr/lib/python3.8/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 50, in execute
    output_str = _pywrap_toco_api.TocoConvert(
Exception: /usr/lib/python3.8/site-packages/tensorflow/python/ops/map_fn.py:417:3: error: requires element_shape to be 1D tensor during TF Lite transformation pass
  return map_fn(
  ^
/usr/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py:574:7: note: called from
      return func(*args, **kwargs)
      ^
/usr/lib/python3.8/site-packages/keras_retinanet/backend/tensorflow_backend.py:35:5: note: called from
    return tensorflow.map_fn(*args, **kwargs)
    ^
/usr/lib/python3.8/site-packages/keras_retinanet/layers/filter_detections.py:175:9: note: called from
        outputs = backend.map_fn(
        ^
/usr/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py:309:7: note: called from
      return func(*args, **kwargs)
      ^
/usr/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py:927:19: note: called from
                  outputs = call_fn(cast_inputs, *args, **kwargs)
                  ^
/usr/lib/python3.8/site-packages/tensorflow/python/keras/engine/network.py:888:11: note: called from
          output_tensors = layer(computed_tensors, **kwargs)
          ^
/usr/lib/python3.8/site-packages/tensorflow/python/keras/engine/network.py:717:5: note: called from
    return self._run_internal_graph(
    ^
/usr/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py:927:19: note: called from
                  outputs = call_fn(cast_inputs, *args, **kwargs)
                  ^
/usr/lib/python3.8/site-packages/tensorflow/python/keras/engine/network.py:888:11: note: called from
          output_tensors = layer(computed_tensors, **kwargs)
          ^
/usr/lib/python3.8/site-packages/tensorflow/python/ops/map_fn.py:417:3: error: failed to legalize operation 'tf.TensorListReserve'
  return map_fn(
  ^
/usr/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py:574:7: note: called from
      return func(*args, **kwargs)
      ^
/usr/lib/python3.8/site-packages/keras_retinanet/backend/tensorflow_backend.py:35:5: note: called from
    return tensorflow.map_fn(*args, **kwargs)
    ^
/usr/lib/python3.8/site-packages/keras_retinanet/layers/filter_detections.py:175:9: note: called from
        outputs = backend.map_fn(
        ^
/usr/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py:309:7: note: called from
      return func(*args, **kwargs)
      ^
/usr/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py:927:19: note: called from
                  outputs = call_fn(cast_inputs, *args, **kwargs)
                  ^
/usr/lib/python3.8/site-packages/tensorflow/python/keras/engine/network.py:888:11: note: called from
          output_tensors = layer(computed_tensors, **kwargs)
          ^
/usr/lib/python3.8/site-packages/tensorflow/python/keras/engine/network.py:717:5: note: called from
    return self._run_internal_graph(
    ^
/usr/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py:927:19: note: called from
                  outputs = call_fn(cast_inputs, *args, **kwargs)
                  ^
/usr/lib/python3.8/site-packages/tensorflow/python/keras/engine/network.py:888:11: note: called from
          output_tensors = layer(computed_tensors, **kwargs)
          ^
```
I already found a thread that pointed out how this could be resolved.
Here is the very simple code to start tflite conversion
```
import tensorflow as tf
from keras_retinanet.models import load_model
from keras.layers import Input
from keras.models import Model
if __name__ == "__main__":
    model = load_model("inference.h5")
    fixed_input = Input((720,1280,3))
    fixed_model = Model(fixed_input,model(fixed_input))
    converter = tf.lite.TFLiteConverter.from_keras_model(fixed_model)
    tflite = converter.convert()
```

**Comment by cbodenst** [comment]
Ok I finally got it to work, but i needed to upgrade to tf 2.3.0rc2.
With this version one can define the outputs of map_fn with "fn_output_signature".

So It will be necessary to modify the map_fn call inside of filtered_detections.py.
Also the newest tflite will support variable input dimensions.

So be adding "fn_output_signature" the conversion code becomes very simple:

```
import tensorflow as tf
from keras_retinanet.models import load_model
if __name__ == "__main__":
    model = load_model("inference.h5")
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.target_spec.supported_ops = [
        tf.lite.OpsSet.TFLITE_BUILTINS,
        tf.lite.OpsSet.SELECT_TF_OPS
    ]
    tflite = converter.convert()
    with open("model.tflite","wb") as h:
        h.write(tflite)
```

Maybe I will add a pull request for the changes needed, Im not sure right now how to make this nicely backward compatible

**Comment by cbodenst** [comment]
https://github.com/fizyr/keras-retinanet/pull/1424

**Comment by metanav** [comment]
@cbodenst Why am I getting this error when running interpreter on the converted tflite model?
`RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.Node number 107 (FlexSize) failed to prepare.`

**Comment by gosha20777** [comment]
i tried converting the model and quantizing it but so far with no success:
@cbodenst do you have any ideas?

```python
import cv2
import glob
import tensorflow as tf
from keras.layers import Input
from keras.models import Mode
from keras_retinanet import models
from keras_retinanet.utils.image import preprocess_image
from keras_retinanet import models

def create_model(backbone_name, num_classes=1):
    backbone_factory = models.backbone(backbone_name)
    model = backbone_factory.retinanet(num_classes)
    return models.convert_model(model)

def representative_data_gen():
    fimage = glob.glob('test_data/img/1/*.jpg')
    for input_value in range(10):
        if os.path.exists(fimage[input_value]):
            original_image=cv2.imread(fimage[input_value])
            image_data = cv2.resize(original_image, (512,512))
            image_data = preprocess_image(image_data)
            img_in = image_data[np.newaxis, ...].astype(np.float32)
            print("calibration image {}".format(fimage[input_value]))
            yield [img_in]
        else:
            continue

# create model
backbone = 'resnet50'
model = create_model(backbone)

# convert to int8 tf.lite
fixed_input = Input((512,512,3))
fixed_model = Model(fixed_input,model(fixed_input))
converter = tf.lite.TFLiteConverter.from_keras_model(fixed_model)
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS,
    tf.lite.OpsSet.SELECT_TF_OPS
]
converter.allow_custom_ops = True
converter.representative_dataset = representative_data_gen

tflite = converter.convert()

with open("model_int8.tflite","wb") as h:
    h.write(tflite)
```

and I det an error
```
~/anaconda3/envs/tf-2-3/lib/python3.7/site-packages/tensorflow/lite/python/optimize/calibrator.py in __init__(self, model_content)
     52           _calibration_wrapper.CalibrationWrapper(model_content))
     53     except Exception as e:
---> 54       raise ValueError("Failed to parse the model: %s." % e)
     55     if not self._calibrator:
     56       raise ValueError("Failed to parse the model.")

ValueError: Failed to parse the model: pybind11::init(): factory function returned nullptr.
```

you can find more info here
https://github.com/lacmus-foundation/lacmus-research/blob/master/retinanet_tflite.ipynb

**Comment by meteora9479** [comment]
> @cbodenst Why am I getting this error when running interpreter on the converted tflite model?
> `Traceback (most recent call last): File "interpreter.py", line 17, in <module> interpreter.invoke() File "/Users/metanav/Library/Python/3.7/lib/python/site-packages/tensorflow/lite/python/interpreter.py", line 524, in invoke self._interpreter.Invoke() RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.Node number 107 (FlexSize) failed to prepare.`

I got the same problem. Have someone resolved this ?

**Comment by kriskorrel-cw** [comment]
@meteora9479 @metanav 
I believe this is the answer to that: https://github.com/tensorflow/tensorflow/issues/40157#issuecomment-680798660
So if I understand correctly, allowing specific Tensorflow Ops by setting `tf.lite.OpsSet.SELECT_TF_OPS` makes that the tf lite runtime interpreter will not be able to interpret and execute those ops.

If someone can show me otherwise or has a solution, please let me know!
