### ISSUE TITLE
Efficientnet :  NotImplementedError: Backbone class for  '<function backbone at 0x7f62b932d9e0>' not implemented.

### ISSUE THREAD

**Issue by Samjith888** [fizyr/keras-retinanet#1297]
Trying to change the backbone into efficientnet B7 , but got the following error

Command used :
 `retinanet-train  --steps 80257 --backbone EfficientNetB7 --batch-size 4 --workers 4  --multi-gpu 2 --multi-gpu-force --compute-val-loss --config config/cfg.ini --epochs 10 --snapshot-path snapshots --tensorboard-dir tensorboard  csv dataset/train.csv  dataset/classes.csv --val-annotations dataset/test.csv`

Error : 
```
/home/samjith/anaconda3/envs/v2-keras/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/samjith/anaconda3/envs/v2-keras/lib/python3.7/site-packages/keras_retinanet/bin/train.py:354: UserWarning: Using experimental backbone EfficientNetB7. Only resnet50 has been properly tested.
  warnings.warn('Using experimental backbone {}. Only resnet50 has been properly tested.'.format(parsed_args.backbone))
Traceback (most recent call last):
  File "/home/samjith/anaconda3/envs/v2-keras/bin/retinanet-train", line 8, in <module>
    sys.exit(main())
  File "/home/samjith/anaconda3/envs/v2-keras/lib/python3.7/site-packages/keras_retinanet/bin/train.py", line 430, in main
    backbone = models.backbone(args.backbone)
  File "/home/samjith/anaconda3/envs/v2-keras/lib/python3.7/site-packages/keras_retinanet/models/__init__.py", line 61, in backbone
    raise NotImplementedError('Backbone class for  \'{}\' not implemented.'.format(backbone))
NotImplementedError: Backbone class for  '<function backbone at 0x7f2926da1950>' not implemented.
```

**Comment by Samjith888** [comment]
Issue solved by 
https://github.com/fizyr/keras-retinanet/pull/1158/commits/8a8170e6697a31c583cc3b4e1b3854f75447e1b3
