### ISSUE TITLE
train_csv.py error with args

### ISSUE THREAD

**Issue by alexiskattan** [fizyr/keras-retinanet#134]
I tried running `train_csv.py`.  It used to work but is now throwing an error.  It is very close to working.  

```
2017-11-30 20:41:37.639136: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\35\tensorflow\core\common_runtime\gpu\gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 980 Ti, pci bus id: 0000:01:00.0, compute capability: 5.2)
Traceback (most recent call last):
  File "examples/train_csv.py", line 71, in <module>
    batch_size=args.batch_size
  File "C:\alexis\AppData\Roaming\Python\Python35\site-packages\keras_retinanet-0.0.1-py3.5.egg\keras_retinanet\preprocessing\csv_generator.py", line 136, in __init__
NameError: name 'args' is not defined
```

**Comment by alexiskattan** [comment]
ahh looks like @wassname got it https://github.com/fizyr/keras-retinanet/pull/133

**Comment by hgaiser** [comment]
Should be fixed by https://github.com/fizyr/keras-retinanet/commit/81eb47472e66c200541805a6eaf875890137f390
