### ISSUE TITLE
Problem with training of the model in GPU

### ISSUE THREAD

**Issue by G-Tox** [fizyr/keras-retinanet#1347]
Good day, excuse me I have a problem when I'm training muy own model, I can train the model on CPU, but i have a error when I'm training in GPU, the error is the folllowing:
```
------------------------------------------------------------------------------------
2020-05-06 12:00:49.791164: W tensorflow/core/common_runtime/bfc_allocator.cc:215] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.05GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
.......
2020-05-06 12:01:33.695347: I tensorflow/core/common_runtime/bfc_allocator.cc:654] 1 Chunks of size 154828800 totalling 147.66MiB
2020-05-06 12:01:33.707681: I tensorflow/core/common_runtime/bfc_allocator.cc:654] 1 Chunks of size 207847424 totalling 198.22MiB
2020-05-06 12:01:33.715404: I tensorflow/core/common_runtime/bfc_allocator.cc:654] 1 Chunks of size 247398400 totalling 235.94MiB
2020-05-06 12:01:33.724901: I tensorflow/core/common_runtime/bfc_allocator.cc:658] Sum Total of in-use chunks: 2.78GiB
2020-05-06 12:01:33.732093: I tensorflow/core/common_runtime/bfc_allocator.cc:660] Stats:
Limit:                  3215209267
InUse:                  2985957120
MaxInUse:               3172831232
NumAllocs:                    2063
MaxAllocSize:           1073741824

2020-05-06 12:01:33.752342: W tensorflow/core/common_runtime/bfc_allocator.cc:275] ***********************************************************_*****x********************__************
2020-05-06 12:01:33.764384: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at bias_op.cc:490 : Resource exhausted: OOM when allocating tensor with shape[2048,15100] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "C:\Users\Hp\Downloads\keras-retinanet\keras_retinanet\bin\train.py", line 472, in <module>
    main()
  File "C:\Users\Hp\Downloads\keras-retinanet\keras_retinanet\bin\train.py", line 467, in main
    callbacks=callbacks,
  File "C:\Users\Hp\Anaconda3\envs\AAAA\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Hp\Anaconda3\envs\AAAA\lib\site-packages\keras\engine\training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\Hp\Anaconda3\envs\AAAA\lib\site-packages\keras\engine\training_generator.py", line 217, in fit_generator
    class_weight=class_weight)
  File "C:\Users\Hp\Anaconda3\envs\AAAA\lib\site-packages\keras\engine\training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "C:\Users\Hp\Anaconda3\envs\AAAA\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "C:\Users\Hp\Anaconda3\envs\AAAA\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "C:\Users\Hp\Anaconda3\envs\AAAA\lib\site-packages\tensorflow\python\client\session.py", line 1399, in __call__
    run_metadata_ptr)
  File "C:\Users\Hp\Anaconda3\envs\AAAA\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 526, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[8,256,100,151] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node training/Adam/gradients/classification_submodel/pyramid_classification_3/convolution_grad/Conv2DBackpropInput}} = Conv2DBackpropInput[T=DT_FLOAT, _class=["loc:@training/Adam/cond_32/Switch_2"], data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](training/Adam/gradients/classification_submodel/pyramid_classification_3/convolution_grad/ShapeN, pyramid_classification_3/kernel/read, training/Adam/gradients/classification_submodel/pyramid_classification_3/Relu_grad/ReluGrad)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
-----------------------------------------------------------------------------------------------------------
```
I can see that my GPU is working:
```
2020-05-06 11:59:54.496496: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-05-06 11:59:54.929645: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties:
name: GeForce MX130 major: 5 minor: 0 memoryClockRate(GHz): 1.189
pciBusID: 0000:01:00.0
totalMemory: 4.00GiB freeMemory: 3.35GiB
2020-05-06 11:59:54.936934: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
2020-05-06 11:59:55.936793: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-05-06 11:59:55.942159: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0
2020-05-06 11:59:55.945059: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N
2020-05-06 11:59:55.948480: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3066 MB memory) -> physical GPU (device: 0, name: GeForce MX130, pci bus id: 0000:01:00.0, compute capability: 5.0)
```

**Comment by hgaiser** [comment]
It seems your GPU has 4gb of memory available, which is not enough for your model that you are trying to train. You can try to reduce the batch-size if you have increased it, or try to reduce the image size in the train script.
