### ISSUE TITLE
No module named keras when converting training to inference:

### ISSUE THREAD

**Issue by TimNagle-McNaughton** [fizyr/keras-retinanet#1392]
Having this issue when converting training to inference. May be a separate issue from previously posted issue #1372 as I did not have a problem while training the model.

- python 3.7.7
- keras 2.4.0
- tensorflow 2.2.0

Command
`path\keras-retinanet\keras_retinanet\bin>convert_model.py path\models\train_36.h5 path\TAR_retinanet\models\infer_36.h5`

Result:
`Traceback (most recent call last):
  File "path\keras-retinanet\keras_retinanet\bin\convert_model.py", line 31, in <module>
    from ..utils.config import read_config_file, parse_anchor_parameters
  File "path\keras-retinanet\keras_retinanet\bin\..\..\keras_retinanet\utils\config.py", line 19, in <module>
    import keras
ImportError: No module named keras`

_Originally posted by @TimNagle-McNaughton in https://github.com/fizyr/keras-retinanet/issues/1372#issuecomment-645678679_

**Comment by TimNagle-McNaughton** [comment]
Deleted my virtual env and started from scratch, issue is gone. Likely user error.
