### ISSUE TITLE
Running the code in Windows10 has an error 

### ISSUE THREAD

**Issue by xuangestallone** [fizyr/keras-retinanet#141]
When I run the example code `"python train_pascal.py VOCdevkit2007\VOCdevkit2007\VOC2007"`
I have the following issues, I can't solve it. Can anyone understand it? Thank you!

```
Using TensorFlow backend.
Traceback (most recent call last):
  File "train_pascal.py", line 24, in <module>
    from keras_retinanet.models.resnet import ResNet50RetinaNet
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "C:\Users\shuaigejzx\AppData\Roaming\Python\Python36\site-packages\keras_retinanet-0.0.1-py3.6.egg\keras_retinanet\models\resnet.py", line 25, in <module>
AttributeError: module 'keras_resnet' has no attribute 'custom_objects'
```

**Comment by hgaiser** [comment]
Check the README. You aren't running the correct version of `keras-resnet`.

**Comment by de-vri-es** [comment]
I'm assuming this is fixed when using the proper `keras-resnet` version, so I'm closing this issue. If the problem persists, feel free to re-open the issue.
