### ISSUE TITLE
TypeError: type object got multiple values for keyword argument 'training'

### ISSUE THREAD

**Issue by damasubaie** [fizyr/keras-retinanet#1410]
Hi everyone, I'm trying to run the training script and I keep getting this error:

```
Traceback (most recent call last):
  File "C:\Users\user\retinanet\keras-retinanet-master\keras_retinanet\bin\train.py", line 547, in <module>
    main()
  File "C:\Users\user\retinanet\keras-retinanet-master\keras_retinanet\bin\train.py", line 507, in main
    config=args.config
  File "C:\Users\user\retinanet\keras-retinanet-master\keras_retinanet\bin\train.py", line 117, in create_models
    model          = model_with_weights(backbone_retinanet(num_classes, num_anchors=num_anchors, modifier=modifier, pyramid_levels=pyramid_levels), weights=weights, skip_mismatch=True)
  File "C:\Users\user\retinanet\keras-retinanet-master\keras_retinanet\bin\..\..\keras_retinanet\models\resnet.py", line 38, in retinanet
    return resnet_retinanet(*args, backbone=self.backbone, **kwargs)
  File "C:\Users\user\retinanet\keras-retinanet-master\keras_retinanet\bin\..\..\keras_retinanet\models\resnet.py", line 99, in resnet_retinanet
    resnet = keras_resnet.models.ResNet50(inputs, include_top=False, freeze_bn=True)
  File "C:\Users\user\miniconda3\envs\retinanet\lib\site-packages\keras_resnet\models\_2d.py", line 188, in ResNet50
    return ResNet(inputs, blocks, numerical_names=numerical_names, block=keras_resnet.blocks.bottleneck_2d, include_top=include_top, classes=classes, *args, **kwargs)
  File "C:\Users\user\miniconda3\envs\retinanet\lib\site-packages\keras_resnet\models\_2d.py", line 66, in ResNet
    x = keras_resnet.layers.BatchNormalization(axis=axis, epsilon=1e-5, freeze=freeze_bn, name="bn_conv1")(x)
  File "C:\Users\user\miniconda3\envs\retinanet\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 922, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "C:\Users\user\miniconda3\envs\retinanet\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 265, in wrapper
    raise e.ag_error_metadata.to_exception(e)
TypeError: in user code:

    C:\Users\user\miniconda3\envs\retinanet\lib\site-packages\keras_resnet\layers\_batch_normalization.py:17 call  *
        return super(BatchNormalization, self).call(training=(not self.freeze), *args, **kwargs)

    TypeError: type object got multiple values for keyword argument 'training'
```

Can anyone help? thanks!

**Comment by damasubaie** [comment]
It seems I just had the wrong version of Keras, this fixed it:
`pip install --upgrade keras==2.3.0`
