### ISSUE TITLE
What is this error?

### ISSUE THREAD

**Issue by kawshik8** [fizyr/keras-retinanet#142]
```
Epoch 1/20
  1/800 [..............................] - ETA: 1:00:40 - loss: 1.1321 - regression_loss: 0.0015 - classification_loss: 1.13052017-12-01 16:40:26.685595: I tensorfl
ow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 1798 get requests, put_count=1718 evicted_count=1000 eviction_rate=0.582072 and unsatisfied a
llocation rate=0.656285
2017-12-01 16:40:26.685667: I tensorflow/core/common_runtime/gpu/pool_allocator.cc:259] Raising pool_size_limit_ from 100 to 110
 39/800 [>.............................] - ETA: 16:37 - loss: 1.1293 - regression_loss: 0.0043 - classification_loss: 1.12502017-12-01 16:41:13.202649: I tensorflow
/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 3508 get requests, put_count=3562 evicted_count=1000 eviction_rate=0.280741 and unsatisfied all
ocation rate=0.276226
2017-12-01 16:41:13.202718: I tensorflow/core/common_runtime/gpu/pool_allocator.cc:259] Raising pool_size_limit_ from 256 to 281
677/800 [========================>.....] - ETA: 1:29 - loss: 0.4599 - regression_loss: 0.0038 - classification_loss: 0.4561Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 579, in data_generator_task
    generator_output = next(self._generator)
  File "build/bdist.linux-x86_64/egg/keras_retinanet/preprocessing/generator.py", line 221, in next
    return self.compute_input_output(group)
  File "build/bdist.linux-x86_64/egg/keras_retinanet/preprocessing/generator.py", line 199, in compute_input_output
    image_group, annotations_group = self.preprocess_group(image_group, annotations_group)
  File "build/bdist.linux-x86_64/egg/keras_retinanet/preprocessing/generator.py", line 115, in preprocess_group
    image, annotations = random_transform(image, annotations, self.image_data_generator)
  File "build/bdist.linux-x86_64/egg/keras_retinanet/utils/image.py", line 76, in random_transform
    boxes[index, 0] = float(min(j))
ValueError: min() arg is an empty sequence
678/800 [========================>.....] - ETA: 1:28 - loss: 0.4596 - regression_loss: 0.0038 - classification_loss: 0.4559Traceback (most recent call last):
  File "examples/train_csv1.py", line 117, in <module>
    keras.callbacks.ReduceLROnPlateau(monitor='loss', factor=0.1, patience=2, verbose=1, mode='auto', epsilon=0.0001, cooldown=0, min_lr=0),
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 2046, in fit_generator
    generator_output = next(output_generator)
StopIteration
Exception AttributeError: "'NoneType' object has no attribute 'TF_NewStatus'" in <bound method Session.__del__ of <tensorflow.python.client.session.Session object a
t 0x7f07ac144510>> ignored
```

I'm training using GPU! What is this error?

**Comment by hgaiser** [comment]
Seems you aren't updated to the latest version. You seem to be missing [this](https://github.com/fizyr/keras-retinanet/commit/0e255e08b2fa8a6ec1b797c41677a984e27609bd) fix.

**Comment by kawshik8** [comment]
The error still persists after i do the suggested changes!

**Comment by hgaiser** [comment]
If the error remains the same then I'm guessing it is still not using the updated code. Perhaps you have an older version installed which it is using? Try prefixing your command with `PYTHONPATH=/path/to/keras-retinanet` to be sure it is using your cloned repository.

**Comment by kawshik8** [comment]
You've basically added a way to check if it's an invalid box right?
I have created the csv file such that it is already done(i.e x2>x1 and y2>y1)
I did write the suggested changes in the image.py file..
No changes were reflected.
I tried commenting out the rrandom_transform function and it started working
will that decrease the accuracy?

**Comment by hgaiser** [comment]
If you disable all data augmentation methods then no, it won't. If you keep them enabled then your annotations won't match your image.

The reason I asked to update is because that check prints the box for which the `min(j)` command would throw an error. It would give some more information as to what is going wrong.

**Comment by kawshik8** [comment]
I cloned the new repository !
Still no leads on why this is happening
I went through the code and I think it doesn't recognize the annotated bounding boxes

**Comment by hgaiser** [comment]
Can you select any image and the corresponding annotations, visualize them on that image and check if they are correct? It sounds like your annotations are incorrect (maybe you're encoding your boxes as `(x, y, w, h)` or maybe something like `(y1, x1, y2, x2)` instead of `(x1, y1, x2, y2)`).

I added some [checks](https://github.com/fizyr/keras-retinanet/commit/5f8a3a5b02fdc7c1bbadc5a3c739bac2aee75176) which should catch this error and print a more readable exception. The root cause seems to be your annotations though.

**Comment by kawshik8** [comment]
No they are correct . I visualized every one of them several times to be sure.
Keras-frcnn worked perfectly on my annotations.

**Comment by hgaiser** [comment]
Can you pull the latest code? My guess is that the error will change into a warning. Please look into that image(s) and share it if possible.

**Comment by hgaiser** [comment]
Any update on this ?

**Comment by hgaiser** [comment]
Closing due to inactivity.
