### ISSUE TITLE
Incomplete error

### ISSUE THREAD

**Issue by Weixing-Zhang** [fizyr/keras-retinanet#143]
@de-vri-es Thank you so much for your quick response! 

**Incomplete error popped up when I ran train_csv.py on my custom data**. 
Train_frcnn.py from yhenon has no problem with my data. 

----------------------------------------
(1) 
I tried to run train_csv.py on my custom data with Keras 2.0.9. It would stop at different step of the program if I restarted again. It could stop at Epoch 1/20 156/873[......]. But it never finish a epoch. 

This is the error:
```
=============
Epoch 1/20
 31/873 [>.............................] - ETA: 10:59 - loss: 1.1267 - regression_loss: 0.0020 - classification_loss: 1.1246Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 579, in data_generator_task
    generator_output = next(self._generator)
  File "build/bdist.linux-x86_64/egg/keras_retinanet/preprocessing/generator.py", line 217, in next
    return self.compute_input_output(group)
  File "build/bdist.linux-x86_64/egg/keras_retinanet/preprocessing/generator.py", line 195, in compute_input_output
    image_group, annotations_group = self.preprocess_group(image_group, annotations_group)
  File "build/bdist.linux-x86_64/egg/keras_retinanet/preprocessing/generator.py", line 115, in preprocess_group
    image, annotations = random_transform(image, annotations, self.image_data_generator)
  File "build/bdist.linux-x86_64/egg/keras_retinanet/utils/image.py", line 76, in random_transform
    boxes[index, 0] = float(min(j))
 32/873 [>.............................] - ETA: 10:45 - loss: 1.1265 - regression_loss: 0.0020 - classification_loss: 1.1245Traceback (most recent call last):
  File "train_csv.py", line 117, in <module>
    keras.callbacks.ReduceLROnPlateau(monitor='loss', factor=0.1, patience=2, verbose=1, mode='auto', epsilon=0.0001, cooldown=0, min_lr=0),
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 2046, in fit_generator
    generator_output = next(output_generator)
StopIteration
```

----------------------------------------
(2)  @de-vri-es kindly repied my reported error 

from @de-vri-es "@Weixing-Zhang: The error message you posted is incomplete. The actual exception is missing. That is probably because of the way keras handles exception in data generators (would be improved by fchollet/keras#8485) . I do not think this is the same issue though.

If this is a reproducible error, could you update Keras to latest master (so that you get fchollet/keras#8485) and open a new issue with the updated error message?"

Then I upgraded Keras to latest master from 2.0.9 as @de-vri-es suggested. Another error showed up:
(p.s. the reason I downgraded keras before because ValueError: Error when checking target: expected regression to have shape (None, None, 4) but got array with shape (1, 102438, 5), it seems this error is fixed now). 
```
=============
None
Epoch 1/20
391/873 [============>.................] - ETA: 3:48 - loss: 0.5860 - regression_loss: 0.0018 - classification_loss: 0.5841Traceback (most recent call last):
  File "train_csv.py", line 117, in <module>
    keras.callbacks.ReduceLROnPlateau(monitor='loss', factor=0.1, patience=2, verbose=1, mode='auto', epsilon=0.0001, cooldown=0, min_lr=0),
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 2115, in fit_generator
    generator_output = next(output_generator)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 735, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 635, in data_generator_task
    generator_output = next(self._generator)
  File "build/bdist.linux-x86_64/egg/keras_retinanet/preprocessing/generator.py", line 217, in next
  File "build/bdist.linux-x86_64/egg/keras_retinanet/preprocessing/generator.py", line 195, in compute_input_output
  File "build/bdist.linux-x86_64/egg/keras_retinanet/preprocessing/generator.py", line 115, in preprocess_group
  File "build/bdist.linux-x86_64/egg/keras_retinanet/utils/image.py", line 76, in random_transform
ValueError: min() arg is an empty sequence
```

Any help would be appreciated!!

**Comment by hgaiser** [comment]
I'm guessing your `keras-retinanet` is outdated, could you update it? If you updated, you would likely see a different error, claiming that one of your annotations is incorrect. Each annotation must be in the positive area and must have `x2 > x1` and `y2 > y1`>

**Comment by Weixing-Zhang** [comment]
@hgaiser 
It is still not working. I updated keras-retinanet by running pip install --user --upgrade git+https://github.com/broadinstitute/keras-resnet. I double-checked annotation file (x2 > x1 and y2 > y1). Nobody got this error before? Anyway, really appreciate your excellent work.

None
Epoch 1/20
 48/873 [>.............................] - ETA: 9:50 - loss: 1.0871 - regression_loss: 0.0019 - classification_loss: 1.0852Traceback (most recent call last):
  File "train_csv.py", line 117, in <module>
    keras.callbacks.ReduceLROnPlateau(monitor='loss', factor=0.1, patience=2, verbose=1, mode='auto', epsilon=0.0001, cooldown=0, min_lr=0),
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 2115, in fit_generator
    generator_output = next(output_generator)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 735, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 635, in data_generator_task
    generator_output = next(self._generator)
  File "build/bdist.linux-x86_64/egg/keras_retinanet/preprocessing/generator.py", line 217, in next
  File "build/bdist.linux-x86_64/egg/keras_retinanet/preprocessing/generator.py", line 195, in compute_input_output
  File "build/bdist.linux-x86_64/egg/keras_retinanet/preprocessing/generator.py", line 115, in preprocess_group
  File "build/bdist.linux-x86_64/egg/keras_retinanet/utils/image.py", line 79, in random_transform
ValueError: min() arg is an empty sequence

**Comment by hgaiser** [comment]
That command updates `keras-resnet`, you sure you ran the right command?

**Comment by Weixing-Zhang** [comment]
@hgaiser Besides that, I downloaded the repository from https://github.com/fizyr/keras-retinanet and ran "python setup.py install --user"in the repository.

**Comment by hgaiser** [comment]
I see now that the line number changed from 76 to 79, which means you're probably indeed using the updated version. Strange, it shouldn't happen anymore then.. Could you help me debug this by adding `print(b)` [here](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/utils/image.py#L72) ? It should print all the boxes and when it crashes it will stop printing, I'm curious what the box is where it crashes.

**Comment by Weixing-Zhang** [comment]
@hgaiser 

I added print(b) at the 72nd line.

I got this:

None
Epoch 1/20
[110  50 161 101]
[180  26 234  82]
[237 151 294 210]
[  0 291  81 388]
[432 405 489 463]
[123  33 533 444]
[ 77  75 623 614]
[ 46 274 146 372]
[209 151 257 196]
[ 24 246  80 303]
[216 121 264 172]
[220 341 311 438]
[429 189 508 267]
[ 18 286 206 478]
[251  22 281  56]
[ 37  23 106  96]
[189  45 211  66]
[ 46 141  83 182]
[ 12   1 177 169]
[  0 221  48 288]
[146 120 227 225]
[ 80 307 128 356]
  1/873 [..............................] - ETA: 1:21:07 - loss: 1.1321 - regression_loss: 0.0019 - classification_lo 17/873 [..............................] - ETA: 15:25 - loss: 1.1311 - regression_loss: 0.0019 - classification_loss 37/873 [>.............................] - ETA: 10:41 - loss: 1.1192 - regression_loss: 0.0019 - classification_loss 62/873 [=>............................] - ETA: 9:20 - loss: 1.0812 - regression_loss: 0.0018 - classification_loss: 94/873 [==>...........................] - ETA: 8:06 - loss: 0.9130 - regression_loss: 0.0018 - classification_loss: 0.9111[153  45 199  91]
118/873 [===>..........................] - ETA: 7:20 - loss: 0.8128 - regression_loss: 0.0018 - classification_loss:132/873 [===>..........................] - ETA: 7:00 - loss: 0.7976 - regression_loss: 0.0018 - classification_loss:147/873 [====>.........................] - ETA: 6:36 - loss: 0.7699 - regression_loss: 0.0018 - classification_loss:148/873 [====>.........................] - ETA: 6:34 - loss: 0.7666 - regression_loss: 0.0018 - classification_loss:169/873 [====>.........................] - ETA: 6:15 - loss: 0.7166 - regression_loss: 0.0018 - classification_loss:175/873 [=====>........................] - ETA: 6:18 - loss: 0.7210 - regression_loss: 0.0018 - classification_loss:180/873 [=====>........................] - ETA: 6:10 - loss: 0.7199 - regression_loss: 0.0018 - classification_loss:185/873 [=====>........................] - ETA: 6:07 - loss: 0.7105 - regression_loss: 0.0018 - classification_loss:191/873 [=====>........................] - ETA: 6:02 - loss: 0.7027 - regression_loss: 0.0018 - classification_loss:219/873 [======>.......................] - ETA: 5:44 - loss: 0.6749 - regression_loss: 0.0018 - classification_loss:268/873 [========>.....................] - ETA: 5:03 - loss: 0.6683 - regression_loss: 0.0018 - classification_loss: 0.6665[196 265 259 328]
279/873 [========>.....................] - ETA: 4:53 - loss: 0.6541 - regression_loss: 0.0018 - classification_loss: 0.6522[297 174 320 197]
[297 171 321 201]
297/873 [=========>....................] - ETA: 4:40 - loss: 0.6347 - regression_loss: 0.0018 - classification_loss:306/873 [=========>....................] - ETA: 4:33 - loss: 0.6263 - regression_loss: 0.0018 - classification_loss:310/873 [=========>....................] - ETA: 4:30 - loss: 0.6216 - regression_loss: 0.0018 - classification_loss:326/873 [==========>...................] - ETA: 4:21 - loss: 0.6084 - regression_loss: 0.0018 - classification_loss: 0.6066Traceback (most recent call last):
  File "train_csv.py", line 117, in <module>
    keras.callbacks.ReduceLROnPlateau(monitor='loss', factor=0.1, patience=2, verbose=1, mode='auto', epsilon=0.0001, cooldown=0, min_lr=0),
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 2115, in fit_generator
    generator_output = next(output_generator)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 735, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 635, in data_generator_task
    generator_output = next(self._generator)
  File "build/bdist.linux-x86_64/egg/keras_retinanet/preprocessing/generator.py", line 217, in next
  File "build/bdist.linux-x86_64/egg/keras_retinanet/preprocessing/generator.py", line 195, in compute_input_output
  File "build/bdist.linux-x86_64/egg/keras_retinanet/preprocessing/generator.py", line 115, in preprocess_group
  File "build/bdist.linux-x86_64/egg/keras_retinanet/utils/image.py", line 79, in random_transform
ValueError: min() arg is an empty sequence

**Comment by hgaiser** [comment]
That seems fine. Can you change it to `print(b, mask.shape)` then? Other guess is that the box is outside of the image boundaries.

**Comment by Weixing-Zhang** [comment]
None
Epoch 1/20
(array([  0, 299,  61, 380]), (500, 385, 3))
(array([227, 191, 272, 236]), (500, 334, 3))
(array([104, 109, 139, 146]), (333, 500, 3))
(array([193,  32, 280, 119]), (445, 500, 3))
(array([ 36, 127, 150, 242]), (500, 333, 3))
(array([182,  48, 222,  86]), (500, 290, 3))
(array([257,  80, 292, 118]), (457, 500, 3))
(array([129, 179, 156, 209]), (375, 500, 3))
(array([295, 164, 331, 201]), (375, 500, 3))
(array([232, 165, 305, 231]), (500, 333, 3))
(array([229, 160, 277, 206]), (326, 500, 3))
(array([201, 106, 239, 147]), (333, 500, 3))
(array([ 76,  76, 127, 128]), (500, 357, 3))
(array([149, 220, 167, 240]), (500, 332, 3))
(array([182, 151, 261, 231]), (500, 333, 3))
(array([233, 222, 285, 271]), (500, 295, 3))
(array([101,   3, 423, 328]), (333, 500, 3))
(array([ 73,   0, 110,  38]), (418, 500, 3))
(array([105, 101, 162, 150]), (500, 333, 3))
(array([  4,   0, 247, 247]), (250, 250, 3))
(array([306, 186, 352, 231]), (375, 500, 3))
  9/873 [..............................] - ETA: 23:26 - loss: 1.1317 - regression_loss: 0.0020 - classification_loss: 1.1297(array([155, 230, 190, 258]), (345, 500, 3))))
(array([161, 230, 185, 256]), (345, 500, 3))
 36/873 [>.............................] - ETA: 12:56 - loss: 1.1259 - regression_loss: 0.0020 - classification_loss 60/873 [=>............................] - ETA: 10:40 - loss: 1.0453 - regression_loss: 0.0019 - classification_loss: 1.0434Traceback (most recent call last):, 333, 3))
  File "train_csv.py", line 117, in <module>
    keras.callbacks.ReduceLROnPlateau(monitor='loss', factor=0.1, patience=2, verbose=1, mode='auto', epsilon=0.0001, cooldown=0, min_lr=0),
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 2115, in fit_generator
    generator_output = next(output_generator)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 735, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 635, in data_generator_task
    generator_output = next(self._generator)
  File "build/bdist.linux-x86_64/egg/keras_retinanet/preprocessing/generator.py", line 217, in next
  File "build/bdist.linux-x86_64/egg/keras_retinanet/preprocessing/generator.py", line 195, in compute_input_output
  File "build/bdist.linux-x86_64/egg/keras_retinanet/preprocessing/generator.py", line 115, in preprocess_group
  File "build/bdist.linux-x86_64/egg/keras_retinanet/utils/image.py", line 79, in random_transform
ValueError: min() arg is an empty sequence

**Comment by Weixing-Zhang** [comment]
@hgaiser 
This is the data I used. I'd like to prepare the csv file for you if you can tell me where do you want to put those images.

https://drive.google.com/file/d/1IeB2zIJlw5hS2h409HswKXlfEoV2oKDI/view?usp=sharing

**Comment by hgaiser** [comment]
It seems your annotations are incorrect. I just pushed a [commit](https://github.com/fizyr/keras-retinanet/commit/5f8a3a5b02fdc7c1bbadc5a3c739bac2aee75176) which should check for the case where it goes wrong and then raises an assertion. I believe if you'd use that version, that assertion will be raised in your case. In any case, it seems your annotations don't match your images. Did you export them as `(x1, y1, x2, y2)` ?

**Comment by Weixing-Zhang** [comment]
@hgaiser 
You are right. Your code runs perfectly after I filter out those wrong annotations. I am really sorry for wasting your time. Please allow me have all of your in the acknowledgement section of my research article.

**Comment by hgaiser** [comment]
Good to hear it's working, and thanks :)
