### ISSUE TITLE
train.py gives unexpected error with load_weights()

### ISSUE THREAD

**Issue by chulminkw** [fizyr/keras-retinanet#1443]
Hello, Dev Team

I've been using fizyr keras-retinanet package quite well and thanks for your hard work.   

A few days ago, I used train.py to train csv based annotation files. but train.py gave unexpected errors.
train.py had no problem until recently. My environment is keras 2.3.0 and tensorflow 1.15.2   

Following is my command that I used. 

train.py --epochs=20 --steps=200 \
  csv ~/DLCV/data/raccoon/annotations/raccoon_anno_retina_train.csv \
      ~/DLCV/data/raccoon/annotations/raccoon_class.txt

and following is the error message it gives. It seems like model.load_weights() is bringing the problem

Using TensorFlow backend.
Downloading data from https://github.com/fizyr/keras-models/releases/download/v0.0.1/ResNet-50-model.keras.h5
102948864/102945312 [==============================] - 6s 0us/step
Creating model, this may take a second...
WARNING:tensorflow:From /home/chulmin.kwon999/anaconda3/envs/tf115_test01/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
WARNING:tensorflow:From /home/chulmin.kwon999/anaconda3/envs/tf115_test01/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:4070: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

2020-08-27 04:00:04.357765: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-08-27 04:00:04.987063: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-08-27 04:00:04.987520: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Found device 0 with properties:
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:00:04.0
2020-08-27 04:00:04.996580: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-08-27 04:00:05.102913: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-08-27 04:00:05.149497: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-08-27 04:00:05.165833: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-08-27 04:00:05.270805: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-08-27 04:00:05.348874: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-08-27 04:00:05.548379: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-08-27 04:00:05.548660: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-08-27 04:00:05.549175: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-08-27 04:00:05.549534: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1767] Adding visible gpu devices: 0
2020-08-27 04:00:05.601123: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-08-27 04:00:06.019521: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2200000000 Hz
2020-08-27 04:00:06.020838: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5568e1bdb740 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-27 04:00:06.020878: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-08-27 04:00:06.523438: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-08-27 04:00:06.523987: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5568e1c46800 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-08-27 04:00:06.524019: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla T4, Compute Capability 7.5
2020-08-27 04:00:06.524327: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-08-27 04:00:06.524693: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Found device 0 with properties:
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:00:04.0
2020-08-27 04:00:06.524779: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-08-27 04:00:06.524813: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2020-08-27 04:00:06.524835: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2020-08-27 04:00:06.524870: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2020-08-27 04:00:06.524892: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2020-08-27 04:00:06.524916: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2020-08-27 04:00:06.524940: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-08-27 04:00:06.525036: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-08-27 04:00:06.525466: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-08-27 04:00:06.525799: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1767] Adding visible gpu devices: 0
2020-08-27 04:00:06.545956: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-08-27 04:00:06.571262: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1180] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-08-27 04:00:06.571293: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1186]      0
2020-08-27 04:00:06.571303: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1199] 0:   N
2020-08-27 04:00:06.572784: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-08-27 04:00:06.573260: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-08-27 04:00:06.573642: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1325] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14202 MB memory) -> physical GPU (device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5)
Traceback (most recent call last):
  File "/home/chulmin.kwon999/anaconda3/envs/tf115_test01/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/chulmin.kwon999/anaconda3/envs/tf115_test01/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/chulmin.kwon999/anaconda3/envs/tf115_test01/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Error while reading resource variable pyramid_classification/Variable from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/pyramid_classification/Variable/N10tensorflow3VarE does not exist.
         [[{{node pyramid_classification/ReadVariableOp}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./train.py", line 547, in <module>
    main()
  File "./train.py", line 507, in main
    config=args.config
  File "./train.py", line 117, in create_models
    model          = model_with_weights(backbone_retinanet(num_classes, num_anchors=num_anchors, modifier=modifier, pyramid_levels=pyramid_levels), weights=weights, skip_mismatch=True)
  File "./train.py", line 75, in model_with_weights
    model.load_weights(weights, by_name=True, skip_mismatch=skip_mismatch)
  File "/home/chulmin.kwon999/anaconda3/envs/tf115_test01/lib/python3.6/site-packages/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "/home/chulmin.kwon999/anaconda3/envs/tf115_test01/lib/python3.6/site-packages/keras/engine/network.py", line 1227, in load_weights
    reshape=reshape)
  File "/home/chulmin.kwon999/anaconda3/envs/tf115_test01/lib/python3.6/site-packages/keras/engine/saving.py", line 1330, in load_weights_from_hdf5_group_by_name
    K.batch_set_value(weight_value_tuples)
  File "/home/chulmin.kwon999/anaconda3/envs/tf115_test01/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2960, in batch_set_value
    tf_keras_backend.batch_set_value(tuples)
  File "/home/chulmin.kwon999/anaconda3/envs/tf115_test01/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 3259, in batch_set_value
    get_session().run(assign_ops, feed_dict=feed_dict)
  File "/home/chulmin.kwon999/anaconda3/envs/tf115_test01/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 486, in get_session
    _initialize_variables(session)
  File "/home/chulmin.kwon999/anaconda3/envs/tf115_test01/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 910, in _initialize_variables
    session.run(variables_module.variables_initializer(uninitialized_vars))
  File "/home/chulmin.kwon999/anaconda3/envs/tf115_test01/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/chulmin.kwon999/anaconda3/envs/tf115_test01/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/chulmin.kwon999/anaconda3/envs/tf115_test01/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/chulmin.kwon999/anaconda3/envs/tf115_test01/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Error while reading resource variable pyramid_classification/Variable from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/pyramid_classification/Variable/N10tensorflow3VarE does not exist.
         [[node pyramid_classification/ReadVariableOp (defined at /home/chulmin.kwon999/anaconda3/envs/tf115_test01/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Original stack trace for 'pyramid_classification/ReadVariableOp':
  File "./train.py", line 547, in <module>
    main()
  File "./train.py", line 507, in main
    config=args.config
  File "./train.py", line 117, in create_models
    model          = model_with_weights(backbone_retinanet(num_classes, num_anchors=num_anchors, modifier=modifier, pyramid_levels=pyramid_levels), weights=weights, skip_mismatch=True)
  File "./../../keras_retinanet/models/resnet.py", line 38, in retinanet
    return resnet_retinanet(*args, backbone=self.backbone, **kwargs)
  File "./../../keras_retinanet/models/resnet.py", line 120, in resnet_retinanet
    return retinanet.retinanet(inputs=inputs, num_classes=num_classes, backbone_layers=backbone_layers, **kwargs)
  File "./../../keras_retinanet/models/retinanet.py", line 295, in retinanet
    submodels = default_submodels(num_classes, num_anchors)
  File "./../../keras_retinanet/models/retinanet.py", line 198, in default_submodels
    ('classification', default_classification_model(num_classes, num_anchors))
  File "./../../keras_retinanet/models/retinanet.py", line 71, in default_classification_model
    )(outputs)
  File "/home/chulmin.kwon999/anaconda3/envs/tf115_test01/lib/python3.6/site-packages/keras/engine/base_layer.py", line 463, in __call__
    self.build(unpack_singleton(input_shapes))
  File "/home/chulmin.kwon999/anaconda3/envs/tf115_test01/lib/python3.6/site-packages/keras/layers/convolutional.py", line 147, in build
    constraint=self.bias_constraint)
  File "/home/chulmin.kwon999/anaconda3/envs/tf115_test01/lib/python3.6/site-packages/keras/engine/base_layer.py", line 279, in add_weight
    weight = K.variable(initializer(shape, dtype=dtype),
  File "./../../keras_retinanet/initializers.py", line 37, in __call__
    result = K.ones(shape, dtype=dtype) * -math.log((1 - self.probability) / self.probability)
  File "/home/chulmin.kwon999/anaconda3/envs/tf115_test01/lib/python3.6/site-packages/tensorflow_core/python/ops/variables.py", line 1079, in _run_op
    return tensor_oper(a.value(), *args, **kwargs)
  File "/home/chulmin.kwon999/anaconda3/envs/tf115_test01/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py", line 524, in value
    return self._read_variable_op()
  File "/home/chulmin.kwon999/anaconda3/envs/tf115_test01/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py", line 608, in _read_variable_op
    self._dtype)
  File "/home/chulmin.kwon999/anaconda3/envs/tf115_test01/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_resource_variable_ops.py", line 587, in read_variable_op
    "ReadVariableOp", resource=resource, dtype=dtype, name=name)
  File "/home/chulmin.kwon999/anaconda3/envs/tf115_test01/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/chulmin.kwon999/anaconda3/envs/tf115_test01/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/chulmin.kwon999/anaconda3/envs/tf115_test01/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/chulmin.kwon999/anaconda3/envs/tf115_test01/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/chulmin.kwon999/anaconda3/envs/tf115_test01/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by JianxiangFENG** [comment]
```tensorflow.python.framework.errors_impl.FailedPreconditionError: Error while reading resource variable pyramid_classification/Variable from Container: localhost. This could mean that th
e variable was uninitialized. Not found: Resource localhost/pyramid_classification/Variable/N10tensorflow3VarE does not exist.
         [[node pyramid_classification/ReadVariableOp (defined at /home/nvidia/.local/lib/python2.7/site-packages/keras_retinanet/initializers.py:37) ]]
```
the same for me, it becomes normal when using version 0.5.0. Not understand why it happened.

**Comment by MikeyLev** [comment]
same for me also

**Comment by hansoli68** [comment]
I think the latest code is not compatible with older tensorflow version, maybe it causes by a recent commit for support keras 2.4.

Maybe related to #1442, #1422.

I could train and inference models without any problems. I suggest upgrade your tensorflow and keras to latest if possible.

**Comment by chulminkw** [comment]
Thanks, hansoli68 

I thought keras-retinanet worked well with tensorflow 1.15 and keras 2.3 
I didn't know it had already moved to tensorflow 2.x and keras 2.4

Should I move my environment to tensorflow tensorflow 2.x and keras 2.4 ?

**Comment by chulminkw** [comment]
Hello, hansoli68 

Which tensorflow version are you using? 
It seems like tensorflow 2.2 with keras 2.4 is giving some errors? 
Can I get your tensorflow version info?

**Comment by hansoli68** [comment]
@chulminkw 
I currently using tensorflow 2.3 I had no problems with this version.
Tensorflow 2.2 occurs an error described in issue #1444.
I didn't tested tensorflow 1.15.
