### ISSUE TITLE
retinanet-train gives error

### ISSUE THREAD

**Issue by mavalderrama** [fizyr/keras-retinanet#1444]
Hello dev team, thanks for this awesome work.

I was working with retinanet last 2 weeks and everything was ok since today when I built a new container with a fresh copy of the repository.

I'm getting this error below.

Thanks for your help.

2020-08-27 23:01:26.378718: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 28454 MB memory) -> physical GPU (device: 0, name: GRID V100D-32Q, pci bus id: 0000:02:04.0, compute capability: 7.0)
2020-08-27 23:01:26.380208: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55d3d57dd0f0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-08-27 23:01:26.380232: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GRID V100D-32Q, Compute Capability 7.0
Traceback (most recent call last):
  File "/opt/conda/envs/retinanet/bin/retinanet-train", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/retinanet/lib/python3.6/site-packages/keras_retinanet/bin/train.py", line 516, in main
    config=args.config
  File "/opt/conda/envs/retinanet/lib/python3.6/site-packages/keras_retinanet/bin/train.py", line 121, in create_models
    prediction_model = retinanet_bbox(model=model, anchor_params=anchor_params, pyramid_levels=pyramid_levels)
  File "/opt/conda/envs/retinanet/lib/python3.6/site-packages/keras_retinanet/models/retinanet.py", line 400, in retinanet_bbox
    )([boxes, classification] + other)
  File "/opt/conda/envs/retinanet/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 922, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/opt/conda/envs/retinanet/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 265, in wrapper
    raise e.ag_error_metadata.to_exception(e)
tensorflow.python.autograph.impl.api.StagingError: in user code:

    /opt/conda/envs/retinanet/lib/python3.6/site-packages/keras_retinanet/layers/filter_detections.py:178 call  *
        outputs = backend.map_fn(
    /opt/conda/envs/retinanet/lib/python3.6/site-packages/keras_retinanet/backend/tensorflow_backend.py:36 map_fn  *
        if "shapes" in kwargs:
    /opt/conda/envs/retinanet/lib/python3.6/site-packages/tensorflow/python/autograph/operators/control_flow.py:926 if_stmt
        return _py_if_stmt(cond, body, orelse)
    /opt/conda/envs/retinanet/lib/python3.6/site-packages/tensorflow/python/autograph/operators/control_flow.py:1035 _py_if_stmt
        return body() if cond else orelse()
    /tmp/tmp817ombpn.py:31 if_true
        return (do_return, retval_)

    UnboundLocalError: local variable 'retval_' referenced before assignment

**Comment by hansoli68** [comment]
I confirmed tensorflow 2.2.0 occurs the issue and 2.3.0 doesn't.

**Comment by mavalderrama** [comment]
I can confirm the
