### ISSUE TITLE
Getting this below error when try to load the retinanet model

### ISSUE THREAD

**Issue by vijayymyl** [fizyr/keras-retinanet#1455]
when i execute the below code..
# load retinanet model
model = models.load_model(model_path, backbone_name='resnet50')

tensorflow.python.framework.errors_impl.FailedPreconditionError: Error while reading resource variable pyramid_classification/Variable from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/pyramid_classification/Variable)
         [[{{node pyramid_classification/ReadVariableOp}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/anvijaya/Documents/GitHub/Deep-Learning-For-Hackers-master/keras_retinanet/examples/ResNet50RetinaNet.py", line 58, in <module>
    model = models.load_model(model_path, backbone_name='resnet50')
  File "C:\Users\anvijaya\AppData\Local\Continuum\anaconda3\lib\site-packages\keras_retinanet\models\__init__.py", line 87, in load_model
    return keras.models.load_model(filepath, custom_objects=backbone(backbone_name).custom_objects)
  File "C:\Users\anvijaya\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\engine\saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "C:\Users\anvijaya\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\engine\saving.py", line 584, in load_model
    model = _deserialize_model(h5dict, custom_objects, compile)
  File "C:\Users\anvijaya\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\engine\saving.py", line 336, in _deserialize_model
    K.batch_set_value(weight_value_tuples)
  File "C:\Users\anvijaya\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 2960, in batch_set_value
    tf_keras_backend.batch_set_value(tuples)
  File "C:\Users\anvijaya\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\keras\backend.py", line 3259, in batch_set_value        
    get_session().run(assign_ops, feed_dict=feed_dict)
  File "C:\Users\anvijaya\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\keras\backend.py", line 486, in get_session
    _initialize_variables(session)
  File "C:\Users\anvijaya\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\keras\backend.py", line 910, in _initialize_variables   
    session.run(variables_module.variables_initializer(uninitialized_vars))
  File "C:\Users\anvijaya\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\client\session.py", line 956, in run
    run_metadata_ptr)
  File "C:\Users\anvijaya\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\client\session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\anvijaya\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\client\session.py", line 1359, in _do_run
    run_metadata)
  File "C:\Users\anvijaya\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\client\session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Error while reading resource variable pyramid_classification/Variable from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/pyramid_classification/Variable)
         [[node pyramid_classification/ReadVariableOp (defined at C:\Users\anvijaya\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]

Original stack trace for 'pyramid_classification/ReadVariableOp':
  File "c:/Users/anvijaya/Documents/GitHub/Deep-Learning-For-Hackers-master/keras_retinanet/examples/ResNet50RetinaNet.py", line 58, in <module>
    model = models.load_model(model_path, backbone_name='resnet50')
  File "C:\Users\anvijaya\AppData\Local\Continuum\anaconda3\lib\site-packages\keras_retinanet\models\__init__.py", line 87, in load_model
    return keras.models.load_model(filepath, custom_objects=backbone(backbone_name).custom_objects)
  File "C:\Users\anvijaya\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\engine\saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "C:\Users\anvijaya\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\engine\saving.py", line 584, in load_model
    model = _deserialize_model(h5dict, custom_objects, compile)
  File "C:\Users\anvijaya\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\engine\saving.py", line 274, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "C:\Users\anvijaya\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\engine\saving.py", line 627, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "C:\Users\anvijaya\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\layers\__init__.py", line 168, in deserialize
    printable_module_name='layer')
  File "C:\Users\anvijaya\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\utils\generic_utils.py", line 147, in deserialize_keras_object
    list(custom_objects.items())))
  File "C:\Users\anvijaya\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\engine\network.py", line 1056, in from_config
    process_layer(layer_data)
  File "C:\Users\anvijaya\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\engine\network.py", line 1042, in process_layer
    custom_objects=custom_objects)
  File "C:\Users\anvijaya\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\layers\__init__.py", line 168, in deserialize
    printable_module_name='layer')
  File "C:\Users\anvijaya\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\utils\generic_utils.py", line 147, in deserialize_keras_object
    list(custom_objects.items())))
  File "C:\Users\anvijaya\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\engine\network.py", line 1075, in from_config
    process_node(layer, node_data)
  File "C:\Users\anvijaya\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\engine\network.py", line 1025, in process_node
    layer(unpack_singleton(input_tensors), **kwargs)
  File "C:\Users\anvijaya\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\engine\base_layer.py", line 463, in __call__
    self.build(unpack_singleton(input_shapes))
  File "C:\Users\anvijaya\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\layers\convolutional.py", line 147, in build
    constraint=self.bias_constraint)
  File "C:\Users\anvijaya\AppData\Local\Continuum\anaconda3\lib\site-packages\keras\engine\base_layer.py", line 279, in add_weight
    weight = K.variable(initializer(shape, dtype=dtype),
  File "C:\Users\anvijaya\AppData\Local\Continuum\anaconda3\lib\site-packages\keras_retinanet\initializers.py", line 37, in __call__
    result = K.ones(shape, dtype=dtype) * -math.log((1 - self.probability) / self.probability)
  File "C:\Users\anvijaya\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\ops\variables.py", line 1079, in _run_op
    return tensor_oper(a.value(), *args, **kwargs)
  File "C:\Users\anvijaya\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py", line 524, in value       
    return self._read_variable_op()
  File "C:\Users\anvijaya\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py", line 608, in _read_variable_op
    self._dtype)
  File "C:\Users\anvijaya\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\ops\gen_resource_variable_ops.py", line 587, in read_variable_op
    "ReadVariableOp", resource=resource, dtype=dtype, name=name)
  File "C:\Users\anvijaya\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\anvijaya\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\anvijaya\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "C:\Users\anvijaya\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal    
    op_def=op_def)
  File "C:\Users\anvijaya\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by PhenoBrain** [comment]
same with you, but it somtimes  happened,not alwayes for me ,which maybe related to  tf version

**Comment by vijayymyl** [comment]
> same with you, but it somtimes happened,not alwayes for me ,which maybe related to tf version

what is the TF version which i need to use for to load Retinanet model

**Comment by PhenoBrain** [comment]
@vijayymyl   this [issue](https://github.com/fizyr/keras-retinanet/issues/1443) may help you

**Comment by aashishpt** [comment]
Facing the same issue, and it seems random, sometimes happen sometimes doesn't. Driving me crazy trying to find the cause and fix it.
