### ISSUE TITLE
DLL load failed while importing compute_overlap

### ISSUE THREAD

**Issue by fjsaezm** [fizyr/keras-retinanet#1486]
I've been trying to run train in my own dataset. I've already done `python setup.py build_ext --inplace` and it seems that it worked well. However, when I execute:
`
python keras-retinanet/keras_retinanet/bin/train.py csv annotations CropsTrain.csv classes classes.csv --val-annotations CropsVal.csv
`
I get 
`
2020-11-11 12:10:08.281465: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
Traceback (most recent call last):
  File "keras-retinanet/keras_retinanet/bin/train.py", line 34, in <module>
    from .. import layers  # noqa: F401
  File "keras-retinanet/keras_retinanet/bin\..\..\keras_retinanet\layers\__init__.py", line 1, in <module>
    from ._misc import RegressBoxes, UpsampleLike, Anchors, ClipBoxes  # noqa: F401
  File "keras-retinanet/keras_retinanet/bin\..\..\keras_retinanet\layers\_misc.py", line 20, in <module>
    from ..utils import anchors as utils_anchors
  File "keras-retinanet/keras_retinanet/bin\..\..\keras_retinanet\utils\anchors.py", line 20, in <module>
    from ..utils.compute_overlap import compute_overlap
ImportError: DLL load failed while importing compute_overlap: The parameter is incorrect.
`

And I can't solve it. For extra info, it also fails when I run `python setup.py install`, with a *permission denied* error:
`
[Errno 13] Permission denied: 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\\Lib\\site-packages\\test-easy-install-18464.write-test'
`

Any help? Thanks!!!

**Comment by toolgood** [comment]
me too

**Comment by andreYoo** [comment]
I found a solution.

Mvoe 'examples' and 'snapshots' directories into 'keras-retinanet' (Subdirectory of main directory). probably it is the problems that the source code could not find the suitable library path.

**Comment by nacayu** [comment]
hello @fjsaezm, have your solved this problem?
