### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'ConfigProto'

### ISSUE THREAD

**Issue by Microset** [fizyr/keras-retinanet#1492]
Ubuntu18.04
tensorflow: 2.2.0
keras: 2.3.1
cuda: 10.1
cudnn: 7.6
keras-retinanet==0.4.1

I got error:
$ retinanet-train --batch-size 2 --steps 2989 --epochs 50 --weights retinanet/resnet50_coco_best_v2.1.0.h5 --snapshot-path retinanet/snapshots csv retinanet/train.csv retinanet/classes.csv
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/../.virtualenvs/retinanet/bin/retinanet-train", line 33, in <module>
    sys.exit(load_entry_point('keras-retinanet==0.4.1', 'console_scripts', 'retinanet-train')())
  File "/home/.../.virtualenvs/retinanet/lib/python3.6/site-packages/keras_retinanet-0.4.1-py3.6-linux-x86_64.egg/keras_retinanet/bin/train.py", line 417, in main
    keras.backend.tensorflow_backend.set_session(get_session())
  File "/home/.../.virtualenvs/retinanet/lib/python3.6/site-packages/keras_retinanet-0.4.1-py3.6-linux-x86_64.egg/keras_retinanet/bin/train.py", line 65, in get_session
    config = tf.ConfigProto()
AttributeError: module 'tensorflow' has no attribute 'ConfigProto'

Thank you

**Comment by Microset** [comment]
Ubuntu: 18.04
tensorflow: 2.4..0
keras: 2.4.3
cuda: 10.1
cudnn: 7.6
keras-retinanet: 1.0.0

Good day!
Changing version fixing this problem.
You can close my question.
Thank you for your contributions.
