### ISSUE TITLE
Convert to onnx model

### ISSUE THREAD

**Issue by QuantumLiu** [fizyr/keras-retinanet#1500]
I got error when I try to convert retinanet(oid resnet) to onnx model.
It may caused by arg `other` in layer `FilterDetections`
```
from keras_retinanet import models as retina_models
m=retina_models.load_model('/home/re01/pyprojects/ModelWeights/keras-retinanet/retinanet_resnet152_500_classes_0.4991_converted.h5',backbone_name='resnet152')
import keras2onnx

onnx_model = keras2onnx.convert_keras(m, m.name,target_opset=11)
temp_model_file = 'retina_res152_oid.onnx'
keras2onnx.save_model(onnx_model, temp_model_file,)
```

Log:
```
WARN: No corresponding ONNX op matches the tf.op node retinanet-bbox/filtered_detections/map/TensorArrayV2Stack/TensorListStack of type TensorListStack
      The generated ONNX model needs run with the custom op supports.
Traceback (most recent call last):
  File "retina2onnx.py", line 13, in <module>
    onnx_model = keras2onnx.convert_keras(m, m.name,target_opset=11)
  File "/home/re01/anaconda3/envs/tf2cpu/lib/python3.6/site-packages/keras2onnx/main.py", line 80, in convert_keras
    parse_graph(topology, tf_graph, target_opset, output_names, output_dict)
  File "/home/re01/anaconda3/envs/tf2cpu/lib/python3.6/site-packages/keras2onnx/parser.py", line 841, in parse_graph
    ) if is_tf2 and is_tf_keras else _parse_graph_core(
  File "/home/re01/anaconda3/envs/tf2cpu/lib/python3.6/site-packages/keras2onnx/parser.py", line 729, in _parse_graph_core_v2
    _on_parsing_tf_nodes(graph, layer_info.nodelist, varset, topology.debug_mode)
  File "/home/re01/anaconda3/envs/tf2cpu/lib/python3.6/site-packages/keras2onnx/parser.py", line 323, in _on_parsing_tf_nodes
    var_type = infer_variable_type(i_, varset.target_opset)
  File "/home/re01/anaconda3/envs/tf2cpu/lib/python3.6/site-packages/keras2onnx/_parser_tf.py", line 48, in infer_variable_type
    "Unable to find out a correct type for tensor type = {} of {}".format(tensor_type, tensor.name))
ValueError: Unable to find out a correct type for tensor type = <dtype: 'variant'> of retinanet-bbox/filtered_detections/map/while/exit/_34:0

```

**Comment by QuantumLiu** [comment]
Well, it may caused by tf.map_fn, I'm trying to change it. But got error....
```
        dtypes = ['float32', 'float32', 'int32'] #+ [o.dtype for o in other]
        shapes = [(self.max_detections, 4), (self.max_detections,), (self.max_detections,)]
        #shapes.extend([(self.max_detections,) + o.shape[2:] for o in other])
# =============================================================================
#         outputs = backend.map_fn(
#             _filter_detections,
#             elems=[boxes, classification],
#             dtype=dtypes,
#             shapes=shapes,
#             parallel_iterations=self.parallel_iterations,
#         )
# =============================================================================
        outputs = _filter_detections([boxes, classification])

```
