### ISSUE TITLE
train.py Error with Generators

### ISSUE THREAD

**Issue by boldi124** [fizyr/keras-retinanet#1551]
Using TensorFlow backend.
Traceback (most recent call last):
  File "train.py", line 553, in <module>
    main()
  File "train.py", line 483, in main
    train_generator, validation_generator = create_generators(args, backbone.preprocess_image)
  File "train.py", line 281, in create_generators
    train_generator = PascalVocGenerator(
  File "..\..\keras_retinanet\preprocessing\pascal_voc.py", line 92, in __init__
    self.image_names = [line.strip().split(None, 1)[0] for line in
  File "..\..\keras_retinanet\preprocessing\pascal_voc.py", line 92, in <listcomp>
    self.image_names = [line.strip().split(None, 1)[0] for line in
IndexError: list index out of range

**Comment by boldi124** [comment]
do not have line breaks at the end of your train.txt
