### ISSUE TITLE
Additional ratios / scales?

### ISSUE THREAD

**Issue by pstucki** [fizyr/keras-retinanet#174]
hey
I am trying to detect some object-classes with the resnet-retinanet. Some objects are narrow and high others are low and wide. To detect all of them I have to add additional ratios and scales. 

```python
AnchorParameters.default = AnchorParameters(
    sizes=[32,64,128,256,512],
    strides=[8,16,32, 64,128],
    ratios=np.array([0.4, 0.8, 1,1.2, 3, 5], keras.backend.floatx()),
    scales=np.array([2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)], keras.backend.floatx()),
)
 ```
When I run the code I get a InvalidArgumentError. The Shapes are not the same size:

```python
InvalidArgumentError (see above for traceback): Incompatible shapes: [1,120880,4] vs. [1,67995,4]
         [[Node: loss/regression_loss/sub = Sub[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](regression/concat, loss/regression_loss/strided_slice)]]
         [[Node: loss/classification_loss/Mean_2/_2065 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", 
```

Which parameters do I have to manipulate to get support for more than 3 ratios and/or scales?
Thank you!

**Comment by vanphuctran** [comment]
I think you should also change the ratio in the _misc.py file.

**Comment by hgaiser** [comment]
@vanphuctran is right. It isn't pretty, and it's something I intend to look into after "v1.0" is done, but for now if you have to use non-standard ratios/scales you have to do so dirty editing.

**Comment by pstucki** [comment]
many thanks for your responds, @vanphuctran and @hgaiser 

I've managed to get rid of the problem by setting fixed ratio and scale in the generate_anchors function (utilitis.anchors.py script).

```python
def generate_anchors(base_size=16, ratios=None, scales=None):
    """
    Generate anchor (reference) windows by enumerating aspect ratios X
    scales w.r.t. a reference window.
    """

    '''
    if ratios is None:
        ratios = np.array([0.5, 1, 2])
    if scales is None:
        scales = np.array([2 0, 2 (1.0 / 3.0), 2 ** (2.0 / 3.0)])
    '''

    ratios = np.array([0.2, 0.5, 0.8, 1, 1.5, 2, 6, 8], keras.backend.floatx())
    scales = np.array([2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)]], keras.backend.floatx())

    num_anchors = len(ratios) * len(scales)

    ...
```

**Comment by hgaiser** [comment]
Awesome, I'll close this issue then.

**Comment by SargamModak** [comment]
I want additional ratios and for that I've modified the following files like:

in layers/_misc.py
```
class Anchors(keras.layers.Layer):
    def __init__(self, size, stride, ratios=None, scales=None, *args, **kwargs):
        self.size   = size
        self.stride = stride
        self.ratios = ratios
        self.scales = scales

        if ratios is None:
            # self.ratios  = np.array([0.5, 1, 2], keras.backend.floatx()),
            self.ratios = np.array([0.25, 0.5, 1, 2], keras.backend.floatx()),
        elif isinstance(ratios, list):
            self.ratios  = np.array(ratios)
        if scales is None:
            self.scales  = np.array([2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)], keras.backend.floatx()),
        elif isinstance(scales, list):
            self.scales  = np.array(scales)
```
...

in models/retinanet.py:

```
AnchorParameters.default = AnchorParameters(
    sizes   = [32, 64, 128, 256, 512],
    strides = [8, 16, 32, 64, 128],
    # ratios  = np.array([0.5, 1, 2], keras.backend.floatx()),
    ratios  = np.array([0.25, 0.5, 1, 2], keras.backend.floatx()),
    scales  = np.array([2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)], keras.backend.floatx()),
)
```


and in utils/anchors.py:

```
def anchors_for_shape(
    image_shape,
    pyramid_levels=None,
    ratios=None,
    scales=None,
    strides=None,
    sizes=None,
    shapes_callback=None,
):
    if pyramid_levels is None:
        pyramid_levels = [3, 4, 5, 6, 7]
    if strides is None:
        strides = [2 ** x for x in pyramid_levels]
    if sizes is None:
        sizes = [2 ** (x + 2) for x in pyramid_levels]
    if ratios is None:
        # ratios = np.array([0.5, 1, 2])
        ratios = np.array([0.25, 0.5, 1, 2])
    if scales is None:
        scales = np.array([2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)])
```

```
def generate_anchors(base_size=16, ratios=None, scales=None):
    """
    Generate anchor (reference) windows by enumerating aspect ratios X
    scales w.r.t. a reference window.
    """

    if ratios is None:
        # ratios = np.array([0.5, 1, 2])
        ratios = np.array([0.25,  0.5, 1, 2])

    if scales is None:
```
        scales = np.array([2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)])

still I am getting error:
```
InvalidArgumentError (see above for traceback): Incompatible shapes: [1,53838] vs. [1,71784]
	 [[Node: boxes/mul_9 = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](boxes/Exp_1, boxes/sub_1)]]
	 [[Node: filtered_detections/map/while/strided_slice_21/_3525 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2599_filtered_detections/map/while/strided_slice_21", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopfiltered_detections/map/while/non_max_suppression/iou_threshold/_3423)]]
```
Am I supposed to make any other changes for supporting additional values for ratios?

**Comment by JudyMRSD** [comment]
Hello, I'm copy pasting the same lines to try different aspect ratios, but still got the same error. Do you have any suggestions? Thanks a lot! 
def generate_anchors(base_size=16, ratios=None, scales=None):
    """
    Generate anchor (reference) windows by enumerating aspect ratios X
    scales w.r.t. a reference window.
    """

    '''
    if ratios is None:
        ratios = np.array([0.5, 1, 2])
    if scales is None:
        scales = np.array([2 0, 2 (1.0 / 3.0), 2 ** (2.0 / 3.0)])
    '''

    ratios = np.array([0.2, 0.5, 0.8, 1, 1.5, 2, 6, 8], keras.backend.floatx())
    scales = np.array([2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)]), keras.backend.floatx())

    num_anchors = len(ratios) * len(scales)

    ...

error message:
```
Epoch 1/100
2018-08-04 22:58:07.639446: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [1,2975928] vs. [1,1115973]
	 [[Node: metrics/acc/Equal = Equal[T=DT_INT64, _device="/job:localhost/replica:0/task:0/device:GPU:0"](metrics/acc/ArgMax, metrics/acc/ArgMax_1)]]
2018-08-04 22:58:07.639592: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [1,2975928] vs. [1,1115973]
	 [[Node: metrics/acc/Equal = Equal[T=DT_INT64, _device="/job:localhost/replica:0/task:0/device:GPU:0"](metrics/acc/ArgMax, metrics/acc/ArgMax_1)]]
2018-08-04 22:58:07.639845: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [1,2975928] vs. [1,1115973]
	 [[Node: metrics/acc/Equal = Equal[T=DT_INT64, _device="/job:localhost/replica:0/task:0/device:GPU:0"](metrics/acc/ArgMax, metrics/acc/ArgMax_1)]]
2018-08-04 22:58:07.639927: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [1,2975928] vs. [1,1115973]
	 [[Node: metrics/acc/Equal = Equal[T=DT_INT64, _device="/job:localhost/replica:0/task:0/device:GPU:0"](metrics/acc/ArgMax, metrics/acc/ArgMax_1)]]
2018-08-04 22:58:07.640013: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Incompatible shapes: [1,2975928] vs. [1,1115973]
	 [[Node: metrics/acc/Equal = Equal[T=DT_INT64, _device="/job:localhost/replica:0/task:0/device:GPU:0"](metrics/acc/ArgMax, metrics/acc/ArgMax_1)]]
Traceback (most recent call last):
  File "/home/jinz1/anaconda/envs/keras_retinanet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/home/jinz1/anaconda/envs/keras_retinanet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/home/jinz1/anaconda/envs/keras_retinanet/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [1,2975928] vs. [1,1115973]
	 [[Node: metrics/acc/Equal = Equal[T=DT_INT64, _device="/job:localhost/replica:0/task:0/device:GPU:0"](metrics/acc/ArgMax, metrics/acc/ArgMax_1)]]
	 [[Node: loss/regression_loss/Mean_2/_2075 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_5231_loss/regression_loss/Mean_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 294, in <module>
    main()
  File "train.py", line 288, in main
    callbacks=callbacks,
  File "/home/jinz1/anaconda/envs/keras_retinanet/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/jinz1/anaconda/envs/keras_retinanet/lib/python3.6/site-packages/keras/engine/training.py", line 2177, in fit_generator
    class_weight=class_weight)
  File "/home/jinz1/anaconda/envs/keras_retinanet/lib/python3.6/site-packages/keras/engine/training.py", line 1849, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/jinz1/anaconda/envs/keras_retinanet/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2475, in __call__
    **self.session_kwargs)
  File "/home/jinz1/anaconda/envs/keras_retinanet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/jinz1/anaconda/envs/keras_retinanet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/jinz1/anaconda/envs/keras_retinanet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/jinz1/anaconda/envs/keras_retinanet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [1,2975928] vs. [1,1115973]
	 [[Node: metrics/acc/Equal = Equal[T=DT_INT64, _device="/job:localhost/replica:0/task:0/device:GPU:0"](metrics/acc/ArgMax, metrics/acc/ArgMax_1)]]
	 [[Node: loss/regression_loss/Mean_2/_2075 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_5231_loss/regression_loss/Mean_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'metrics/acc/Equal', defined at:
  File "train.py", line 294, in <module>
    main()
  File "train.py", line 266, in main
    freeze_backbone=Freeze_Backbone
  File "train.py", line 127, in create_models
    metrics=['accuracy']
  File "/home/jinz1/anaconda/envs/keras_retinanet/lib/python3.6/site-packages/keras/engine/training.py", line 914, in compile
    handle_metrics(output_metrics)
  File "/home/jinz1/anaconda/envs/keras_retinanet/lib/python3.6/site-packages/keras/engine/training.py", line 911, in handle_metrics
    mask=masks[i])
  File "/home/jinz1/anaconda/envs/keras_retinanet/lib/python3.6/site-packages/keras/engine/training.py", line 426, in weighted
    score_array = fn(y_true, y_pred)
  File "/home/jinz1/anaconda/envs/keras_retinanet/lib/python3.6/site-packages/keras/metrics.py", line 31, in categorical_accuracy
    K.argmax(y_pred, axis=-1)),
  File "/home/jinz1/anaconda/envs/keras_retinanet/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 1576, in equal
    return tf.equal(x, y)
  File "/home/jinz1/anaconda/envs/keras_retinanet/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 1476, in equal
    "Equal", x=x, y=y, name=name)
  File "/home/jinz1/anaconda/envs/keras_retinanet/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/jinz1/anaconda/envs/keras_retinanet/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/jinz1/anaconda/envs/keras_retinanet/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Incompatible shapes: [1,2975928] vs. [1,1115973]
	 [[Node: metrics/acc/Equal = Equal[T=DT_INT64, _device="/job:localhost/replica:0/task:0/device:GPU:0"](metrics/acc/ArgMax, metrics/acc/ArgMax_1)]]
	 [[Node: loss/regression_loss/Mean_2/_2075 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_5231_loss/regression_loss/Mean_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]


```
