### ISSUE TITLE
Train from scratch

### ISSUE THREAD

**Issue by shaohuifangit** [fizyr/keras-retinanet#264]
I use ImageNet's weights to train my data, but total loss remains around 0.4. So instead of using a model trained from ImageNet, I'd like to try training from scratch. What should I do?

**Comment by deepaklunked** [comment]
When executing the train.py script, try passing the argument "--weights None"..
Example, if you are using csv annotations, then try this command: 
"python train.py --weights None <annotation.csv> <classmapping.csv>"

**Comment by shaohuifangit** [comment]
I see. Thank you！

**Comment by hgaiser** [comment]
A total loss of 0.4 is quite nice though. I suspect most of it is in the regression loss?

**Comment by shaohuifangit** [comment]
In my experiment, loss comes mainly from classification_loss, which remains around 0.35. After 20 epochs (epoch_length = 10000), loss does not decrease. And after I've done 70 epochs, I test on my images, even though it comes from the training set and can not detect objects with scores below 0.1.

**Comment by hgaiser** [comment]
Closing due to inactivity.

**Comment by KienVu2368** [comment]
When I run: keras_retinanet/bin/train.py --weights None csv <annotation.csv> <classmapping.csv>
I have error: 
Traceback (most recent call last):
  File "keras_retinanet/bin/train.py", line 308, in <module>
    main()
  File "keras_retinanet/bin/train.py", line 284, in main
    model, training_model, prediction_model = create_models(num_classes=train_generator.num_classes(), weights=args.weights, multi_gpu=args.multi_gpu)
  File "keras_retinanet/bin/train.py", line 70, in create_models
    model            = resnet50_retinanet(num_classes, weights=weights, nms=True)
  File "keras_retinanet/bin/../../keras_retinanet/models/resnet.py", line 89, in resnet50_retinanet
    return resnet_retinanet(num_classes=num_classes, backbone=50, inputs=inputs, weights=weights, skip_mismatch=skip_mismatch, **kwargs)
  File "keras_retinanet/bin/../../keras_retinanet/models/resnet.py", line 83, in resnet_retinanet
    model.load_weights(weights_path, by_name=True, skip_mismatch=skip_mismatch)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/keras/engine/topology.py", line 2638, in load_weights
    f = h5py.File(filepath, mode='r')
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/h5py/_hl/files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/h5py/_hl/files.py", line 99, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'None', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

What should I do?

**Comment by de-vri-es** [comment]
@KienVu2368: Please don't hijack issues like this.
