### ISSUE TITLE
TypeError: Expected binary or unicode string, got <tf.Tensor 'anchors_0/mul:0' shape=(?,) dtype=float32>

### ISSUE THREAD

**Issue by jhonygiraldo** [fizyr/keras-retinanet#372]
Hi there,

I'm trying to train my own database with:

_keras_retinanet/bin/train.py csv /home/jhony/objectRecognitionBS/annotations.csv /home/jhony/objectRecognitionBS/classMapping.csv_

I get the following error:
```
[...]
Creating model, this may take a second...
Traceback (most recent call last):
  File "keras_retinanet/bin/train.py", line 426, in <module>
    main()
  File "keras_retinanet/bin/train.py", line 394, in main
    freeze_backbone=args.freeze_backbone
  File "keras_retinanet/bin/train.py", line 91, in create_models
    model            = model_with_weights(backbone_retinanet(num_classes, backbone=backbone, nms=True, modifier=modifier), weights=weights, skip_mismatch=True)
  File "keras_retinanet/bin/../../keras_retinanet/models/resnet.py", line 80, in resnet_retinanet
    return retinanet.retinanet_bbox(inputs=inputs, num_classes=num_classes, backbone_layers=resnet.outputs[1:], **kwargs)
  File "keras_retinanet/bin/../../keras_retinanet/models/retinanet.py", line 348, in retinanet_bbox
    model = retinanet(inputs=inputs, num_classes=num_classes, **kwargs)
  File "keras_retinanet/bin/../../keras_retinanet/models/retinanet.py", line 312, in retinanet
    anchors  = __build_anchors(anchor_parameters, features)
  File "keras_retinanet/bin/../../keras_retinanet/models/retinanet.py", line 265, in __build_anchors
    )(f) for i, f in enumerate(features)
  File "/home/jhony/anaconda2/envs/tensorflow/lib/python2.7/site-packages/keras/engine/topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)
  File "keras_retinanet/bin/../../keras_retinanet/layers/_misc.py", line 54, in call
    anchors = backend.shift(features_shape[1:3], self.stride, self.anchors)
  File "keras_retinanet/bin/../../keras_retinanet/backend/common.py", line 63, in shift
    shift_x = keras.backend.reshape(shift_x, [-1])
  File "/home/jhony/anaconda2/envs/tensorflow/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1894, in reshape
    return tf.reshape(x, shape)
  File "/home/jhony/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 5782, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/home/jhony/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 513, in _apply_op_helper
    raise err
TypeError: Expected binary or unicode string, got <tf.Tensor 'anchors_0/mul:0' shape=(?,) dtype=float32
```

Any help would be greatly appreciated.
Thank you in advance!

**Comment by hgaiser** [comment]
Could you make sure your libraries are up to date? What versions are you using?

**Comment by jhonygiraldo** [comment]
Hi @hgaiser,

The version of tensorflow is 1.7.0 and the version of keras is 2.1.5

**Comment by hgaiser** [comment]
Hmm the error seems really weird to me. I don't think the issue is in keras-retinanet to be honest.

Could you try running the following:

```python
import keras.backend

a = keras.backend.zeros((10,))
a = keras.backend.reshape(a, (5, 2))
print(a)
```

**Comment by jhonygiraldo** [comment]
Hi @hgaiser, the output is:

`Tensor("Reshape:0", shape=(5, 2), dtype=float32)`

**Comment by jhonygiraldo** [comment]
That result was obtained with python2. In fact I don't have installed python 3. Should I installed it?

**Comment by hgaiser** [comment]
It's worth a shot.

**Comment by jhonygiraldo** [comment]
Hi @hgaiser,

I get the same result with python3 (`Tensor("Reshape:0", shape=(5, 2), dtype=float32)`). In the same way, I created an environment for Python 3.6 and I installed tensorflow, keras, and RetinaNet again. I tried to run again the script train.py (`keras_retinanet/bin/train.py csv /home/jhony/objectRecognitionBS/annotations.csv /home/jhony/objectRecognitionBS/classMapping.csv`) and I get the same error (`TypeError: Expected binary or unicode string, got <tf.Tensor 'anchors_0/mul:0' shape=(?,) dtype=float32>`)

When I run the example _ResNet50RetinaNet.ipynb_ with the python3.6 environment I get the same error (`TypeError: Expected binary or unicode string, got <tf.Tensor 'anchors_0/mul:0' shape=(?,) dtype=float32>`). However, this example runs well with python2.

Maybe I made a mistake installing some library. Probably I will reinstall all again.

Best.

**Comment by hgaiser** [comment]
Did reinstalling help?

**Comment by hgaiser** [comment]
Closing due to inactivity. Feel free to re-open if it is relevant.

**Comment by CrRak** [comment]
can't find solution to this problem.

**Comment by danamyu** [comment]
I am also running into this error. I am using Python 3.6, Tensorflow 1.14, Keras 2.3.0.
Any chance we can open this issue back up?

I have tried reinstalling the libraries and running the Tensorflow code you suggested above:

>>> a=keras.backend.zeros((10,))
>>> a=keras.backend.reshape(a,(5,2))
>>> print(a)
Tensor("Reshape:0", shape=(5, 2), dtype=float32)

Here is the full error:

tracking <tf.Variable 'Variable:0' shape=(9, 4) dtype=float32> anchors
Traceback (most recent call last):
  File "keras_retinanet/bin/train.py", line 530, in <module>
    main()
  File "keras_retinanet/bin/train.py", line 490, in main
    config=args.config
  File "keras_retinanet/bin/train.py", line 118, in create_models
    prediction_model = retinanet_bbox(model=model, anchor_params=anchor_params)
  File "keras_retinanet/bin/../../keras_retinanet/models/retinanet.py", line 331, in retinanet_bbox
    anchors  = __build_anchors(anchor_params, features)
  File "keras_retinanet/bin/../../keras_retinanet/models/retinanet.py", line 232, in __build_anchors
    )(f) for i, f in enumerate(features)
  File "keras_retinanet/bin/../../keras_retinanet/models/retinanet.py", line 232, in <listcomp>
    )(f) for i, f in enumerate(features)
  File "/home/dany/anaconda3/envs/tensorflow_1.14/lib/python3.6/site-packages/keras/engine/base_layer.py", line 489, in __call__
    output = self.call(inputs, **kwargs)
  File "keras_retinanet/bin/../../keras_retinanet/layers/_misc.py", line 68, in call
    anchors = backend.shift(features_shape[1:3], self.stride, self.anchors)
  File "keras_retinanet/bin/../../keras_retinanet/backend/common.py", line 68, in shift
    shift_x = keras.backend.reshape(shift_x, [-1])
  File "/home/dany/anaconda3/envs/tensorflow_1.14/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2440, in reshape
    return tf.reshape(x, shape)
  File "/home/dany/anaconda3/envs/tensorflow_1.14/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 7715, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/home/dany/anaconda3/envs/tensorflow_1.14/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 530, in _apply_op_helper
    raise err
  File "/home/dany/anaconda3/envs/tensorflow_1.14/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 527, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/home/dany/anaconda3/envs/tensorflow_1.14/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1224, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/dany/anaconda3/envs/tensorflow_1.14/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 305, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/dany/anaconda3/envs/tensorflow_1.14/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 246, in constant
    allow_broadcast=True)
  File "/home/dany/anaconda3/envs/tensorflow_1.14/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 284, in _constant_impl
    allow_broadcast=allow_broadcast))
  File "/home/dany/anaconda3/envs/tensorflow_1.14/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 573, in make_tensor_proto
    append_fn(tensor_proto, proto_values)
  File "tensorflow/python/framework/fast_tensor_util.pyx", line 127, in tensorflow.python.framework.fast_tensor_util.AppendObjectArrayToTensorProto
  File "/home/dany/anaconda3/envs/tensorflow_1.14/lib/python3.6/site-packages/tensorflow/python/util/compat.py", line 65, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got <tf.Tensor 'anchors_0/mul:0' shape=(?,) dtype=float32>

**Comment by danamyu** [comment]
I reinstalled the repository, and my conda env with python3.6, tensorflow=1.14, the requirements.txt. After running the setup.py step, I tried again and now the model can start training.
