### ISSUE TITLE
I try backbone which is densenet121,but too many values to unpack (expected 3)

### ISSUE THREAD

**Issue by zhang92** [fizyr/keras-retinanet#377]
I try backbone which is densenet121,but after saving model to ./snapshots/densenet121_pascal_01.h5,ValueError: too many values to unpack (expected 3)

```
Epoch 00001: saving model to ./snapshots/densenet121_pascal_01.h5
Traceback (most recent call last):
  File "keras_retinanet/bin/train.py", line 426, in <module>
    main()
  File "keras_retinanet/bin/train.py", line 422, in main
    callbacks=callbacks,
  File "/home/zhangliyuan/anaconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/zhangliyuan/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 2213, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/zhangliyuan/anaconda3/lib/python3.6/site-packages/keras/callbacks.py", line 76, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "keras_retinanet/bin/../../keras_retinanet/callbacks/common.py", line 30, in on_epoch_end
    self.callback.on_epoch_end(epoch, logs=logs)
  File "keras_retinanet/bin/../../keras_retinanet/callbacks/eval.py", line 52, in on_epoch_end
    save_path=self.save_path
  File "keras_retinanet/bin/../../keras_retinanet/utils/eval.py", line 183, in evaluate
    all_detections     = _get_detections(generator, model, score_threshold=score_threshold, max_detections=max_detections, save_path=save_path)
  File "keras_retinanet/bin/../../keras_retinanet/utils/eval.py", line 81, in _get_detections
    _, _, detections = model.predict_on_batch(np.expand_dims(image, axis=0))
ValueError: too many values to unpack (expected 3)
```

**Comment by hgaiser** [comment]
It seems like your repository is out of date. That line in eval.py has changed recently. Could you try updating and see if it works?

**Comment by zhang92** [comment]
thank you very much. I try it.

**Comment by hgaiser** [comment]
I assume your issue is resolved.

**Comment by zhang92** [comment]
Yes, I forgot to tell you. The problem is solved. I really appreciate it.
