### ISSUE TITLE
train issue

### ISSUE THREAD

**Issue by LXWDL** [fizyr/keras-retinanet#387]
Hi,when I execute python3 keras_retinanet/bin/train.py pascal ./VOCdevkit2007/VOC2007 due to network speed problem, the model download does not come down, I will download the ResNet-50- The model.keras.h5 model is executed in the ./snapshots folder and is not used. The model file is still downloaded automatically. I specify --weights ./snapshots/ResNet-50-model.keras.h5 on the command line. error:
Train.py: error: unrecognized arguments: weights ResNet-50-model.keras.h5
How can I solve it? thanks.

**Comment by hgaiser** [comment]
I guess you specify weights at the end? They need to be specified before the dataset. So for instance:

`python3 keras_retinanet/bin/train.py --weights <weights> pascal ./VOCdevkit2007/VOC2007`

**Comment by hgaiser** [comment]
Did this fix your issue?

**Comment by LXWDL** [comment]
Sorry, recently busy with other things, did not respond in time, the problem has been solved, because of the problem of parameter order, thank you for your help.

**Comment by hgaiser** [comment]
Just passing `--random-transform` is sufficient.

**Comment by nosa999** [comment]
are you sure this work? I have a challenge with this that I think when I use random-transform it should increase the parameter of learning rather than when I don't use random-transform. but it didn't change. and it is 36569662 in both state.
![image](https://user-images.githubusercontent.com/40929193/51308026-6a091300-1a56-11e9-8446-0ee9c5059c4e.png)

**Comment by hgaiser** [comment]
Passing `--random-transform` won't change the network (and therefore the total params). It only modifies how the generator loads the images. Why do you think the number of parameters should change?

**Comment by nosa999** [comment]
and another question about validation. I want show the loss_val in end of every epoch but I do not know how to access it.
a parameter in args is --no-evaluation I want to know it is related to validation?

**Comment by nosa999** [comment]
![image](https://user-images.githubusercontent.com/40929193/51309342-662ac000-1a59-11e9-939c-68e7f77314bd.png)
basis on above picture I have to give address of validation-set and I have to give true to evaluation so this work but it isn't work in below picture
![image](https://user-images.githubusercontent.com/40929193/51309599-0c76c580-1a5a-11e9-82e5-be1334531539.png)

**Comment by nosa999** [comment]
> 
> 
> > I mean it should show the number of picture become more than before with data augmentation.
> 
> Not really, there is an unlimited amount of images you can generate with the default params. If we wanted to show the amount of images including data augmentation we should print `infinite`.

sorry about a lot of questions, how can I save the images that produce with data augmentation?

**Comment by nosa999** [comment]
> 
> 
> > > I mean it should show the number of picture become more than before with data augmentation.
> > 
> > 
> > Not really, there is an unlimited amount of images you can generate with the default params. If we wanted to show the amount of images including data augmentation we should print `infinite`.
> 
> sorry about a lot of questions, how can I save the images that produce with data augmentation?

because I think one thing should be exist that shows data augmentation works, for example the learning time in every epoch should increase

**Comment by aldiak** [comment]
Hi, when I run this command I am getting this error: (base) cyf@ubuntu:~/RetinanetTutorial/keras-retinanet$ keras_retinanet/bin/train.py --tensorboard-dir ~/RetinanetTutorial/TrainingOutput --snapshot-path ~/RetinanetTutorial/TrainingOutput/snapshots --steps 100 pascal ~/RetinanetTutorial/PlumsVOC

Using TensorFlow backend.
/home/cyf/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/cyf/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/cyf/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/cyf/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/cyf/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/cyf/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
2020-06-14 16:03:28.140328: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2020-06-14 16:03:28.145953: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3192670000 Hz
2020-06-14 16:03:28.146436: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55b659e8a8a0 executing computations on platform Host. Devices:
2020-06-14 16:03:28.146484: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2020-06-14 16:03:28.282631: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-06-14 16:03:28.283258: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55b659f49a90 executing computations on platform CUDA. Devices:
2020-06-14 16:03:28.283308: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce GTX 1070, Compute Capability 6.1
2020-06-14 16:03:28.283719: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.7845
pciBusID: 0000:01:00.0
totalMemory: 7.93GiB freeMemory: 7.38GiB
2020-06-14 16:03:28.283762: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2020-06-14 16:03:28.284816: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-06-14 16:03:28.284837: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2020-06-14 16:03:28.284843: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2020-06-14 16:03:28.285058: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7183 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "keras_retinanet/bin/train.py", line 426, in <module>
    main()
  File "keras_retinanet/bin/train.py", line 362, in main
    train_generator, validation_generator = create_generators(args)
  File "keras_retinanet/bin/train.py", line 196, in create_generators
    batch_size=args.batch_size
  File "keras_retinanet/bin/../../keras_retinanet/preprocessing/pascal_voc.py", line 64, in __init__
    self.image_names          = [l.strip().split(None, 1)[0] for l in open(os.path.join(data_dir, 'ImageSets', 'Main', set_name + '.txt')).readlines()]
FileNotFoundError: [Errno 2] No such file or directory: '/home/cyf/RetinanetTutorial/PlumsVOC/ImageSets/Main/test.txt'
(base) cyf@ubuntu:~/RetinanetTutorial/keras-retinanet$ keras_retinanet/bin/train.py --tensorboard-dir ~/RetinanetTutorial/TrainingOutput --snapshot-path ~/RetinanetTutorial/TrainingOutput/snapshots --steps 100 pascal ~/RetinanetTutorial/PlumsVOC
Using TensorFlow backend.
/home/cyf/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/cyf/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/cyf/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/cyf/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/cyf/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/cyf/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
2020-06-14 16:06:11.619951: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2020-06-14 16:06:11.625742: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3192670000 Hz
2020-06-14 16:06:11.626235: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55e72620f680 executing computations on platform Host. Devices:
2020-06-14 16:06:11.626298: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2020-06-14 16:06:11.767342: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-06-14 16:06:11.768000: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55e7262ce870 executing computations on platform CUDA. Devices:
2020-06-14 16:06:11.768050: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): GeForce GTX 1070, Compute Capability 6.1
2020-06-14 16:06:11.768525: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties: 
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.7845
pciBusID: 0000:01:00.0
totalMemory: 7.93GiB freeMemory: 7.38GiB
2020-06-14 16:06:11.768579: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2020-06-14 16:06:11.769437: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-06-14 16:06:11.769459: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0 
2020-06-14 16:06:11.769479: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N 
2020-06-14 16:06:11.769711: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7184 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "keras_retinanet/bin/train.py", line 426, in <module>
    main()
  File "keras_retinanet/bin/train.py", line 362, in main
    train_generator, validation_generator = create_generators(args)
  File "keras_retinanet/bin/train.py", line 196, in create_generators
    batch_size=args.batch_size
  File "keras_retinanet/bin/../../keras_retinanet/preprocessing/pascal_voc.py", line 64, in __init__
    self.image_names          = [l.strip().split(None, 1)[0] for l in open(os.path.join(data_dir, 'ImageSets', 'Main', set_name + '.txt')).readlines()]
FileNotFoundError: [Errno 2] No such file or directory: '/home/cyf/RetinanetTutorial/PlumsVOC/ImageSets/Main/test.txt'
