### ISSUE TITLE
Pretrained Model Loading error

### ISSUE THREAD

**Issue by Cpptz** [fizyr/keras-retinanet#394]
I get the following error while running your example ipython notebook with the pretrained model:

```
Traceback (most recent call last):
  File "/home/cpttz/Documents/INSA/4IF/smart/Affluatif-Interpreteur/keras-retinanet/examples/ResNet50RetinaNet.py", line 46, in <module>
    model = keras.models.load_model(model_path, custom_objects=custom_objects)
File "/home/cpttz/programmes/anaconda3/envs/faster/lib/python2.7/site-packages/keras/models.py", line 243, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
File "/home/cpttz/programmes/anaconda3/envs/faster/lib/python2.7/site-packages/keras/models.py", line 317, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
File "/home/cpttz/programmes/anaconda3/envs/faster/lib/python2.7/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
File "/home/cpttz/programmes/anaconda3/envs/faster/lib/python2.7/site-packages/keras/utils/generic_utils.py", line 144, in deserialize_keras_object
    list(custom_objects.items())))
File "/home/cpttz/programmes/anaconda3/envs/faster/lib/python2.7/site-packages/keras/engine/topology.py", line 2514, in from_config
    process_layer(layer_data)
File "/home/cpttz/programmes/anaconda3/envs/faster/lib/python2.7/site-packages/keras/engine/topology.py", line 2500, in process_layer
    custom_objects=custom_objects)
File "/home/cpttz/programmes/anaconda3/envs/faster/lib/python2.7/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
File "/home/cpttz/programmes/anaconda3/envs/faster/lib/python2.7/site-packages/keras/utils/generic_utils.py", line 138, in deserialize_keras_object
    ': ' + class_name)
ValueError: Unknown layer: NonMaximumSuppression
```

It seems NonMaximumSuppression is not defined in custom_object pass to load_model() while it is present in the h5 file.
Thanks in advance

**Comment by paghdv** [comment]
Same here, something is broken, nms was moved to it's own separate file but in the master branch it just disappeared

**Comment by hgaiser** [comment]
I need to upload an updated model, but it's at work.. in the meantime you can create a new model and call `model.load_weights(weights_path, by_name=True)`

**Comment by hgaiser** [comment]
Should be fixed now.

**Comment by a6225301** [comment]
Same error with that , any solution ?

**Comment by hgaiser** [comment]
Download the latest pretrained model.

**Comment by Checksum** [comment]
Get the same error while using bin/train.py to continue training using an existing snapshot. On master branch. Is there any way to fix this?
