### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'freeze'

### ISSUE THREAD

**Issue by zhang92** [fizyr/keras-retinanet#397]
python '/home/zhangliyuan/Desktop/keras-retinanet-master/keras_retinanet/bin/evaluate.py' pascal '/home/zhangliyuan/Desktop/keras-retinanet-master1/VOCdevkit/VOC2012' '/home/zhangliyuan/Desktop/keras-retinanet-master/snapshots/densenet121_pascal_260.h5' 

Traceback (most recent call last):
  File "/home/zhangliyuan/Desktop/keras-retinanet-master/keras_retinanet/bin/evaluate.py", line 140, in <module>
    main()
  File "/home/zhangliyuan/Desktop/keras-retinanet-master/keras_retinanet/bin/evaluate.py", line 119, in main
    model = keras.models.load_model(args.model, custom_objects=custom_objects)
  File "/home/zhangliyuan/anaconda3/lib/python3.6/site-packages/keras/models.py", line 243, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/home/zhangliyuan/anaconda3/lib/python3.6/site-packages/keras/models.py", line 317, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "/home/zhangliyuan/anaconda3/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/zhangliyuan/anaconda3/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 143, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/zhangliyuan/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 2507, in from_config
    process_layer(layer_data)
  File "/home/zhangliyuan/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 2493, in process_layer
    custom_objects=custom_objects)
  File "/home/zhangliyuan/anaconda3/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/zhangliyuan/anaconda3/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "/home/zhangliyuan/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 1269, in from_config
    return cls(**config)
TypeError: __init__() missing 1 required positional argument: 'freeze'

**Comment by rsingla92** [comment]
Can you please report what version of tensorflow and Keras you're running?

**Comment by zhang92** [comment]
tensorflow 1.4.1
keras 2.1.3

**Comment by zhang92** [comment]
tensorflow.__version__
'1.4.1'
>>> import keras
Using TensorFlow backend.
>>> keras.__version__
'2.1.3'

**Comment by zhang92** [comment]
Yes, I try it, it is resoved. Thank you very much.
