### ISSUE TITLE
Got error when trying to convert model to inference model

### ISSUE THREAD

**Issue by StandAloneComplex666** [fizyr/keras-retinanet#425]
```
/usr/local/lib/python2.7/dist-packages/Keras-2.1.6-py2.7.egg/keras/engine/saving.py:276: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/retinanet-convert-model", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python2.7/site-packages/keras_retinanet/bin/convert_model.py", line 51, in main
    model = models.load_model(args.model_in, convert=True, backbone=args.backbone, nms=args.nms)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/keras_retinanet/models/__init__.py", line 26, in load_model
    model = retinanet_bbox(model=model, nms=nms)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/keras_retinanet/models/retinanet.py", line 363, in retinanet_bbox
    detections = layers.FilterDetections(nms=nms, name='filtered_detections')([boxes, classification] + other)
  File "build/bdist.linux-x86_64/egg/keras/engine/base_layer.py", line 453, in __call__
  File "/home/ubuntu/.local/lib/python2.7/site-packages/keras_retinanet/layers/filter_detections.py", line 154, in call
    parallel_iterations=self.parallel_iterations
  File "/home/ubuntu/.local/lib/python2.7/site-packages/keras_retinanet/backend/tensorflow_backend.py", line 22, in map_fn
    return tensorflow.map_fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/functional_ops.py", line 389, in map_fn
    swap_memory=swap_memory)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2775, in while_loop
    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2604, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2554, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/functional_ops.py", line 379, in compute
    packed_fn_values = fn(packed_values)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/keras_retinanet/layers/filter_detections.py", line 146, in _filter_detections
    nms_threshold=self.nms_threshold,
  File "/home/ubuntu/.local/lib/python2.7/site-packages/keras_retinanet/layers/filter_detections.py", line 44, in filter_detections
    for c in range(int(classification.shape[1])):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_shape.py", line 505, in __getitem__
    return self._dims[key]
IndexError: list index out of range
```

**Comment by hgaiser** [comment]
What is it you did so far?

**Comment by hgaiser** [comment]
Closing due to inactivity.

**Comment by micoene** [comment]
Hi,

I'm having the same problem : 

```
    model = retinanet_bbox(model=model, nms=nms, class_specific_filter=class_specific_filter)
  File "C:\Source\SIDMCOE\keras-retinanet-master\keras_retinanet\bin\..\..\keras_retinanet\models\retinanet.py", line 356, in retinanet_bbox
    )([boxes, classification] + other)
  File "C:\Users\AMVision\AppData\Local\conda\conda\envs\retinanet\lib\site-packages\keras\engine\base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "C:\Source\SIDMCOE\keras-retinanet-master\keras_retinanet\bin\..\..\keras_retinanet\layers\filter_detections.py", line 179, in call
    parallel_iterations=self.parallel_iterations
  File "C:\Source\SIDMCOE\keras-retinanet-master\keras_retinanet\bin\..\..\keras_retinanet\backend\tensorflow_backend.py", line 23, in map_fn
    return tensorflow.map_fn(*args, **kwargs)
  File "C:\Users\AMVision\AppData\Local\conda\conda\envs\retinanet\lib\site-packages\tensorflow\python\ops\functional_ops.py", line 423, in map_fn
    swap_memory=swap_memory)
  File "C:\Users\AMVision\AppData\Local\conda\conda\envs\retinanet\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 3224, in while_loop
    result = loop_context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "C:\Users\AMVision\AppData\Local\conda\conda\envs\retinanet\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2956, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "C:\Users\AMVision\AppData\Local\conda\conda\envs\retinanet\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2893, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "C:\Users\AMVision\AppData\Local\conda\conda\envs\retinanet\lib\site-packages\tensorflow\python\ops\functional_ops.py", line 413, in compute
    packed_fn_values = fn(packed_values)
  File "C:\Source\SIDMCOE\keras-retinanet-master\keras_retinanet\bin\..\..\keras_retinanet\layers\filter_detections.py", line 171, in _filter_detections
    nms_threshold         = self.nms_threshold,
  File "C:\Source\SIDMCOE\keras-retinanet-master\keras_retinanet\bin\..\..\keras_retinanet\layers\filter_detections.py", line 74, in filter_detections
    for c in range(int(classification.shape[1])):
  File "C:\Users\AMVision\AppData\Local\conda\conda\envs\retinanet\lib\site-packages\tensorflow\python\framework\tensor_shape.py", line 612, in __getitem__
    return self._dims[key]
IndexError: list index out of range
```
The model works fine when i try to load it without the convert=True
