### ISSUE TITLE
A model based on a 3-class custom dataset is trained but convert_model fails

### ISSUE THREAD

**Issue by shirishr** [fizyr/keras-retinanet#441]
Hello,
I have a dataset with 3 classes. I have trained a model using reset50-retinanet on it.
In snapshots have a saved resnet50_blood3_20.h5
I want to convert this to a inference model
When I run 
keras_retinanet/bin/convert_model.py snapshots/resnet50_blood3_20.h5 snapshots/inference_ready_blood3_20.h5
I get an error:
ValueError: Unknown layer: NonMaximumSuppression

Full trace as below:

Using TensorFlow backend.
Traceback (most recent call last):
  File "keras_retinanet/bin/convert_model.py", line 58, in <module>
    main()
  File "keras_retinanet/bin/convert_model.py", line 51, in main
    model = models.load_model(args.model_in, convert=True, backbone_name=args.backbone, nms=args.nms)
  File "keras_retinanet/bin/../../keras_retinanet/models/__init__.py", line 76, in load_model
    model = keras.models.load_model(filepath, custom_objects=backbone(backbone_name).custom_objects)
  File "/home/sam/anaconda3/envs/py36/lib/python3.6/site-packages/keras/models.py", line 243, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/home/sam/anaconda3/envs/py36/lib/python3.6/site-packages/keras/models.py", line 317, in model_from_config
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "/home/sam/anaconda3/envs/py36/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/sam/anaconda3/envs/py36/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 144, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/sam/anaconda3/envs/py36/lib/python3.6/site-packages/keras/engine/topology.py", line 2514, in from_config
    process_layer(layer_data)
  File "/home/sam/anaconda3/envs/py36/lib/python3.6/site-packages/keras/engine/topology.py", line 2500, in process_layer
    custom_objects=custom_objects)
  File "/home/sam/anaconda3/envs/py36/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/home/sam/anaconda3/envs/py36/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 138, in deserialize_keras_object
    ': ' + class_name)
ValueError: Unknown layer: NonMaximumSuppression

**Comment by shirishr** [comment]
Update,
I had installed keras_retinanet some time back.
Looks like the code has changed since then...so the model was based on old code.
Closing this now

**Comment by shirishr** [comment]
More updates:

Repeated training of the model with 3 classes for 1 epoch.
The trained model (resnet50_blood3_01.h5) is 436.9 MB large
ran
keras_retinanet/bin/convert_model.py snapshots/resnet50_blood3_01.h5 snapshots/inference_blood3_01.h5

Interestingly 

inference_blood3_01.h5 is only 146.3 MB large

using a mod of the notebook 
https://github.com/fizyr/keras-retinanet/blob/master/examples/ResNet50RetinaNet.ipynb

I was able to predict for an image as well

**Comment by de-vri-es** [comment]
Thanks for the update :)

**Comment by safetykinetics** [comment]
I have the same problem--trained on old code, but trying to use the latest code for inference.  Is there a way to convert an old snapshot to be compatible with the latest?  pip freeze on training code is: 
Keras==2.1.5
keras-resnet==0.1.0
keras-retinanet==0.0.1
tensorflow-gpu==1.4.0
