### ISSUE TITLE
training image with 4 channel

### ISSUE THREAD

**Issue by HuangBo-Terraloupe** [fizyr/keras-retinanet#465]
I add one additional channel of optical flow for the image, try to get better performance.
I save the 4 channel image as a '.npy' file.
I modify the input of resnet, and in the csv generator, instead of reading image, I change to load a npy file.

But I got error these error:
```
WARNING:tensorflow:From /home/ga58zak/.local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
Epoch 1/50
Traceback (most recent call last):
  File "/home/ga58zak/pull_requist/keras-retinanet-optical-flow/keras_retinanet/bin/train.py", line 441, in <module>
    main()
  File "/home/ga58zak/pull_requist/keras-retinanet-optical-flow/keras_retinanet/bin/train.py", line 435, in main
    callbacks=callbacks,
  File "/home/ga58zak/.local/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/ga58zak/.local/lib/python2.7/site-packages/keras/engine/training.py", line 2145, in fit_generator
    generator_output = next(output_generator)
  File "/home/ga58zak/.local/lib/python2.7/site-packages/keras/utils/data_utils.py", line 770, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "/home/ga58zak/.local/lib/python2.7/site-packages/keras/utils/data_utils.py", line 635, in _data_generator_task
    generator_output = next(self._generator)
  File "/home/ga58zak/pull_requist/keras-retinanet-optical-flow/keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py", line 246, in next
    return self.compute_input_output(group)
  File "/home/ga58zak/pull_requist/keras-retinanet-optical-flow/keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py", line 224, in compute_input_output
    image_group, annotations_group = self.preprocess_group(image_group, annotations_group)
  File "/home/ga58zak/pull_requist/keras-retinanet-optical-flow/keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py", line 152, in preprocess_group
    image, annotations = self.preprocess_group_entry(image, annotations)
  File "/home/ga58zak/pull_requist/keras-retinanet-optical-flow/keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py", line 139, in preprocess_group_entry
    image, annotations = self.random_transform_group_entry(image, annotations)
  File "/home/ga58zak/pull_requist/keras-retinanet-optical-flow/keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py", line 119, in random_transform_group_entry
    image     = apply_transform(transform, image, self.transform_parameters)
  File "/home/ga58zak/pull_requist/keras-retinanet-optical-flow/keras_retinanet/bin/../../keras_retinanet/utils/image.py", line 155, in apply_transform
    borderValue = params.cval,
TypeError: src data type = 23 is not supported
```

Please give me some directions how to train 4 channel images.

**Comment by hgaiser** [comment]
I would guess that the `apply_transform` function does not expect 4 class images as inputs. You could try disabling random transformations.

It should be possible to train retinanet on any dimensional input, but we don't currently support that, nor do we have plans to. I'm going to close this issue, if you wish to discuss this further, my advise is to join the Slack channel.

**Comment by HuangBo-Terraloupe** [comment]
Hello Hans,

Can you please explain me how the apply_transform do? In the training
setup, there is a option --random-transform, are they same thing? Can you
set --random-transform as False to disable the function?

**Comment by Shiro-LK** [comment]
it is strange, that's work for me. I just create a custom csv function and change the input of the resnet. When you load the weight of your network, did you have a similar message to that ? UserWarning: Skipping loading of weights for layer conv1 due to mismatch in shape ((7, 7, 4, 64) vs (64, 3, 7, 7)).

**Comment by kimtaehyeong** [comment]
I currently want to learn with 5 channels, but I want to know how to make a custom generator.
