### ISSUE TITLE
 raise StopIteration(e) StopIteration

### ISSUE THREAD

**Issue by zccoder** [fizyr/keras-retinanet#47]
The problem occur like that:
```
None
Epoch 1/50
Traceback (most recent call last):
  File "examples/train_pascal.py", line 105, in <module>
    keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.1, patience=10, verbose=1, mode='auto', epsilon=0.0001, cooldown=0, min_lr=0),
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 2046, in fit_generator
    generator_output = next(output_generator)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 518, in get
    raise StopIteration(e)
StopIteration

```
It seems that fit_generator has problem. More detailedly, it may be "PascalVocIterator" problem.
I do not know whether it is the version or the code problem?

**Comment by hgaiser** [comment]
Is there no other error beyond this? Usually it also shows where in the generator the error occurred.

**Comment by dasolyn** [comment]
I have a similar issue, too.

```
Traceback (most recent call last):
  File "train_pascal.py", line 109, in <module>
    keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.1, patience=10, verbose=1, mode='auto', epsilon=0.0001, cooldown=0, min_lr=0),
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 2046, in fit_generator
    generator_output = next(output_generator)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 518, in get
    raise StopIteration(e)
StopIteration: 'NoneType' object has no attribute 'text'
```

I edited some code in train_pascal.py because I want to use my own dataset. But I didn't edit pascal_voc.py

**Comment by dasolyn** [comment]
I made a xml annotations file myself so it doesn't contain `difficult`, `truncated` tags.
I added it and now it works well.

**Comment by zccoder** [comment]
@hgaiser 
I find the reason. It is just the version of tensorflow. At first, I use tensorflow-gpu 1.0.0, and then I upgrade it to 1.4.0. It is good.
@de-vri-es I think it will be better to reference the version of this project.

**Comment by de-vri-es** [comment]
@zccoder: If you mean you think that keras-retinanet should check the version of tensorflow, that seems to go against the principle of being back-end agnostic by using keras.

The examples now do check the keras version since #59. Did you have something else in mind?

**Comment by hgaiser** [comment]
This issue is addressed in PR https://github.com/fizyr/keras-retinanet/pull/48.
