### ISSUE TITLE
IOError: Unable to create file

### ISSUE THREAD

**Issue by yanducky** [fizyr/keras-retinanet#53]
I modify file 'pascal_voc.py' and 'train_pascal.py' and trian my model.But I got the following error:

Epoch 1/50
 999/1000 [============================>.] - ETA: 0s - loss: 1.4074 - regression_loss: 0.3482 - classification_loss: 1.0593Epoch 00001: val_loss improved from inf to 1.04777, saving model to snapshots/resnet50_voc_best.h5
Traceback (most recent call last):
  File "train_pascal.py", line 106, in <module>
    keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.1, patience=10, verbose=1, mode='auto', epsilon=0.0001, cooldown=0, min_lr=0),
  File "/home/wanghan/miniconda2/envs/tensorflow/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/wanghan/miniconda2/envs/tensorflow/lib/python2.7/site-packages/keras/engine/training.py", line 2117, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/wanghan/miniconda2/envs/tensorflow/lib/python2.7/site-packages/keras/callbacks.py", line 73, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/wanghan/miniconda2/envs/tensorflow/lib/python2.7/site-packages/keras/callbacks.py", line 414, in on_epoch_end
    self.model.save(filepath, overwrite=True)
  File "/home/wanghan/miniconda2/envs/tensorflow/lib/python2.7/site-packages/keras/engine/topology.py", line 2556, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "/home/wanghan/miniconda2/envs/tensorflow/lib/python2.7/site-packages/keras/models.py", line 102, in save_model
    with h5py.File(filepath, mode='w') as f:
  File "/home/wanghan/miniconda2/envs/tensorflow/lib/python2.7/site-packages/h5py/_hl/files.py", line 271, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/wanghan/miniconda2/envs/tensorflow/lib/python2.7/site-packages/h5py/_hl/files.py", line 107, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1490028130695/work/h5py/_objects.c:2846)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/h5py_1490028130695/work/h5py/_objects.c:2804)
  File "h5py/h5f.pyx", line 98, in h5py.h5f.create (/home/ilan/minonda/conda-bld/h5py_1490028130695/work/h5py/h5f.c:2290)
IOError: Unable to create file (Unable to open file: name = 'snapshots/resnet50_voc_best.h5', errno = 2, error message = 'no such file or directory', flags = 13, o_flags = 242)

but i don't understand what cause the problem.
can anyone help me?thank you.

**Comment by de-vri-es** [comment]
The script is attempting to save snapshots to the `snapshots` folder, which does not seem to exist on your system.

Make sure to create a snapshots folder or modify the location of the snapshots if you don't run the script from the repository root.

**Comment by de-vri-es** [comment]
@yanducky: Can you confirm if creating a `snapshots` folder solves your issue?

**Comment by hgaiser** [comment]
Presumably this is fixed then. Closing.
