### ISSUE TITLE
debug.py fails to display annotations with csv data.

### ISSUE THREAD

**Issue by AlliedToasters** [fizyr/keras-retinanet#542]
Hello,

I love this package! I'd like to see if my annotations are assigning to anchors, but the debug script gives me this error message:

```
-> % python debug.py --annotations csv train.csv class_mapping.csv
/home/my_acct/miniconda3/envs/dev1/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "debug.py", line 215, in <module>
    main()
  File "debug.py", line 211, in main
    run(generator, args)
  File "debug.py", line 186, in run
    labels, boxes, _ = generator.compute_anchor_targets(image.shape, annotations, generator.num_classes())
  File "/home/alliedtoasters/projects/keras-retinanet/keras_retinanet/utils/anchors.py", line 47, in anchor_targets_bbox
    anchor_states = np.zeros((anchors.shape[0],))
AttributeError: 'tuple' object has no attribute 'shape'

```

I've tried looking for the root of the issue; I get a tuple with values (800, 800, 15) or something like that where the function expects a numpy array. Any ideas?

**Comment by hgaiser** [comment]
Thank you for reporting the issue, there was indeed a bug in debug.py (ironically :)).

Fixed with https://github.com/fizyr/keras-retinanet/commit/7a6b874a526126db8a6b449a637b67de2a87b507
