### ISSUE TITLE
Debug.py throwing error

### ISSUE THREAD

**Issue by sumeetssaurav** [fizyr/keras-retinanet#560]
I am trying to debug the ANNOATIOANS USING 
python keras_retinanet/bin/debug.py csv ./CARPK/data/annotations.csv ./CARPK/data/class.csv 
However, it is throwing the below error
Traceback (most recent call last):
  File "keras_retinanet/bin/debug.py", line 221, in <module>
    main()
  File "keras_retinanet/bin/debug.py", line 217, in main
    run(generator, args)
  File "keras_retinanet/bin/debug.py", line 192, in run
    labels, boxes, _ = generator.compute_anchor_targets(image.shape, annotations, generator.num_classes())
  File "keras_retinanet/bin/../../keras_retinanet/utils/anchors.py", line 47, in anchor_targets_bbox
    anchor_states = np.zeros((anchors.shape[0],))
AttributeError: 'tuple' object has no attribute 'shape'

**Comment by yhenon** [comment]
duplicate of #542, are you on the latest commit?

**Comment by hgaiser** [comment]
Indeed, should be fixed with https://github.com/fizyr/keras-retinanet/commit/7a6b874a526126db8a6b449a637b67de2a87b507
If it is not fixed, feel free to reopen this issue.
