### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by KwanjaiPSU** [fizyr/keras-retinanet#567]
Epoch 1/50
Traceback (most recent call last):
  File "keras_retinanet/bin/train.py", line 483, in <module>
    main()
  File "keras_retinanet/bin/train.py", line 478, in main
    callbacks=callbacks,
  File "/root/miniconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.6/site-packages/keras/engine/training.py", line 2194, in fit_generator
    generator_output = next(output_generator)
  File "/root/miniconda3/lib/python3.6/site-packages/keras/utils/data_utils.py", line 793, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "/root/miniconda3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/root/miniconda3/lib/python3.6/site-packages/keras/utils/data_utils.py", line 658, in _data_generator_task
    generator_output = next(self._generator)
  File "keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py", line 287, in __next__
    return self.next()
  File "keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py", line 295, in next
    group = self.groups[self.group_index]
IndexError: list index out of range

**Comment by hgaiser** [comment]
That's a strange error, it can never be out of range there. Did you change anything in the code? Are you sure your CSV (assuming you're using CSV) contains data?

**Comment by KwanjaiPSU** [comment]
I’m change dataset, I use widerface dataset. and then I convert file txt to json. I manage widerface dataset seems like MSCOCO dataset.

**Comment by hgaiser** [comment]
You could try printing `len(train_generator.groups)` to see if you have images in your generator.

**Comment by KwanjaiPSU** [comment]
okay I'll try.

**Comment by KwanjaiKJ** [comment]
@hgaiser excuse me...  len(train_generator.groups) put in what file??

**Comment by KwanjaiKJ** [comment]
I put in on train.py and I'm try train model. 
"Error"
Traceback (most recent call last):
  File "keras_retinanet/bin/train.py", line 483, in <module>
    main()
  File "keras_retinanet/bin/train.py", line 478, in main
    callbacks=callbacks,
  File "/root/miniconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.6/site-packages/keras/engine/training.py", line 2194, in fit_generator
    generator_output = next(output_generator)
  File "/root/miniconda3/lib/python3.6/site-packages/keras/utils/data_utils.py", line 793, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "/root/miniconda3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/root/miniconda3/lib/python3.6/site-packages/keras/utils/data_utils.py", line 658, in _data_generator_task
    generator_output = next(self._generator)
TypeError: 'int' object is not an iterator

**Comment by KwanjaiKJ** [comment]
# start training
    training_model.fit_generator(
        generator=len(train_generator.groups),
        steps_per_epoch=args.steps,
        epochs=args.epochs,
        verbose=1,
        callbacks=callbacks,
    ) @hgaiser

**Comment by hgaiser** [comment]
> @hgaiser excuse me... len(train_generator.groups) put in what file??

Put `print(len(train_generator.groups))` [here](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/bin/train.py#L421).

**Comment by KwanjaiKJ** [comment]
thanks a lot @hgaiser

**Comment by hgaiser** [comment]
Did you find the issue ?

**Comment by chrishengbee** [comment]
Hi, @hgaiser I have encontered similar situation.

**Comment by chrishengbee** [comment]
I am using oid v4 dataset, my file tree is like this
2018_04
-train/    #images and csv files inside
-validation/
-test/
-bbox_labels_600_hierarchy.json
-class-descriptions-boxable.csv

I type /keras_retinanet/bin/train.py oid ../../../input/google-ai-open-images-object-detection-track/, and then get exactly same error as KwanjaiKJ.
Any ideas? Thank you!

**Comment by hgaiser** [comment]
Most likely you've converted a model to an inference model twice.

**Comment by chrishengbee** [comment]
I figured it out.
I am too stupid to put /image under /2018_04 ...

**Comment by rizwanriaz-se** [comment]
> I figured it out. I am too stupid to put /image under /2018_04 ...

@chrishengbee 
I am getting the same error as well, and have followed this article .. https://medium.com/@van.evanfebrianto/how-to-train-custom-object-detection-models-using-retinanet-aeed72f5d701 .. How do you have different directory structure working ? I am using this command to train: !python keras_retinanet/bin/train.py --imagenet-weights --epoch 7 --batch-size 1 --steps 7816 --snapshot-path snapshots/ --tensorboard-dir tensorboard/ pascal dataset/ .. My dataset contains 7816 images in total. 7493 for training and 323 for testing .. The only difference from above error is I am getting None instead of Epoch numbers..
