### ISSUE TITLE
Change Anchor Boxes Aspect Ratio

### ISSUE THREAD

**Issue by ahkarami** [fizyr/keras-retinanet#596]
Dear @hgaiser,
Thank you for your nice work.
If one wants to change the `aspect ratios` of anchor boxes for example to 0.7, which parts of the _training code_ and _inference code_ must be changed? 
I think for _training_ this part [1](https://github.com/fizyr/keras-retinanet/blob/6ccf6bf3d03a1b5ea1d59fa8dac8dfcb3545a11b/keras_retinanet/models/retinanet.py#L179) must be changed, but I don't know for test/inference time which part must be changed? 

Would you please explain how one can change the aspect ratios of anchor boxes?

**Comment by hgaiser** [comment]
Hey,

Indeed it needs to be changed in two locations, but it's more accurate to call them the generator (or input) and the model. The model expects the anchors to be a certain way and the generator needs to generate it in that way.

You've already found the model side, the generator side can be changed [here](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/preprocessing/generator.py#L238).

Granted this is a far from ideal way to adjust the anchor scales and ratios, then again we've never really properly exposed these parameters. The hope is that we find a good way to handle configurations and then we can move exactly these  kind of stuff in there. For now, good luck!

If this solves your issue, feel free to close it.

**Comment by ahkarami** [comment]
@hgaiser 
Thank you for your time & response.

**Comment by JudyMRSD** [comment]
Hello, thank you for creating this great project!  I'm trying to train for different aspect ratios. I changed in anchors.py https://github.com/fizyr/keras-retinanet/blob/9f6ee78a67d27e5d6d9055c2a0da3803e03b290b/keras_retinanet/utils/anchors.py#L210
as 
```
   ratios = np.array([5.5, 2, 1, 0.5, 0.18])
    scales = np.array([0.8, 1, 1.2])
    sizes = np.array([32, 64, 128, 256, 512]) # default size: [32, 64, 128, 256, 512]
    image_shapes = shapes_callback(image_shape, pyramid_levels)
```

and changed https://github.com/fizyr/keras-retinanet/blob/6ccf6bf3d03a1b5ea1d59fa8dac8dfcb3545a11b/keras_retinanet/models/retinanet.py#L179
as 
```
AnchorParameters.default = AnchorParameters(
    sizes   = [32, 64, 128, 256, 512],
    strides = [8, 16, 32, 64, 128],
    ratios  = np.array([5.5, 2, 1, 0.5, 0.18], keras.backend.floatx()),
    scales  = np.array([0.8, 1, 1.2], keras.backend.floatx()),
)
```

Is there other things I need to change? I have a dataset of two classes of very different aspect ratois, so 3 anchor ratios need to be changed to  5 ratios. Thanks a lot for helping! 

When I run train.py,  I got an errorr indicating shape mismatch. 
```
no early stopping
Epoch 1/100
29/30 [============================>.] - ETA: 5s - loss: 7.4080 - regression_loss: 4.1776 - classification_loss: 3.2304 Traceback (most recent call last):
  File "/home/jinz1/anaconda/envs/keras_retinanet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/home/jinz1/anaconda/envs/keras_retinanet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/home/jinz1/anaconda/envs/keras_retinanet/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [1,1115973] vs. [1,1859955]
	 [[Node: boxes/mul_9 = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](boxes/Exp_1, boxes/sub_1)]]
	 [[Node: filtered_detections/map/while/Where/_2145 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2379_filtered_detections/map/while/Where", tensor_type=DT_INT64, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopfiltered_detections/map/while/strided_slice_8/stack/_2097)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 297, in <module>
    main()
  File "train.py", line 291, in main
    callbacks=callbacks,
  File "/home/jinz1/anaconda/envs/keras_retinanet/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/jinz1/anaconda/envs/keras_retinanet/lib/python3.6/site-packages/keras/engine/training.py", line 2213, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/jinz1/anaconda/envs/keras_retinanet/lib/python3.6/site-packages/keras/callbacks.py", line 76, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/jinz1/Jin/Intersection_TrafficFlow/detection_refactor/code/detection_anchor/keras_retinanet/callbacks/common.py", line 30, in on_epoch_end
    self.callback.on_epoch_end(epoch, logs=logs)
  File "/home/jinz1/Jin/Intersection_TrafficFlow/detection_refactor/code/detection_anchor/keras_retinanet/callbacks/eval.py", line 52, in on_epoch_end
    save_path=self.save_path
  File "/home/jinz1/Jin/Intersection_TrafficFlow/detection_refactor/code/detection_anchor/keras_retinanet/utils/eval.py", line 164, in evaluate
    all_detections     = _get_detections(generator, model, score_threshold=score_threshold, max_detections=max_detections, save_path=save_path)
  File "/home/jinz1/Jin/Intersection_TrafficFlow/detection_refactor/code/detection_anchor/keras_retinanet/utils/eval.py", line 84, in _get_detections
    boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))
  File "/home/jinz1/anaconda/envs/keras_retinanet/lib/python3.6/site-packages/keras/engine/training.py", line 1912, in predict_on_batch
    outputs = self.predict_function(ins)
  File "/home/jinz1/anaconda/envs/keras_retinanet/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2475, in __call__
    **self.session_kwargs)
  File "/home/jinz1/anaconda/envs/keras_retinanet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/jinz1/anaconda/envs/keras_retinanet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/jinz1/anaconda/envs/keras_retinanet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/jinz1/anaconda/envs/keras_retinanet/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [1,1115973] vs. [1,1859955]
	 [[Node: boxes/mul_9 = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](boxes/Exp_1, boxes/sub_1)]]
	 [[Node: filtered_detections/map/while/Where/_2145 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2379_filtered_detections/map/while/Where", tensor_type=DT_INT64, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopfiltered_detections/map/while/strided_slice_8/stack/_2097)]]

Caused by op 'boxes/mul_9', defined at:
  File "train.py", line 297, in <module>
    main()
  File "train.py", line 269, in main
    freeze_backbone=Freeze_Backbone
  File "train.py", line 121, in create_models
    prediction_model = retinanet_bbox(model=model)
  File "/home/jinz1/Jin/Intersection_TrafficFlow/detection_refactor/code/detection_anchor/keras_retinanet/models/retinanet.py", line 356, in retinanet_bbox
    boxes = layers.RegressBoxes(name='boxes')([anchors, regression])
  File "/home/jinz1/anaconda/envs/keras_retinanet/lib/python3.6/site-packages/keras/engine/topology.py", line 617, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/jinz1/Jin/Intersection_TrafficFlow/detection_refactor/code/detection_anchor/keras_retinanet/layers/_misc.py", line 111, in call
    return backend.bbox_transform_inv(anchors, regression, mean=self.mean, std=self.std)
  File "/home/jinz1/Jin/Intersection_TrafficFlow/detection_refactor/code/detection_anchor/keras_retinanet/backend/common.py", line 42, in bbox_transform_inv
    pred_h     = keras.backend.exp(dh) * heights
  File "/home/jinz1/anaconda/envs/keras_retinanet/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 894, in binary_op_wrapper
    return func(x, y, name=name)
  File "/home/jinz1/anaconda/envs/keras_retinanet/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 1117, in _mul_dispatch
    return gen_math_ops._mul(x, y, name=name)
  File "/home/jinz1/anaconda/envs/keras_retinanet/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 2726, in _mul
    "Mul", x=x, y=y, name=name)
  File "/home/jinz1/anaconda/envs/keras_retinanet/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/jinz1/anaconda/envs/keras_retinanet/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/jinz1/anaconda/envs/keras_retinanet/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Incompatible shapes: [1,1115973] vs. [1,1859955]
	 [[Node: boxes/mul_9 = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](boxes/Exp_1, boxes/sub_1)]]
	 [[Node: filtered_detections/map/while/Where/_2145 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2379_filtered_detections/map/while/Where", tensor_type=DT_INT64, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopfiltered_detections/map/while/strided_slice_8/stack/_2097)]]


```

**Comment by dusk039** [comment]
If you're changing the number of either ratios or sizes, you need to also change the number of anchors expected [here](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/models/retinanet.py#L271) 
At least that's what worked for me.

**Comment by JudyMRSD** [comment]
Hello, I have another question for training with 2 classes with different anchor shapes. Class A converged quickly and have score close to 0.95, but class B didn't converge and still have score as 0. Looks like it's ignoring class B during training. I visualized the bbox that participated in training using debug.py, and both classes showed up properly. Could this be a result of imbalance of classes? Number of class A : class B is around 30:1. Do you think there is something that I need to modify in the code? Thanks!
