### ISSUE TITLE
StopIteration: points is not a numpy array, neither a scalar

### ISSUE THREAD

**Issue by aminshabani** [fizyr/keras-retinanet#61]
Hi,

I am getting the following error on train_pascal:

![screenshot from 2017-11-15 19-17-34](https://user-images.githubusercontent.com/8512924/32830814-c044f734-ca39-11e7-82cb-44067bcda503.png)

I tested it on my dataset as well, but I got a same error, any idea?

Edited: Sorry, it was my mistake. I found the solution in the previous issues.

**Comment by aminshabani** [comment]
Hi again, I am using conda and I installed `opencv-python` as it is written in [this](https://github.com/fizyr/keras-retinanet/issues/43) issue,  but I didn't remove my previous opencv. 
Now, I am getting the following error, is it possible that it is because of an opencv conflict?!

Epoch 1/20
Traceback (most recent call last):
  File "examples/train_wider.py", line 110, in <module>
    keras.callbacks.ReduceLROnPlateau(monitor='loss', factor=0.1, patience=2, verbose=1, mode='auto', epsilon=0.0001, cooldown=0, min_lr=0),
  File "/home/amin/anaconda2/envs/tf/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/amin/anaconda2/envs/tf/lib/python2.7/site-packages/keras/engine/training.py", line 2114, in fit_generator
    class_weight=class_weight)
  File "/home/amin/anaconda2/envs/tf/lib/python2.7/site-packages/keras/engine/training.py", line 1826, in train_on_batch
    check_batch_axis=True)
  File "/home/amin/anaconda2/envs/tf/lib/python2.7/site-packages/keras/engine/training.py", line 1411, in _standardize_user_data
    exception_prefix='target')
  File "/home/amin/anaconda2/envs/tf/lib/python2.7/site-packages/keras/engine/training.py", line 153, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking target: expected regression to have shape (None, None, 4) but got array with shape (1, 105993, 5)

**Comment by hgaiser** [comment]
I've seen this error yesterday too .. seems to be caused by Keras 2.1.0. For now, install Keras 2.0.9 to fix this issue.

**Comment by hgaiser** [comment]
For reference, this is what caused it : https://github.com/fchollet/keras/pull/8056#pullrequestreview-76745344

**Comment by aminshabani** [comment]
Yesss, thank you so much.
I installed the 2.0.9 version by `conda install -c conda-forge keras` and it works.
