### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by summer-bunny** [fizyr/keras-retinanet#613]
When I use the mobilenet model, it's a problem：
Traceback (most recent call last):
  File "/home/neu/zly/keras-retinanet-master/keras_retinanet/bin/train.py", line 472, in <module>
    main()
  File "/home/neu/zly/keras-retinanet-master/keras_retinanet/bin/train.py", line 432, in main
    weights = backbone.download_imagenet()
  File "/home/neu/zly/keras-retinanet-master/keras_retinanet/bin/../../keras_retinanet/models/mobilenet.py", line 52, in download_imagenet
    alpha = float(self.backbone.split('_')[1])
IndexError: list index out of range

thank you！！！！

**Comment by hgaiser** [comment]
Please follow the issue template:

Please make sure that you follow the steps below when creating an issue.
Only use GitHub issues for issues with the implementation, not for issues with specific datasets or general questions about functionality.
If your issue is an implementation question, please ask your question on the #keras-retinanet Slack channel instead of filing a GitHub issue.
You can find directions for the Slack channel here: https://github.com/fizyr/keras-retinanet#discussions

Thank you!

1. Check that you are up-to-date with the master branch of keras-retinanet.
2. Check that you are up-to-date with the latest version of Keras: https://github.com/keras-team/keras.
3. Check that you are up-to-date with the latest version of TensorFlow.
   The installation instructions can be found here: https://www.tensorflow.org/get_started/os_setup.
4. Check that you have read the entire README.md: https://github.com/fizyr/keras-retinanet/README.md.
   Most noticably the FAQ section shows common issues: https://github.com/fizyr/keras-retinanet#faq.
5. Clearly describe the issues you're having including the expected behaviour, the actual behaviour
   and the steps required to trigger the issue.
6. Include relevant output from the commands you're executing, including full stack traces where relevant.
7. Remove this entire message and replace it with your issue.

**Comment by hgaiser** [comment]
Closing due to inactivity. If it is still relevant, feel free to reopen, but please provide more information (such as the steps and commands you executed).
