### ISSUE TITLE
'numpy.float64' object is not iterable

### ISSUE THREAD

**Issue by cuongnc220592** [fizyr/keras-retinanet#636]
I have a problem when I run evaluate.py.
How to solve this error.
Thank for your support

python keras_retinanet/bin/evaluate.py csv validation_non_aug.txt classes.txt vgg16.h5 --backbone=vgg16
```
Loading model, this may take a second...
/home/cuongnc/anaconda2/lib/python2.7/site-packages/keras/models.py:255: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
Traceback (most recent call last):
  File "keras_retinanet/bin/evaluate.py", line 166, in <module>
    main()
  File "keras_retinanet/bin/evaluate.py", line 156, in main
    for label, (average_precision, num_annotations) in average_precisions.items():
TypeError: 'numpy.float64' object is not iterable
```

**Comment by hgaiser** [comment]
(Line 156](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/bin/evaluate.py#L156) is different on `master`. Could you try updating and see if the error still occurs?

**Comment by hgaiser** [comment]
Closing due to inactivity (and assuming updating of the code fixes the issue).
