### ISSUE TITLE
[question] does retinanet support different anchor ratios?

### ISSUE THREAD

**Issue by chrjxj** [fizyr/keras-retinanet#644]
when I try to modify anchor ratios,  `keras_retinanet/models/retinanet.py:172`:

```
AnchorParameters.default = AnchorParameters(
    sizes   = [32, 64, 128, 256, 512],
    strides = [8, 16, 32, 64, 128],
    ratios  = np.array([0.1, 0.2, 0.5, 1, 2, 5, 10], keras.backend.floatx()),
    scales  = np.array([2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)], keras.backend.floatx()),
)
```

the training seems fine but on the 1st epoch end, the training pipeline raised the following errors. any insights? thanks a lot. 

```
None
Epoch 1/50
500/500 [==============================] - 1595s 3s/step - loss: 2.7686 - regression_loss: 1.4671 - classification_loss: 1.3015
Traceback (most recent call last):
  File "keras_retinanet/bin/train.py", line 441, in <module>
    main()
  File "keras_retinanet/bin/train.py", line 437, in main
    callbacks=callbacks,
  File "/home/jin/pyenv/tf2/local/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/jin/pyenv/tf2/local/lib/python2.7/site-packages/keras/engine/training.py", line 2280, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/jin/pyenv/tf2/local/lib/python2.7/site-packages/keras/callbacks.py", line 77, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "keras_retinanet/bin/../../keras_retinanet/callbacks/common.py", line 30, in on_epoch_end
    self.callback.on_epoch_end(epoch, logs=logs)
  File "keras_retinanet/bin/../../keras_retinanet/callbacks/eval.py", line 54, in on_epoch_end
    save_path=self.save_path
  File "keras_retinanet/bin/../../keras_retinanet/utils/eval.py", line 163, in evaluate
    all_detections     = _get_detections(generator, model, score_threshold=score_threshold, max_detections=max_detections, save_path=save_path)
  File "keras_retinanet/bin/../../keras_retinanet/utils/eval.py", line 81, in _get_detections
    boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))
  File "/home/jin/pyenv/tf2/local/lib/python2.7/site-packages/keras/engine/training.py", line 1952, in predict_on_batch
    outputs = self.predict_function(ins)
  File "/home/jin/pyenv/tf2/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2475, in __call__
    **self.session_kwargs)
  File "/home/jin/pyenv/tf2/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/jin/pyenv/tf2/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/jin/pyenv/tf2/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/jin/pyenv/tf2/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [1,156231] vs. [1,260385]
         [[Node: boxes/mul_7 = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](boxes/add_6, boxes/sub_1)]]
         [[Node: filtered_detections/map/while/Identity/_2451 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2935_filtered_detections/map/while/Identity", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopfiltered_detections/map/while/strided_slice_58/stack/_2259)]]
 
Caused by op u'boxes/mul_7', defined at:
  File "keras_retinanet/bin/train.py", line 441, in <module>
    main()
  File "keras_retinanet/bin/train.py", line 409, in main
    freeze_backbone=args.freeze_backbone
  File "keras_retinanet/bin/train.py", line 90, in create_models
    prediction_model = retinanet_bbox(model=model)
  File "keras_retinanet/bin/../../keras_retinanet/models/retinanet.py", line 344, in retinanet_bbox
    boxes = layers.RegressBoxes(name='boxes')([anchors, regression])
  File "/home/jin/pyenv/tf2/local/lib/python2.7/site-packages/keras/engine/topology.py", line 617, in __call__
    output = self.call(inputs, **kwargs)
  File "keras_retinanet/bin/../../keras_retinanet/layers/_misc.py", line 111, in call
    return backend.bbox_transform_inv(anchors, regression, mean=self.mean, std=self.std)
  File "keras_retinanet/bin/../../keras_retinanet/backend/common.py", line 35, in bbox_transform_inv
    y2 = boxes[:, :, 3] + (deltas[:, :, 3] * std[3] + mean[3]) * height
  File "/home/jin/pyenv/tf2/local/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 894, in binary_op_wrapper
    return func(x, y, name=name)
  File "/home/jin/pyenv/tf2/local/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 1117, in _mul_dispatch
    return gen_math_ops._mul(x, y, name=name)
  File "/home/jin/pyenv/tf2/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 2726, in _mul
    "Mul", x=x, y=y, name=name)
  File "/home/jin/pyenv/tf2/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/jin/pyenv/tf2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/jin/pyenv/tf2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
 
InvalidArgumentError (see above for traceback): Incompatible shapes: [1,156231] vs. [1,260385]
         [[Node: boxes/mul_7 = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](boxes/add_6, boxes/sub_1)]]
         [[Node: filtered_detections/map/while/Identity/_2451 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2935_filtered_detections/map/while/Identity", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopfiltered_detections/map/while/strided_slice_58/stack/_2259)]]
 
```

**Comment by chrjxj** [comment]
figured this out. multiple [0.2, 1, 2] places are hard coded. need to update them all to make things work.
