### ISSUE TITLE
Expected regression have unexpected shape

### ISSUE THREAD

**Issue by y-vasilyev** [fizyr/keras-retinanet#66]
Hi all,

I'm trying to train network on my own data and got that error, could anybody help me with this issue?

`Epoch 1/50
Traceback (most recent call last):
  File "examples/train_pascal.py", line 109, in <module>
    keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.1, patience=10, verbose=1, mode='auto', epsilon=0.0001, cooldown=0, min_lr=0),
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\keras\engine\training.py", line 2114, in fit_generator
    class_weight=class_weight)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\keras\engine\training.py", line 1826, in train_on_batch
    check_batch_axis=True)
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\keras\engine\training.py", line 1411, in _standardize_user_data
    exception_prefix='target')
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\keras\engine\training.py", line 153, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking target: expected regression to have shape (None, None, 4) but got array with shape (1, 110520, 5)`

Thank you for support :)

**Comment by hgaiser** [comment]
Check [here](https://github.com/fchollet/keras/pull/8514). Until that, or something similar gets merged, use keras 2.0.9.

**Comment by y-vasilyev** [comment]
Thank you very much! All works like a charm! :)
