### ISSUE TITLE
Traceback error using Tensorflow as backend

### ISSUE THREAD

**Issue by shrybht** [fizyr/keras-retinanet#666]
I ran the latest version of tensorflow and Keras, then I faced the following errors:

Using TensorFlow backend.
Traceback (most recent call last):
  File ". . ./keras/keras_retinanet/bin/convert_model.py", line 14, in <module>
    model = load_model(model_path, backbone_name='resnet50')
  File ". . ./keras/keras_retinanet/bin\..\..\keras_retinanet\models\__init__.py", line 83, in load_model
    model = keras.models.load_model(filepath, custom_objects=backbone(backbone_name).custom_objects)
  File ". . .\keras\engine\saving.py", line 249, in load_model
    f = h5py.File(filepath, mode='r')
  File "C:\Python\Python36\lib\site-packages\h5py\_hl\files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "C:\Python\Python36\lib\site-packages\h5py\_hl\files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '. . ./keras/keras_retinanet/models\snapshots\resnet50_coco_best_v2.1.0.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

Process finished with exit code 1

I have replaced the 'model_path' and 'filepath' with the actual location of the model
Could you please help me fix this?

**Comment by hgaiser** [comment]
I see you're running on Windows, maybe it is mixing up different slashes, based on your error? I also see three points in the path, why?

**Comment by shrybht** [comment]
"C:\Users\abc\PycharmProjects\keras\keras_retinanet\bin\train.py"

**Comment by hgaiser** [comment]
I'm closing this issue as the error appears to be on your system, not in the codebase. If you feel otherwise, feel free to reopen.
