### ISSUE TITLE
Some error when predicting the result

### ISSUE THREAD

**Issue by Wang-zipeng** [fizyr/keras-retinanet#675]
I have change the anchores for detecting the small object in the picture, and my changing is 
AnchorParameters.default = AnchorParameters(
    sizes   = [32, 64, 128, 256, 512],
    strides = [8, 16, 32, 64, 128],
    ratios  = np.array([..., 0.5, 1, 2], keras.backend.floatx()),
    scales  = np.array([..., 2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)], keras.backend.floatx()),
)
in the  retinanet.py , "..." is something like "0.1, 0.2, ...".
There is no error during train and convert.
But I got this error when i use the model to predict the result.
Traceback (most recent call last):
  File "H:/keras-retinanet/keras_retinanet/bin/predict.py", line 77, in <module>
    predict()
  File "H:/keras-retinanet/keras_retinanet/bin/predict.py", line 55, in predict
    boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))
  File "C:\Anaconda3\lib\site-packages\keras\engine\training.py", line 1272, in predict_on_batch
    outputs = self.predict_function(ins)
  File "C:\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 2666, in __call__
    return self._call(inputs)
  File "C:\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 2636, in _call
    fetched = self._callable_fn(*array_vals)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1382, in __call__
    run_metadata_ptr)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [1,184995] vs. [1,575540]
	 [[Node: boxes/mul_3 = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](boxes/mul_2, boxes/sub_1)]]
         [[Node: filtered_detections/map/while/embedding_lookup_4/_1879 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2028_filtered_detections/map/while/embedding_lookup_4", tensor_type=DT_INT64, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopfiltered_detections/map/while/non_max_suppression/NonMaxSuppressionV3/max_output_size/_1817)]]

There is no error when i used the default archor parameter.

My predict code is:
def predict():
    # set the modified tf session as backend in keras
    keras.backend.tensorflow_backend.set_session(get_session())

    model_path = os.path.join('.', 'snapshots', 'predict_2.h5')

    # load retinanet model
    model = models.load_model(model_path, backbone_name='resnet50')

    # if the model is not converted to an inference model, use the line below
    # see: https://github.com/fizyr/keras-retinanet#converting-a-training-model-to-inference-model
    #model = models.load_model(model_path, backbone_name='resnet50')

    #print(model.summary())

    image = read_image_bgr("./1.jpg")

    # copy to draw on
    draw = image.copy()
    draw = cv2.cvtColor(draw, cv2.COLOR_BGR2RGB)

    # preprocess image for network
    image = preprocess_image(image)
    image, scale = resize_image(image, min_side=562, max_side=864)

    # process image
    boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))

    # correct for image scale
    boxes /= scale

    # visualize detections
    for box, score, label in zip(boxes[0], scores[0], labels[0]):
        # scores are sorted so we can break
        """
        if score < 0.1:
            break
        """

        color = label_color(label)

        b = box.astype(int)
        draw_box(draw, b, color=color)

    cv2.imwrite('result.jpg', draw)

My tensorflow version is tensorflow-gpu 1.10.1
If you @hgaiser know something, please help me, thank you.

**Comment by Wang-zipeng** [comment]
I have solved this problem for changing retinanet.py "retinanet" function's num_anchors from 9 to AnchorParameters.default.num_anchors().
