### ISSUE TITLE
Got "ImportError: DLL load failed" when import keras_retinanet.utils.image before matplotlib.pyplot

### ISSUE THREAD

**Issue by KittyLiou** [fizyr/keras-retinanet#679]
After I installed keras-retinanet, I tried to run retinanet\examples\ResNet50RetinaNet.ipynb. I didn't use jupyter notebook so I copied all the code to another .py file, say test.py.
My problem is that when I run the test.py I got the import error.
The full error message is shown as below:

> E:\Kitty\Code\keras-retinanet\examples>python test.py
C:\Users\RL\Anaconda3\envs\tensorflow-gpu\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future,
it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    import matplotlib.pyplot as plt
  File "C:\Users\RL\Anaconda3\envs\tensorflow-gpu\lib\site-packages\matplotlib\pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "C:\Users\RL\Anaconda3\envs\tensorflow-gpu\lib\site-packages\matplotlib\backends\__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "C:\Users\RL\Anaconda3\envs\tensorflow-gpu\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 15, in <module>
    from .backend_qt5 import (
  File "C:\Users\RL\Anaconda3\envs\tensorflow-gpu\lib\site-packages\matplotlib\backends\backend_qt5.py", line 19, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "C:\Users\RL\Anaconda3\envs\tensorflow-gpu\lib\site-packages\matplotlib\backends\qt_editor\figureoptions.py", line 20, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "C:\Users\RL\Anaconda3\envs\tensorflow-gpu\lib\site-packages\matplotlib\backends\qt_editor\formlayout.py", line 54, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "C:\Users\RL\Anaconda3\envs\tensorflow-gpu\lib\site-packages\matplotlib\backends\qt_compat.py", line 140, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: DLL load failed: The specified module could not be found.

However, after I rearrange the import order by placing `import matplotlib.pyplot as plt` before `from keras_retinanet.utils.image import read_image_bgr, preprocess_image, resize_image` the program worked just well.
Though my problem is solved, I still wonder what causes this different behavior.
Can anyone explain?

Thanks in advance.

**Comment by vcarpani** [comment]
We never tested this on windows, however it seems like you are missing some Qt libraries. It is usually solvable by adding the folder containing Qt's applications and DLLs to your PATH environment variable.

**Comment by hgaiser** [comment]
I don't quite understand why reordering the imports would change anything, do you have a suggestion @KittyLiou ?
