### ISSUE TITLE
ValueError on train_pascal.py

### ISSUE THREAD

**Issue by Shawnjx** [fizyr/keras-retinanet#69]
I tried to train the retinanet on a Pascal dataset. And I got a ValueError like this:
Epoch 1/50
Traceback (most recent call last):
  File "train_pascal.py", line 114, in <module>
    keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.1, patience=10, verbose=1, mode='auto', epsilon=0.0001, cooldown=0, min_lr=0),
  File "/home/Conda/.local/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/Conda/.local/lib/python3.6/site-packages/keras/engine/training.py", line 2114, in fit_generator
    class_weight=class_weight)
  File "/home/Conda/.local/lib/python3.6/site-packages/keras/engine/training.py", line 1826, in train_on_batch
    check_batch_axis=True)
  File "/home/Conda/.local/lib/python3.6/site-packages/keras/engine/training.py", line 1411, in _standardize_user_data
    exception_prefix='target')
  File "/home/Conda/.local/lib/python3.6/site-packages/keras/engine/training.py", line 153, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking target: expected regression to have shape (None, None, 4) but got array with shape (1, 67995, 5)

**Comment by de-vri-es** [comment]
This is a regression in keras 2.1.0, see also #66. For now you can use keras 2.0.9.

**Comment by Shawnjx** [comment]
Thank you very much :)
