### ISSUE TITLE
Shape mismatch while training with csv-file and Full-HD images on GPU

### ISSUE THREAD

**Issue by TimoK93** [fizyr/keras-retinanet#691]
Hi folks,

For training i'm using a NVIDIA GTX 1050ti.

Days ago i trained a net on the KITTI Dataset as explained in your README. It worked fine! The GPU was used correctly and the training was completed successful after ~4 days. 

I just tried to train a little net with a (very small) dataset. I just wanted to verify my implementation and train the net later with a bigger dataset. The dataset contains only 3-channel FHD (1920x1080) images and there is only one class existing.

If i'm trying to run the train.py script on my custom dataset as explained in the README, after some training steps an Error is thrown...
Some shapes seems to do not match. 

**Do you if there could be some problems using FHD files for training?**

**The full output of the script (interesting lines are at the end):**

Using TensorFlow backend.
2018-09-20 15:54:00.472865: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-09-20 15:54:00.564925: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:897] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-09-20 15:54:00.565500: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1405] Found device 0 with properties:
name: GeForce GTX 1050 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.392
pciBusID: 0000:01:00.0
totalMemory: 3.94GiB freeMemory: 3.18GiB
2018-09-20 15:54:00.565514: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1484] Adding visible gpu devices: 0
2018-09-20 15:54:00.780607: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-09-20 15:54:00.780637: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971]      0
2018-09-20 15:54:00.780642: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] 0:   N
2018-09-20 15:54:00.780812: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1097] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2892 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
Creating model, this may take a second...`

... (HERE WAS MODEL SUMMARY)...

Total params: 36,382,957
Trainable params: 36,276,717
Non-trainable params: 106,240
__________________________________________________________________________________________________
None
/home/corvitac/.local/lib/python3.5/site-packages/keras/callbacks.py:999: UserWarning: `epsilon` argument is deprecated and will be removed, use `min_delta` instead.
  warnings.warn('`epsilon` argument is deprecated and '
Epoch 1/50
2018-09-20 15:54:20.549729: W tensorflow/core/common_runtime/bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.08GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2018-09-20 15:54:20.905545: W tensorflow/core/common_runtime/bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.07GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2018-09-20 15:54:20.995272: W tensorflow/core/common_runtime/bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 548.38MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2018-09-20 15:54:21.008238: W tensorflow/core/common_runtime/bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.07GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2018-09-20 15:54:21.146913: W tensorflow/core/common_runtime/bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 276.30MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2018-09-20 15:54:21.146948: W tensorflow/core/common_runtime/bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.12GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2018-09-20 15:54:21.211922: W tensorflow/core/common_runtime/bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 305.57MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2018-09-20 15:54:21.245165: W tensorflow/core/common_runtime/bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 325.38MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2018-09-20 15:54:21.257691: W tensorflow/core/common_runtime/bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 147.05MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2018-09-20 15:54:21.261745: W tensorflow/core/common_runtime/bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.17GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
    1/10000 [..............................] - ETA: 19:22:10 - loss: 3.8591 - regression_loss: 2.7305 - classification_loss: 1.12862018-09-20 15:54:23.045962: E tensorflow/stream_executor/cuda/cuda_dnn.cc:81]
2018-09-20 15:54:23.046060: I tensorflow/stream_executor/stream.cc:4818] stream 0x5151d50 did not memzero GPU location; source: 0x7fbfedffdec0
2018-09-20 15:54:23.046060: I tensorflow/stream_executor/stream.cc:4818] stream 0x5151d50 did not memzero GPU location; source: 0x7fbff4b46ec0
2018-09-20 15:54:23.046249: I tensorflow/stream_executor/stream.cc:4818] stream 0x5151d50 did not memzero GPU location; source: 0x7fbff4b46ec0
2018-09-20 15:54:23.046262: I tensorflow/stream_executor/stream.cc:4818] stream 0x5151d50 did not memzero GPU location; source: 0x7fbfedffdec0
2018-09-20 15:54:23.046428: I tensorflow/stream_executor/stream.cc:4818] stream 0x5151d50 did not memzero GPU location; source: 0x7fbfedffdec0
2018-09-20 15:54:23.046463: I tensorflow/stream_executor/stream.cc:4818] stream 0x5151d50 did not memzero GPU location; source: 0x7fbff4b46ec0
2018-09-20 15:54:23.046579: I tensorflow/stream_executor/stream.cc:4818] stream 0x5151d50 did not memzero GPU location; source: 0x7fbfedffdec0
2018-09-20 15:54:23.046667: I tensorflow/stream_executor/stream.cc:4818] stream 0x5151d50 did not memzero GPU location; source: 0x7fbff4b46ec0
2018-09-20 15:54:23.046710: I tensorflow/stream_executor/stream.cc:4818] stream 0x5151d50 did not memzero GPU location; source: 0x7fbfedffdec0
2018-09-20 15:54:23.046846: I tensorflow/stream_executor/stream.cc:4818] stream 0x5151d50 did not memzero GPU location; source: 0x7fbff4b46ec0
2018-09-20 15:54:23.046891: I tensorflow/stream_executor/stream.cc:4818] stream 0x5151d50 did not memzero GPU location; source: 0x7fbfedffdec0
2018-09-20 15:54:23.046993: I tensorflow/stream_executor/stream.cc:4818] stream 0x5151d50 did not memzero GPU location; source: 0x7fbff4b46ec0
Traceback (most recent call last):
  File "keras_retinanet/bin/train.py", line 480, in <module>
    main()
  File "keras_retinanet/bin/train.py", line 473, in main
    callbacks=callbacks,
  File "/home/corvitac/.local/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/corvitac/.local/lib/python3.5/site-packages/keras/engine/training.py", line 1415, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/corvitac/.local/lib/python3.5/site-packages/keras/engine/training_generator.py", line 213, in fit_generator
    class_weight=class_weight)
  File "/home/corvitac/.local/lib/python3.5/site-packages/keras/engine/training.py", line 1215, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/corvitac/.local/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2666, in __call__
    return self._call(inputs)
  File "/home/corvitac/.local/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2636, in _call
    fetched = self._callable_fn(*array_vals)
  File "/home/corvitac/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1382, in __call__
    run_metadata_ptr)
  File "/home/corvitac/.local/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InternalError: cuDNN Backward Filter function launch failure : input shape([1,256,94,167]) filter shape([3,3,256,9])
     [[Node: training/Adam/gradients/classification_submodel/pyramid_classification/convolution_grad/Conv2DBackpropFilter = Conv2DBackpropFilter[T=DT_FLOAT, _class=["loc:@training/Adam/cond_87/Switch_2"], data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](classification_submodel/pyramid_classification_3/Relu, ConstantFolding/training/Adam/gradients/classification_submodel/pyramid_classification/convolution_grad/ShapeN-matshapes-1, training/Adam/gradients/classification_submodel/pyramid_classification/convolution_grad/Conv2DBackpropInput-2-TransposeNHWCToNCHW-LayoutOptimizer)]]

**Comment by TimoK93** [comment]
Oh sorry guys,
I "fixed" the issue...

My colleague was working that day with the GPU on the system to advance performance for some OpenCV scripts. She used some CUDA libraries below 9.x and maybe there were some interferences. I don't know why but the issue is not happening after rebooting the system and banning my colleague from the system :)

Thanks for reading this issue anyhow! 
I will close the issue.

Greetings,
Timo Kaiser

**Comment by de-vri-es** [comment]
He may simply have used some GPU memory that you needed. Either way, thanks for reporting back :)
