### ISSUE TITLE
A couple of things with train_csv.py

### ISSUE THREAD

**Issue by alexiskattan** [fizyr/keras-retinanet#71]
Hi love the package!  I'm trying to work through a few things with `train_csv.py`.

The first issue is that there seems to be a syntax error on line 114:

`validation_steps=test_generator.size() // args.batch_size if test_generator else: 0,`

The second thing is that this line `from keras_retinanet.models import ResNet50RetinaNet` is throwing an error.

I'm kinda new with this but if you give me some pointers I can try and help!.  Anywho really look forward to trying it out with the CSV files! Thanks again!!!

**Comment by hgaiser** [comment]
Thanks, fixed the incorrect imports and syntax errors. The CSV generator is relatively new so be aware that there may be bugs ;) That being said, I'd love to hear them so we can fix it, good luck :p 

ps. if the latest commit fixes your problem, feel free to close this issue

**Comment by alexiskattan** [comment]
Thank you for the fast response! It is definitely getting closer and almost there.

I'm getting this error now:
`Traceback (most recent call last):
  File "examples/train_csv.py", line 72, in <module>
    batch_size=args.batch_size
  File "C:\Users\me\AppData\Roaming\Python\Python35\site-packages\keras_retinanet-0.0.1-py3.5.egg\keras_retinanet\preprocessing\csv_generator.py", line 43, in __init__
_csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)`

For reference here is what the other files look like

`classes.csv`:
`class_name,0`

`annotations.csv`:
`C:\Users\me\images\0.png,40,40,60,60,class_name
C:\Users\me\images\1.png,40,40,60,60,class_name
C:\Users\me\images\2.png,40,40,60,60,class_name`

**Comment by hgaiser** [comment]
Can you try again? I Just committed a new fix.

**Comment by alexiskattan** [comment]
Thanks again!  The CSV portion works now! That is good.  Now I'm getting the same issue that I got when I used the pascal data set.  There seems to be a shape issue happening.

`Epoch 1/20
Traceback (most recent call last):
  File "examples/train_csv.py", line 117, in <module>
    keras.callbacks.ReduceLROnPlateau(monitor='loss', factor=0.1, patience=2, verbose=1, mode='auto', epsilon=0.0001, cooldown=0, min_lr=0),
  File "C:\Users\me\AppData\Roaming\Python\Python35\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\me\AppData\Roaming\Python\Python35\site-packages\keras\engine\training.py", line 2114, in fit_generator
    class_weight=class_weight)
  File "C:\Users\me\AppData\Roaming\Python\Python35\site-packages\keras\engine\training.py", line 1826, in train_on_batch
    check_batch_axis=True)
  File "C:\Users\me\AppData\Roaming\Python\Python35\site-packages\keras\engine\training.py", line 1411, in _standardize_user_data
    exception_prefix='target')
  File "C:\Users\me\AppData\Roaming\Python\Python35\site-packages\keras\engine\training.py", line 153, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking target: expected regression to have shape (None, None, 4) but got array with shape (1, 67995, 5)`

**Comment by hgaiser** [comment]
Yeah that's an annoying bug in latest keras. Try keras version 2.0.9.

**Comment by mkocabas** [comment]
@alexiskattan If you don't want to downgrade, you can get rid of the mismatch error by installing Keras from git source. The issue was solved by @hgaiser's latest PR.

**Comment by alexiskattan** [comment]
@hgaiser using 2.0.9 worked!
@mkocabas using 2.1.1 worked!
