### ISSUE TITLE
keras_resnet has no attribute custom_objects

### ISSUE THREAD

**Issue by alexhtn** [fizyr/keras-retinanet#73]
Traceback (most recent call last):
  File "examples/train_coco.py", line 27, in <module>
    from keras_retinanet.models.resnet import ResNet50RetinaNet
  File "/home/akh/.local/lib/python3.5/site-packages/keras_retinanet/models/resnet.py", line 25, in <module>
    custom_objects.update(keras_resnet.custom_objects)
AttributeError: module 'keras_resnet' has no attribute 'custom_objects'

I'm using keras version 2.0.9 and keras-resnet version 0.0.8.

**Comment by de-vri-es** [comment]
As the installation instructions note, you need the latest master branch from keras-resnet. `custom_objects` is a recent addition.
