### ISSUE TITLE
Error of Annotations should contain bboxes

### ISSUE THREAD

**Issue by tongluoiupui** [fizyr/keras-retinanet#734]
Could you meet this strange error?  when I installed retinanet before, I didn't meet this error, after I reinstall today and run training, 
'cd ~/isic/keras-retinanet && CUDA_VISIBLE_DEVICES=3 keras_retinanet/bin/train.py --backbone resnet50 --epochs 5 --steps 100  csv /path/to/train_pg.csv  /path/to/cls.csv'

I checked the training data files and I didn't modify preprocessing/generator.py and utils/anchors.py

Error:

Epoch 1/5
keras_retinanet/bin/../../keras_retinanet/utils/anchors.py:83: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  assert('bboxes' in annotations), "Annotations should contain bboxes."
Traceback (most recent call last):
  File "keras_retinanet/bin/train.py", line 476, in <module>
    main()
  File "keras_retinanet/bin/train.py", line 471, in main
    callbacks=callbacks,
  File "/home/tong/isic/local/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/tong/isic/local/lib/python2.7/site-packages/keras/engine/training.py", line 1415, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/tong/isic/local/lib/python2.7/site-packages/keras/engine/training_generator.py", line 177, in fit_generator
    generator_output = next(output_generator)
  File "/home/tong/isic/local/lib/python2.7/site-packages/keras/utils/data_utils.py", line 793, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "/home/tong/isic/local/lib/python2.7/site-packages/keras/utils/data_utils.py", line 658, in _data_generator_task
    generator_output = next(self._generator)
  File "keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py", line 295, in next
    return self.compute_input_output(group)
  File "keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py", line 279, in compute_input_output
    targets = self.compute_targets(image_group, annotations_group)
  File "keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py", line 254, in compute_targets
    self.num_classes()
  File "keras_retinanet/bin/../../keras_retinanet/utils/anchors.py", line 83, in anchor_targets_bbox
    assert('bboxes' in annotations), "Annotations should contain bboxes."
AssertionError: Annotations should contain bboxes.

**Comment by tongluoiupui** [comment]
I reinstall again and again, now running the train.py, get this error which is never meet before.
I remember when fresh installation, always have  some image dicom to jpg format or box float to int conversion problem, so I usually modified some lines image.py or read_image_bgr().  But today's error is first happen:

Using TensorFlow backend.
Traceback (most recent call last):
  File "keras_retinanet/bin/train.py", line 35, in <module>
    from .. import layers  # noqa: F401
  File "keras_retinanet/bin/../../keras_retinanet/layers/__init__.py", line 1, in <module>
    from ._misc import RegressBoxes, UpsampleLike, Anchors, ClipBoxes  # noqa: F401
  File "keras_retinanet/bin/../../keras_retinanet/layers/_misc.py", line 19, in <module>
    from ..utils import anchors as utils_anchors
  File "keras_retinanet/bin/../../keras_retinanet/utils/anchors.py", line 20, in <module>
    from ..utils.compute_overlap import compute_overlap
ImportError: No module named compute_overlap

**Comment by hgaiser** [comment]
For the first error: I'm guessing you're using your own generator? We changed the way it returns annotations, it's a dictionary now instead of one numpy blob. Check one of the existing generators to see how to modify it.

For the second error: check the FAQ ;)

**Comment by tongluoiupui** [comment]
Thanks! 
 the second is my fault( didn't setup)
