### ISSUE TITLE
[Support] Running retinanet-train on GPU

### ISSUE THREAD

**Issue by flightofthunder** [fizyr/keras-retinanet#735]
Hi, I appologize because I know this has been asked before, but I would like some clarification.

I have the following command:
`retinanet-train --gpu=... csv training.csv classes.csv`

I got the gpu ID by running `nvidia-smi.exe --list-gpus`, but since I have just one GPU, this shouldn't be necessary if I'm not mistaken.

I have properly installed the necessary modules according to the installation guide and the executable runs perfectly fine, except I get an ETA of 100+ hours for some 75 training images (and this was just to test, I need to train with 300). I have a GTX1070, and using `nvidia-smi.exe`, there is no process running on my GPU when I run `retinanet-train`.

I noticed in [this issue](https://github.com/fizyr/keras-retinanet/issues/138) that it would be done automatically if I use tensorflow-gpu as a backend. I didn't have this installed and when I did install it (`python -m pip install tensorflow-gpu`), the above `retinanet-train` command gave me a bunch of errors. So what exactly am I to do to get this to run on my GPU?

I'm running this on a Windows 7 PC.

Thanks

**Comment by hgaiser** [comment]
What were the errors you get when you run with tensorflow-gpu? You'd really need a gpu enabled tensorflow to run tensorflow with gpu ;p

I believe the recommendation is to not install tensorflow via pip, since it doesn't know what system it will run on it will run suboptimally. You could try compiling tensorflow from source.

**Comment by flightofthunder** [comment]
```Using TensorFlow backend.
Traceback (most recent call last):
  File "F:\Apps\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "F:\Apps\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "F:\Apps\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "F:\Apps\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "F:\Apps\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Apps\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "F:\Apps\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Phil\AppData\Roaming\Python\Python36\Scripts\retinanet-train.exe\__main__.py", line 5, in <module>
  File "C:\Users\Phil\AppData\Roaming\Python\Python36\site-packages\keras_retinanet\bin\train.py", line 24, in <module>
    import keras
  File "C:\Users\Phil\AppData\Roaming\Python\Python36\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\Users\Phil\AppData\Roaming\Python\Python36\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "C:\Users\Phil\AppData\Roaming\Python\Python36\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "C:\Users\Phil\AppData\Roaming\Python\Python36\site-packages\keras\backend\__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "C:\Users\Phil\AppData\Roaming\Python\Python36\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "F:\Apps\Python36\lib\site-packages\tensorflow\__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "F:\Apps\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "F:\Apps\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "F:\Apps\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "F:\Apps\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "F:\Apps\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "F:\Apps\Python36\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "F:\Apps\Python36\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.```

Thanks for the quick reply. Seems to be a Tensorflow problem, but this only happens once I try installing tensorflow-gpu...

**Comment by hgaiser** [comment]
This seems like an issue with tensorflow, so I'll close it. Perhaps try your question on one of the tensorflow boards?

**Comment by flightofthunder** [comment]
In case anyone else stumbles upon this thread, it was indeed a Tensorflow issue.

I got it to work by installing CUDA v9.0, cuDNN v7.3 (for CUDA9.0) and reinstalling tensorflow-gpu... More or less according to the Tensorflow doc: https://www.tensorflow.org/install/pip

Just so I don't screw anything up, do I need both `tensforflow` and `tensorflow-gpu` installed?
