### ISSUE TITLE
Annotation file parse error?

### ISSUE THREAD

**Issue by peacherwu** [fizyr/keras-retinanet#742]
As I am deploying the most recent Retinanet in a new machine (no GPU) to train oid models, I encounter this error (Everything Okay with the slightly older version of one month ago):
`Epoch 1/1
Traceback (most recent call last):
  File "keras_retinanet/bin/train.py", line 497, in <module>
    main()
  File "keras_retinanet/bin/train.py", line 492, in main
    callbacks=callbacks,
  File "/home/peacherwuengr/anaconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/peacherwuengr/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/peacherwuengr/anaconda3/lib/python3.6/site-packages/keras/engine/training_generator.py", line 181, in fit_generator
    generator_output = next(output_generator)
  File "/home/peacherwuengr/anaconda3/lib/python3.6/site-packages/keras/utils/data_utils.py", line 709, in get
    six.reraise(*sys.exc_info())
  File "/home/peacherwuengr/anaconda3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/peacherwuengr/anaconda3/lib/python3.6/site-packages/keras/utils/data_utils.py", line 685, in get
    inputs = self.queue.get(block=True).get()
  File "/home/peacherwuengr/anaconda3/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/home/peacherwuengr/anaconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/peacherwuengr/anaconda3/lib/python3.6/site-packages/keras/utils/data_utils.py", line 626, in next_sample
    return six.next(_SHARED_SEQUENCES[uid])
  File "keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py", line 305, in __next__
    return self.next()
  File "keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py", line 316, in next
    return self.compute_input_output(group)
  File "keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py", line 288, in compute_input_output
    annotations_group = self.load_annotations_group(group)
  File "keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py", line 137, in load_annotations_group
    annotations_group = [self.load_annotations(image_index) for image_index in group]
  File "keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py", line 137, in <listcomp>
    annotations_group = [self.load_annotations(image_index) for image_index in group]
  File "keras_retinanet/bin/../../keras_retinanet/preprocessing/open_images.py", line 373, in load_annotations
    annotations['labels'][idx, 4] = cls_id
IndexError: too many indices for array`

The command I ran is:
`keras_retinanet/bin/train.py --weights ~/.keras/models/resnet50_coco_best_v2.1.0.h5 --epochs 1 --steps 10 --batch-size 1 --freeze-backbone oid <dir> --parent-label=Clothing
`

Module versions:
`keras-resnet                       0.1.0    
keras-retinanet                    0.5.0
keras                               2.2.4`

**Comment by hgaiser** [comment]
You're right, that line should be `annotations['labels'][idd] = cls_id`.

Could you make a pull request to fix the issue ?
