### ISSUE TITLE
ValueError: Unknown layer: NonMaximumSuppression

### ISSUE THREAD

**Issue by MarouanGit** [fizyr/keras-retinanet#748]
Hi, 

I'm trying to run **keras_retinanet/bin/convert_model.py** and got the error below. I already checked #394  and updated my Keras and Tensorflow, but the error still remains. Any other ideas on how to solve this issue ?

**KERAS** : `keras.__version__ = 2.2.4`
**TF** : `tensorflow.__version == 1.4.1` 

```
Using TensorFlow backend.
2018-10-21 17:48:41.893564: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-10-21 17:48:41.896326: E tensorflow/stream_executor/cuda/cuda_driver.cc:406] failed call to cuInit: CUDA_ERROR_NO_DEVICE
2018-10-21 17:48:41.896367: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: mtaha-0567b503906f023bd
2018-10-21 17:48:41.896380: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: mtaha-0567b503906f023bd
2018-10-21 17:48:41.896410: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: 384.81.0
2018-10-21 17:48:41.896435: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:369] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  384.81  Sat Sep  2 02:43:11 PDT 2017
GCC version:  gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5)
"""
2018-10-21 17:48:41.896462: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 384.81.0
2018-10-21 17:48:41.896475: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:300] kernel version seems to match DSO: 384.81.0
Traceback (most recent call last):
  File "keras_retinanet/bin/convert_model.py", line 88, in <module>
    main()
  File "keras_retinanet/bin/convert_model.py", line 75, in main
    model = models.load_model(args.model_in, backbone_name=args.backbone)
  File "keras_retinanet/bin/../../keras_retinanet/models/__init__.py", line 83, in load_model
    return keras.models.load_model(filepath, custom_objects=backbone(backbone_name).custom_objects)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/network.py", line 1022, in from_config
    process_layer(layer_data)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/network.py", line 1008, in process_layer
    custom_objects=custom_objects)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/generic_utils.py", line 138, in deserialize_keras_object
    ': ' + class_name)
ValueError: Unknown layer: NonMaximumSuppression
```

**Comment by hgaiser** [comment]
I think your keras-retinanet reporistory is outdated, or you might have an outdated version of keras-retinanet installed (which it appears to be using when throwing the error). Try updating it or removing any installed versions (or update the installed version)

**Comment by MarouanGit** [comment]
I cloned and installed keras-retinanet from the last version avalaible : `keras-retinanet==0.5.0`. After the installations are done i have te message below as confirmation: 

`Successfully installed h5py-2.8.0 keras-2.2.4 keras-applications-1.0.6 keras-preprocessing-1.0.5 keras-resnet-0.1.0 numpy-1.15.3 pyyaml-3.13 scipy-1.1.0 six-1.11.0`

I also tried running the notebook but encountered the same error as before when loading the models : `model = models.load_model(model_path, backbone_name='resnet50')`

Below a detailed error message. 

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-41-0aac418d2c8b> in <module>()
      1 # First method
----> 2 model = models.load_model(model_path, backbone_name='resnet50')
      3 
      4 # Second method
      5 #model = model.load_weights(model_path, by_name=True)

/home/mtaha/keras-retinanet/keras_retinanet/models/__init__.pyc in load_model(filepath, backbone_name)
     81     """
     82     import keras.models
---> 83     return keras.models.load_model(filepath, custom_objects=backbone(backbone_name).custom_objects)
     84 
     85 

/usr/local/lib/python2.7/dist-packages/keras/engine/saving.pyc in load_model(filepath, custom_objects, compile)
    417     f = h5dict(filepath, 'r')
    418     try:
--> 419         model = _deserialize_model(f, custom_objects, compile)
    420     finally:
    421         if opened_new_file:

/usr/local/lib/python2.7/dist-packages/keras/engine/saving.pyc in _deserialize_model(f, custom_objects, compile)
    223         raise ValueError('No model found in config.')
    224     model_config = json.loads(model_config.decode('utf-8'))
--> 225     model = model_from_config(model_config, custom_objects=custom_objects)
    226     model_weights_group = f['model_weights']
    227 

/usr/local/lib/python2.7/dist-packages/keras/engine/saving.pyc in model_from_config(config, custom_objects)
    456                         '`Sequential.from_config(config)`?')
    457     from ..layers import deserialize
--> 458     return deserialize(config, custom_objects=custom_objects)
    459 
    460 

/usr/local/lib/python2.7/dist-packages/keras/layers/__init__.pyc in deserialize(config, custom_objects)
     53                                     module_objects=globs,
     54                                     custom_objects=custom_objects,
---> 55                                     printable_module_name='layer')

/usr/local/lib/python2.7/dist-packages/keras/utils/generic_utils.pyc in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    143                     config['config'],
    144                     custom_objects=dict(list(_GLOBAL_CUSTOM_OBJECTS.items()) +
--> 145                                         list(custom_objects.items())))
    146             with CustomObjectScope(custom_objects):
    147                 return cls.from_config(config['config'])

/usr/local/lib/python2.7/dist-packages/keras/engine/network.pyc in from_config(cls, config, custom_objects)
   1020         # First, we create all layers and enqueue nodes to be processed
   1021         for layer_data in config['layers']:
-> 1022             process_layer(layer_data)
   1023         # Then we process nodes in order of layer depth.
   1024         # Nodes that cannot yet be processed (if the inbound node

/usr/local/lib/python2.7/dist-packages/keras/engine/network.pyc in process_layer(layer_data)
   1006 
   1007             layer = deserialize_layer(layer_data,
-> 1008                                       custom_objects=custom_objects)
   1009             created_layers[layer_name] = layer
   1010 

/usr/local/lib/python2.7/dist-packages/keras/layers/__init__.pyc in deserialize(config, custom_objects)
     53                                     module_objects=globs,
     54                                     custom_objects=custom_objects,
---> 55                                     printable_module_name='layer')

/usr/local/lib/python2.7/dist-packages/keras/utils/generic_utils.pyc in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    136             if cls is None:
    137                 raise ValueError('Unknown ' + printable_module_name +
--> 138                                  ': ' + class_name)
    139         if hasattr(cls, 'from_config'):
    140             custom_objects = custom_objects or {}

ValueError: Unknown layer: NonMaximumSuppression
```

**Comment by hgaiser** [comment]
Apologies, I misinterpreted your error. I think your model is a bit old, could that be true? You can update the model like this (typed from the top of my head, might be some error):
```python
import keras_retinanet.models
model = keras_retinanet.models.backbone('resnet50').retinanet(number_of_classes)
model.load_weights("/path/to/old/model.h5", by_name=True)
model.save("/path/to/updated/model.h5")
```

The `NonMaximumSuppression` layer got merged into the `FilterDetection` layer, hence it fails to load your model.

**Comment by razon30** [comment]
> Apologies, I misinterpreted your error. I think your model is a bit old, could that be true? You can update the model like this (typed from the top of my head, might be some error):
> 
> ```python
> import keras_retinanet.models
> model = keras_retinanet.models.backbone('resnet50').retinanet(number_of_classes)
> model.load_weights("/path/to/old/model.h5", by_name=True)
> model.save("/path/to/updated/model.h5")
> ```
> 
> The `NonMaximumSuppression` layer got merged into the `FilterDetection` layer, hence it fails to load your model.

Where to put this code?
