### ISSUE TITLE
AttributeError: 'CSVGenerator' object has no attribute 'groups'

### ISSUE THREAD

**Issue by wgshun** [fizyr/keras-retinanet#77]
Who knows what's the problem?

None
Epoch 1/20
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 579, in data_generator_task
    generator_output = next(self._generator)
  File "/usr/local/lib/python2.7/dist-packages/keras_retinanet/preprocessing/generator.py", line 130, in next
    self.group_index = (self.group_index + 1) % len(self.groups)
AttributeError: 'CSVGenerator' object has no attribute 'groups'

Traceback (most recent call last):
  File "train_csv.py", line 106, in <module>
    keras.callbacks.ReduceLROnPlateau(monitor='loss', factor=0.1, patience=2, verbose=1, mode='auto', epsilon=0.0001, cooldown=0, min_lr=0),
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 2046, in fit_generator
    generator_output = next(output_generator)
StopIteration

**Comment by hgaiser** [comment]
This matter is resolved then? What was the problem?

**Comment by wgshun** [comment]
I re-copied your new project, and adjusted my data. Then, it works.

**Comment by wgshun** [comment]
Thanks for sharing.

**Comment by Weixing-Zhang** [comment]
This is strange. I got a similar error when the model was training. Thank you in advance. ps. I tried to use the train_csv.py with my custom data.

==============================================================
None
Epoch 1/20
275/873 [========>.....................] - ETA: 5:09 - loss: 0.6573 - regression_loss: 0.0018 - classification_loss: 0.6555Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 579, in data_generator_task
    generator_output = next(self._generator)
  File "build/bdist.linux-x86_64/egg/keras_retinanet/preprocessing/generator.py", line 217, in next
    return self.compute_input_output(group)
  File "build/bdist.linux-x86_64/egg/keras_retinanet/preprocessing/generator.py", line 195, in compute_input_output
    image_group, annotations_group = self.preprocess_group(image_group, annotations_group)
  File "build/bdist.linux-x86_64/egg/keras_retinanet/preprocessing/generator.py", line 115, in preprocess_group
    image, annotations = random_transform(image, annotations, self.image_data_generator)
  File "build/bdist.linux-x86_64/egg/keras_retinanet/utils/image.py", line 76, in random_transform
    boxes[index, 0] = float(min(j))
276/873 [========>.....................] - ETA: 5:08 - loss: 0.6560 - regression_loss: 0.0018 - classification_loss: 0.6542Traceback (most recent call last):
  File "train_csv.py", line 117, in <module>
    keras.callbacks.ReduceLROnPlateau(monitor='loss', factor=0.1, patience=2, verbose=1, mode='auto', epsilon=0.0001, cooldown=0, min_lr=0),
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 2046, in fit_generator
    generator_output = next(output_generator)
StopIteration

**Comment by de-vri-es** [comment]
@Weixing-Zhang: The error message you posted is incomplete. The actual exception is missing. That is probably because of the way keras handles exception in data generators (would be improved by fchollet/keras#8485) . I do not think this is the same issue though.

If this is a reproducible error, could you update Keras to latest master (so that you get fchollet/keras#8485) and open a new issue with the updated error message?
