### ISSUE TITLE
Problem ablout convered the mobilenet128 model to inference model

### ISSUE THREAD

**Issue by yuyijie1995** [fizyr/keras-retinanet#772]
Using TensorFlow backend.
Traceback (most recent call last):
  File "D:/postgraduateworking/suanfa/keras-retinanet/keras_retinanet/bin/convert_model.py", line 59, in <module>
    main()
  File "D:/postgraduateworking/suanfa/keras-retinanet/keras_retinanet/bin/convert_model.py", line 52, in main
    model = models.load_model(args.model_in, convert=True, backbone_name=args.backbone, nms=args.nms)
  File "D:/postgraduateworking/suanfa/keras-retinanet/keras_retinanet/bin\..\..\keras_retinanet\models\__init__.py", line 83, in load_model
    model = keras.models.load_model(filepath, custom_objects=backbone(backbone_name).custom_objects)
  File "D:/postgraduateworking/suanfa/keras-retinanet/keras_retinanet/bin\..\..\keras_retinanet\models\__init__.py", line 59, in backbone
    return b(backbone_name)
  File "D:/postgraduateworking/suanfa/keras-retinanet/keras_retinanet/bin\..\..\keras_retinanet\models\mobilenet.py", line 36, in __init__
    'relu6': mobilenet.relu6,
AttributeError: module 'keras_applications.mobilenet' has no attribute 'relu6'
I used the mobilenet complete the trainning ,but when I converted the model,this error happened ,can you tell me how to solve it?  thanks a lot

**Comment by hgaiser** [comment]
The line where it says the error occurred no longer looks like that. Try updating keras-retinanet to see if it resolves your issue.

**Comment by yuyijie1995** [comment]
Thanks a lot  I updated and solved it !
