### ISSUE TITLE
Problems with smooth_l1

### ISSUE THREAD

**Issue by exaltation** [fizyr/keras-retinanet#78]
Hi! I am trying to train retinanet on Pascal VOC dataset, but getting a ValueError:
```
Traceback (most recent call last):
  File "examples/train_pascal.py", line 111, in <module>
    keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.1, patience=10, verbose=1, mode='auto', epsilon=0.0001, cooldown=0, min_lr=0),
  File "C:\Users\Abdurasul\Anaconda3\envs\ML\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Abdurasul\Anaconda3\envs\ML\lib\site-packages\keras\engine\training.py", line 2114, in fit_generator
    class_weight=class_weight)
  File "C:\Users\Abdurasul\Anaconda3\envs\ML\lib\site-packages\keras\engine\training.py", line 1826, in train_on_batch
    check_batch_axis=True)
  File "C:\Users\Abdurasul\Anaconda3\envs\ML\lib\site-packages\keras\engine\training.py", line 1411, in _standardize_user_data
    exception_prefix='target')
  File "C:\Users\Abdurasul\Anaconda3\envs\ML\lib\site-packages\keras\engine\training.py", line 153, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking target: expected regression to have shape (None, None, 4) but got array with shape (1, 90360, 5)
```

Considering
```
model.compile(
        loss={
            'regression'    : keras_retinanet.losses.smooth_l1(),
            'classification': keras_retinanet.losses.focal()
        },
        optimizer=keras.optimizers.adam(lr=1e-5, clipnorm=0.001)
    )
```
I think the problem is in the implementation of smooth_l1 function, but I have no idea how to fix it. Can anyone help?

**Comment by exaltation** [comment]
Sorry, forgot to check for existing issues, here is the [answer](https://github.com/fizyr/keras-retinanet/issues/66), closing this one.
