### ISSUE TITLE
Cannot train with mobilenet160_0.75

### ISSUE THREAD

**Issue by TimoK93** [fizyr/keras-retinanet#794]
Hi all,

I just tried to train a net with mobilenet160_0.75 as backbone. I just added "--backbone mobilenet160_0.75" to the command provided in the README.md for training on csv datasets. It is throwing an error while creating mobilenet in site-package keras-applications. 

**The command i used:**

`$ python3 keras_retinanet/bin/train.py --backbone mobilenet160_0.75 csv /.../annotations.csv /.../class_mapping.csv `

**The error that is thrown:**
```
Creating model, this may take a second...
Traceback (most recent call last):
  File "keras_retinanet/bin/train.py", line 480, in <module>
    main()
  File "keras_retinanet/bin/train.py", line 442, in main
    freeze_backbone=args.freeze_backbone
  File "keras_retinanet/bin/train.py", line 109, in create_models
    model          = model_with_weights(backbone_retinanet(num_classes, modifier=modifier), weights=weights, skip_mismatch=True)
  File "keras_retinanet/bin/../../keras_retinanet/models/mobilenet.py", line 35, in retinanet
    return mobilenet_retinanet(*args, backbone=self.backbone, **kwargs)
  File "keras_retinanet/bin/../../keras_retinanet/models/mobilenet.py", line 98, in mobilenet_retinanet
    backbone = mobilenet.MobileNet(input_tensor=inputs, alpha=alpha, include_top=False, pooling=None, weights=None)
  File "/home/corvitac/.local/lib/python3.5/site-packages/keras_applications/mobilenet.py", line 183, in MobileNet
    data_format=backend.image_data_format(),
AttributeError: 'NoneType' object has no attribute 'image_data_format'
```

Did I forget an additional argument?

_Originally posted by @TimoK93 in https://github.com/fizyr/keras-retinanet/issues/300#issuecomment-438181902_

**Comment by hgaiser** [comment]
Hmm I think I've seen this error before a d it got fixed. Could you try the `master` version of keras-retinanet and the latest Keras?

**Comment by TimoK93** [comment]
O yes!
I updated to the newest version and its working. My fault...
Thanks!
