### ISSUE TITLE
Error using custom ratios in anchors .ini file

### ISSUE THREAD

**Issue by TimoK93** [fizyr/keras-retinanet#808]
Hey fizyr,

I just mentioned a bug using custom anchors. I trained my net using default setting except the achor ratios. I defined them in a config file. After training i tried to run inference but then an error occured. I'll show you the config file and the Error:

## Config file
```
[anchor_parameters]
scales = 1 0.66 1.33
ratios = 0.25 0.5 1 2 4
strides = 8 16 32 64 128
sizes = 32 64 128 256 512
```

## Error
```
Traceback (most recent call last):
  File "/.../SimpleRetinaNetTester.py", line 30, in predict_next_frame
    boxes, scores, labels = self.model.predict_on_batch(batch)
  File "/.../lib/python3.5/site-packages/keras/engine/training.py", line 1274, in predict_on_batch
    outputs = self.predict_function(ins)
  File "/.../lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/.../lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/.../lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/.../lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [1,288300] vs. [1,172980]
	 [[{{node boxes/mul_1}} = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](boxes/mul, boxes/sub)]]
	 [[{{node filtered_detections/map/while/strided_slice_6/_1877}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1986_filtered_detections/map/while/strided_slice_6", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopfiltered_detections/map/while/non_max_suppression/NonMaxSuppressionV3/max_output_size/_1817)]]
```

Do i forget something? I'm just using keras_retinanet.models.load_model()... Maybe you have some suggestions?

Greetings, 
Timo

**Comment by hgaiser** [comment]
I'm assuming you're using the convert script to convert your model to an inference model? Did you pass your settings during that step? It needs it at that point to correctly transform the model to an inference model.
