### ISSUE TITLE
colab ModuleNotFoundError: No module named 'keras_retinanet.utils.compute_overlap'

### ISSUE THREAD

**Issue by duhithas** [fizyr/keras-retinanet#835]
Im training my custom-dataset using COLAB Notebook , 
Refered to FAQ 
unable to run the below command 
!python keras-retinanet/setup.py build_ext --inplace

running build_ext
cythoning keras_retinanet/utils/compute_overlap.pyx to keras_retinanet/utils/compute_overlap.c
error: /content/keras_retinanet/utils/compute_overlap.pyx

However I have uploaded compute_overlap.c file from my local system , but when I run the file train.py with the specified path it gives this error below
Using TensorFlow backend.
Traceback (most recent call last):
  File "keras-retinanet/keras_retinanet/bin/train.py", line 35, in <module>
    from .. import layers  # noqa: F401
  File "keras-retinanet/keras_retinanet/bin/../../keras_retinanet/layers/__init__.py", line 1, in <module>
    from ._misc import RegressBoxes, UpsampleLike, Anchors, ClipBoxes  # noqa: F401
  File "keras-retinanet/keras_retinanet/bin/../../keras_retinanet/layers/_misc.py", line 19, in <module>
    from ..utils import anchors as utils_anchors
  File "keras-retinanet/keras_retinanet/bin/../../keras_retinanet/utils/anchors.py", line 20, in <module>
    from ..utils.compute_overlap import compute_overlap
ModuleNotFoundError: No module named 'keras_retinanet.utils.compute_overlap'

**Comment by hgaiser** [comment]
This error is handled in the [FAQ](https://github.com/fizyr/keras-retinanet#faq).

**Comment by hgaiser** [comment]
I misread the first part, seems you can't build the extension. Do you have a longer error than this, it's not saying what is going wrong.

**Comment by duhithas** [comment]
No there are no much details about this error..

**Comment by duhithas** [comment]
Kindly suggest an other alternative for this problem

**Comment by hgaiser** [comment]
Could you share a screenshot of your terminal when trying to compile this extension ?

**Comment by duhithas** [comment]
apologies for the delay ,
PFA as requested
As in the i marked the compute_overlap.c file

**Comment by hgaiser** [comment]
?

I'm not seeing anything.

**Comment by duhithas** [comment]
I have shared a png format
I would resend you again

**Comment by hgaiser** [comment]
I think you're sending it as an attachment, but that doesn't seem to work.

**Comment by duhithas** [comment]
Hope you would be able to view now
![colab_error](https://user-images.githubusercontent.com/42568072/49808908-9c529100-fd83-11e8-95ee-13175df0f8b6.png)

**Comment by hgaiser** [comment]
Sounds like it could be an issue related to colab. Could you try on your own system to see if the extension can be built there.

**Comment by duhithas** [comment]
Yes i have , It worked and hence I was able to create compute_overlap.c as i have marked

**Comment by hgaiser** [comment]
Is that the version you uploaded to colab? Depending on your system libraries that might not work properly. Could you try it on a clean clone of keras-retinanet?

**Comment by hgaiser** [comment]
You can try to use the python version of the cython code, then you don't need the extensions:

https://github.com/fizyr/keras-retinanet/blob/0.3.1/keras_retinanet/utils/anchors.py#L232-L256

**Comment by duhithas** [comment]
![colab_error](https://user-images.githubusercontent.com/42568072/49811999-6b298f00-fd8a-11e8-9343-4d373623dce4.png)
kindly check above , it uses the python version , 
kindly guide me if im wrong

**Comment by hgaiser** [comment]
You're now doing custom stuff, it's more difficult to support that. By the looks of it you're still trying to import the compute_overlap module, but I'm guessing you just added it to the `anchors.py`? You don't need to import compute_overlap then..

**Comment by nosa999** [comment]
![image](https://user-images.githubusercontent.com/40929193/50005425-89c49b80-ffbf-11e8-8a63-7df17662c269.png)
I have this error :(

**Comment by hgaiser** [comment]
You can't pass a link as csv file, it needs to be a file...

**Comment by duhithas** [comment]
kindly run this command before you could run pip install . --user
!cd keras-retinanet && pip install . --user
