### ISSUE TITLE
Problem in printing mAP into terminal after every epoch

### ISSUE THREAD

**Issue by Rajat-Mehta** [fizyr/keras-retinanet#845]
I am training retinanet using my own custom dataset in the form of CSVGenerator. I want to print the mAP value after every epoch and for that I have added a callback using Evaluate(see the code below). But after one epoch of training the program got terminated with the following error: 

```
Epoch 00001: saving model to ./snapshots/weights.01-0.84.hdf5
Running network: N/A% (0 of 20000) |                                                                                                                                              | Elapsed Time: 0:00:00 ETA:  --:--:--Traceback (most recent call last):
  File "fine_tune_retina.py", line 78, in <module>
    workers=1, use_multiprocessing=False, shuffle=True, initial_epoch=0)
  File "/kaecheledata/MIO-TCD-Localization/keras_retina_net/keras-retinanet/retina/lib/python3.4/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/kaecheledata/MIO-TCD-Localization/keras_retina_net/keras-retinanet/retina/lib/python3.4/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/kaecheledata/MIO-TCD-Localization/keras_retina_net/keras-retinanet/retina/lib/python3.4/site-packages/keras/engine/training_generator.py", line 251, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/kaecheledata/MIO-TCD-Localization/keras_retina_net/keras-retinanet/retina/lib/python3.4/site-packages/keras/callbacks.py", line 79, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/kaecheledata/MIO-TCD-Localization/keras_retina_net/keras-retinanet/keras_retinanet/callbacks/eval.py", line 69, in on_epoch_end
    save_path=self.save_path
  File "/kaecheledata/MIO-TCD-Localization/keras_retina_net/keras-retinanet/keras_retinanet/utils/eval.py", line 168, in evaluate
    all_detections     = _get_detections(generator, model, score_threshold=score_threshold, max_detections=max_detections, save_path=save_path)
  File "/kaecheledata/MIO-TCD-Localization/keras_retina_net/keras-retinanet/keras_retinanet/utils/eval.py", line 84, in _get_detections
    boxes, scores, labels = model.predict_on_batch(np.expand_dims(image, axis=0))[:3]
ValueError: need more than 2 values to unpack
```

I believe this error is because I have not converted the training model to the inference model, but how to do it in my case because I believe the validation is done internally by the fit_generator. So how can I get rid of this error?

Here is my training code:
```
model = load_model('./snapshots/weights.30-0.85.hdf5', backbone_name='resnet50')
batch_size = 4
epochs=50

transform_generator = random_transform_generator(
    min_rotation=-0.1,
    max_rotation=0.1,
    min_scaling=(0.9, 0.9),
    max_scaling=(1.1, 1.1),
    flip_x_chance=0.5
)

generator = CSVGenerator(
    csv_data_file='./data_set_retina/train.csv',
    csv_class_file='./data_set_retina/class_id_mapping.txt',
    batch_size=batch_size,
    transform_generator=transform_generator
)

generator_val = CSVGenerator(
    csv_data_file='./data_set_retina/val.csv',
    csv_class_file='./data_set_retina/class_id_mapping.txt',
    batch_size=batch_size,
    transform_generator=transform_generator
)
#    transform_generator=transform_generator
with open('./data_set_retina/train.csv', 'r') as f:
    l = f.readlines()
with open('./data_set_retina/val.csv', 'r') as f:
    v = f.readlines()

ts=len(l)/batch_size
vs=len(v)/batch_size
model.compile(
    loss={
        'regression'    : keras_retinanet.losses.smooth_l1(),
        'classification': keras_retinanet.losses.focal()
    },
    optimizer=keras.optimizers.adam(lr=1e-5, clipnorm=0.001)
)
csv_logger = keras.callbacks.CSVLogger('./logs/training_log.csv', separator=',', append=False)
evaluation = Evaluate(generator_val, weighted_average=True)

model.fit_generator(generator, steps_per_epoch=10000, epochs=epochs, verbose=1, callbacks=[history, csv_logger, checkpointer, evaluation],
                    validation_data=generator_val, validation_steps=5000, class_weight=None, max_queue_size=10,
                    workers=1, use_multiprocessing=False, shuffle=True, initial_epoch=0)
```

**Comment by hgaiser** [comment]
Check the supplied `train.py`, it also evaluates and prints the mAP every epoch. It requires the model to be a prediction model, so it wraps the training model with some additional layers to compute the bounding boxes and perform NMS. You'd either need to do this in your training script as well, or use the supplied `train.py`.

**Comment by hgaiser** [comment]
Any update on this?
