### ISSUE TITLE
Fail on inference

### ISSUE THREAD

**Issue by MichaelMonashev** [fizyr/keras-retinanet#846]
After 3 hours of good bbox predicting, I got this:
```
Traceback (most recent call last):
  File "predict_daemon.py", line 465, in <module>
    _main(parser.parse_args())
  File "predict_daemon.py", line 386, in _main
    serverBboxes = predict_bboxes(bbox_model, serverImagesScaled, serverScales)
  File "predict_daemon.py", line 201, in predict_bboxes
    bboxes, scores, labels = model.predict_on_batch(images)
  File "/home/xxx/.local/lib/python3.5/site-packages/keras/engine/training.py", line 1274, in predict_on_batch
    outputs = self.predict_function(ins)
  File "/home/xxx/.local/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/home/xxx/.local/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1399, in __call__
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 526, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: scores has incompatible shape
         [[{{node filtered_detections/map/while/non_max_suppression/NonMaxSuppressionV3}} = NonMaxSuppressionV3[_device="/job:localhost/replica:0/task:0/device:CPU:0"](filtered_detections/map/while/GatherNd, filtered_detections/map/while/strided_slice_2, filtered_detections/map/while/sub/x, filtered_detections/map/while/non_max_suppression/iou_threshold, filtered_detections/map/while/non_max_suppression/score_threshold)]]

```

**Comment by hgaiser** [comment]
Can you reproduce the issue? Does it always happen on a certain image? What are you executing?

**Comment by MichaelMonashev** [comment]
> Can you reproduce the issue?

No. This problems raise after some hours of working. 

> Does it always happen on a certain image?

No

> What are you executing?

I called model.predict_on_batch(images) more than 1000 times before bug.

**Comment by MichaelMonashev** [comment]
one more traceback:
```
Traceback (most recent call last):
  File "predict_daemon.py", line 465, in <module>
    _main(parser.parse_args())
  File "predict_daemon.py", line 386, in _main
    serverBboxes = predict_bboxes(bbox_model, serverImagesScaled, serverScales)
  File "predict_daemon.py", line 201, in predict_bboxes
    bboxes, scores, labels = model.predict_on_batch(images)
  File "/home/xxx/.local/lib/python3.5/site-packages/keras/engine/training.py", line 1274, in predict_on_batch
    outputs = self.predict_function(ins)
  File "/home/xxx/.local/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/home/xxx/.local/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1399, in __call__
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 526, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0] = 57 is not in [0, 5)
         [[{{node filtered_detections/map/while/embedding_lookup_1}} = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_INT64, _device="/job:localhost/replica:0/task:0/device:CPU:0"](filtered_detections/map/while/Where, filtered_detections/map/while/non_max_suppression/NonMaxSuppressionV3, filtered_detections/map/while/embedding_lookup_1/axis)]]
```

**Comment by hgaiser** [comment]
Try figuring out which image is causing  this error, it should happen always when you run prediction on the same data.

**Comment by MichaelMonashev** [comment]
```
Traceback (most recent call last):
  File "predict_daemon.py", line 465, in <module>
    _main(parser.parse_args())
  File "predict_daemon.py", line 386, in _main
    serverBboxes = predict_bboxes(bbox_model, serverImagesScaled, serverScales)
  File "predict_daemon.py", line 201, in predict_bboxes
    bboxes, scores, labels = model.predict_on_batch(images)
  File "/home/michael/.local/lib/python3.5/site-packages/keras/engine/training.py", line 1274, in predict_on_batch
    outputs = self.predict_function(ins)
  File "/home/michael/.local/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/home/michael/.local/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1399, in __call__
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 526, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0] = 148 is not in [0, 137)
         [[{{node filtered_detections/map/while/embedding_lookup_1}} = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_INT64, _device="/job:localhost/replica:0/task:0/device:CPU:0"](filtered_detections/map/while/Where, filtered_detections/map/while/non_max_suppression/NonMaxSuppressionV3, filtered_detections/map/while/embedding_lookup_1/axis)]]
```

**Comment by hgaiser** [comment]
I really need a reproducible case otherwise I can't help much.

Also, what version of tensorflow are you using?

**Comment by MichaelMonashev** [comment]
I use batch size 8. May be only one image of 8 cause error.

**Comment by MichaelMonashev** [comment]
```
$ python3 -c 'import tensorflow as tf; print(tf.__version__)'
1.11.0
```

**Comment by MichaelMonashev** [comment]
I decrease batch size to 1 and start logging each image. Waiting for error.

**Comment by MichaelMonashev** [comment]
There are no crashes with batch size = 1.

**Comment by MichaelMonashev** [comment]
With batch size = 2 everything OK.

**Comment by MichaelMonashev** [comment]
With batch size = 3 everything OK.

**Comment by MichaelMonashev** [comment]
I think, it crash with 4 images in batch because batch too big for GeForce GTX 1080 .

**Comment by hgaiser** [comment]
That's weird, normally it would throw an out of memory error in that case. Batch size of 4 does sound big for a 1080. Can we consider this issue resolved then?

**Comment by NatLun091238** [comment]
I am working on a very different project and my predictions using Google's ML Engine. Everything is working fine for a batch size of about 30K (1D application). However, I get a similar error message on larger batch size. The error message does not disappear even if an instance with larger memory used.
