### ISSUE TITLE
numpy.ufunc has the wrong size

### ISSUE THREAD

**Issue by DeepStillWater** [fizyr/keras-retinanet#888]
Hello,when I run 'keras_retinanet/bin/train.py csv new_train_labels.csv train_classes.csv' in terminal,I got this error:
Traceback (most recent call last):
  File "keras_retinanet/bin/train.py", line 35, in <module>
    from .. import layers  # noqa: F401
  File "keras_retinanet/bin/../../keras_retinanet/layers/__init__.py", line 1, in <module>
    from ._misc import RegressBoxes, UpsampleLike, Anchors, ClipBoxes  # noqa: F401
  File "keras_retinanet/bin/../../keras_retinanet/layers/_misc.py", line 19, in <module>
    from ..utils import anchors as utils_anchors
  File "keras_retinanet/bin/../../keras_retinanet/utils/anchors.py", line 20, in <module>
    from ..utils.compute_overlap import compute_overlap
  File "__init__.pxd", line 861, in init keras_retinanet.utils.compute_overlap
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216

I followed the steps in readme,but I don`t know why.

**Comment by martinzlocha** [comment]
This isn't a RetinaNet issue, it looks like you have multiple versions of numpy installed. Please google your errors in the future, you can see a similar problem and the solution here: https://github.com/scikit-learn/scikit-learn/issues/3537

**Comment by DeepStillWater** [comment]
It did is the version of numpy`s problem,I upgrade it to the newest version,and the error is solved.
