### ISSUE TITLE
('Keyword argument not understood:', 'implementation')while testing the model

### ISSUE THREAD

**Issue by alaa-Mz** [fizyr/keras-retinanet#898]
I have generated a trained model using my custom dataset and while testing I am getting this error.

**Comment by alaa-Mz** [comment]
any help I will really appreciated

**Comment by hgaiser** [comment]
Some more information would be nice. What command are you executing, what is your environment like, what steps did you take so far. I don't think you can expect help with this limited amount of information.

**Comment by alaa-Mz** [comment]
sorry for the delay, I am working in Anaconda python 3.6 I trained the model then when I tested I got this:

    Using TensorFlow backend.
Traceback (most recent call last):
  File "test.py", line 57, in <module>
    model=load_model('model.h5')
  File "C:\Users\alaaa\Anaconda3\envs\python-3.6\lib\site-packages\keras\engine\saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "C:\Users\alaaa\Anaconda3\envs\python-3.6\lib\site-packages\keras\engine\saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "C:\Users\alaaa\Anaconda3\envs\python-3.6\lib\site-packages\keras\engine\saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "C:\Users\alaaa\Anaconda3\envs\python-3.6\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "C:\Users\alaaa\Anaconda3\envs\python-3.6\lib\site-packages\keras\utils\generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "C:\Users\alaaa\Anaconda3\envs\python-3.6\lib\site-packages\keras\engine\sequential.py", line 300, in from_config
    custom_objects=custom_objects)
  File "C:\Users\alaaa\Anaconda3\envs\python-3.6\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "C:\Users\alaaa\Anaconda3\envs\python-3.6\lib\site-packages\keras\utils\generic_utils.py", line 147, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "C:\Users\alaaa\Anaconda3\envs\python-3.6\lib\site-packages\keras\layers\convolutional_recurrent.py", line 1091, in from_config
    return cls(**config)
  File "C:\Users\alaaa\Anaconda3\envs\python-3.6\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\alaaa\Anaconda3\envs\python-3.6\lib\site-packages\keras\layers\convolutional_recurrent.py", line 961, in __init__
    **kwargs)
  File "C:\Users\alaaa\Anaconda3\envs\python-3.6\lib\site-packages\keras\layers\convolutional_recurrent.py", line 151, in __init__
    **kwargs)
  File "C:\Users\alaaa\Anaconda3\envs\python-3.6\lib\site-packages\keras\layers\recurrent.py", line 408, in __init__
    super(RNN, self).__init__(**kwargs)
  File "C:\Users\alaaa\Anaconda3\envs\python-3.6\lib\site-packages\keras\engine\base_layer.py", line 128, in __init__
    raise TypeError('Keyword argument not understood:', kwarg)
TypeError: ('Keyword argument not understood:', 'implementation')

**Comment by hgaiser** [comment]
Try using our wrapper for `keras.models.load_model`, it is `keras_retinanet.models.load_model`.

**Comment by alaa-Mz** [comment]
i am new in Keras and i did change in the code but still got the same error as above

    from keras_retinanet.models import load_model
#from keras.models import load_model
import numpy as np

def mean_squared_loss(x1,x2):


	''' Compute Euclidean Distance Loss  between 
	input frame and the reconstructed frame'''

	diff=x1-x2
	a,b,c,d,e=diff.shape
	n_samples=a*b*c*d*e
	sq_diff=diff**2
	Sum=sq_diff.sum()
	dist=np.sqrt(Sum)
	mean_dist=dist/n_samples

	return mean_dist



'''Define threshold for Sensitivity
Lower the Threshhold,higher the chances that a bunch of frames will be flagged as Anomalous.

'''

threshold= 0.2
model=load_model('model.h5')
X_test=np.load('testing.npy')
frames=X_test.shape[2]
#Need to make number of frames divisible by 10


flag=0 #Overall video flagq

frames=frames-frames%10

X_test=X_test[:,:,:frames]
X_test=X_test.reshape(-1,227,227,10)
X_test=np.expand_dims(X_test,axis=4)

for number,bunch in enumerate(X_test):
	n_bunch=np.expand_dims(bunch,axis=0)
	reconstructed_bunch=model.predict(n_bunch)


	loss=mean_squared_loss(n_bunch,reconstructed_bunch)

	if loss>threshold:
		print("Anomalous bunch of frames at bunch number {}".format(number))
		flag=1

	else:
		print('Bunch Normal')



if flag==1:
	print("Anomalous Events detected")

**Comment by hgaiser** [comment]
Wait, what model are you trying to load? It seems to attempt to load a `RNN` layer, but we don't use those in retinanet..

**Comment by alaa-Mz** [comment]
the model is autoencoder and LSTM


>>THE MODEL CODE:  
    from keras.layers import Conv3D,ConvLSTM2D,Conv3DTranspose
    from keras.models import Sequential

    def load_model():

	    model=Sequential()
	    model.add(Conv3D(filters=128,kernel_size=(11,11,1),strides=(4,4,1),padding='valid',input_shape=(227,227,10,1),activation='tanh'))
	   model.add(Conv3D(filters=64,kernel_size=(5,5,1),strides=(2,2,1),padding='valid',activation='tanh'))

	    model.add(ConvLSTM2D(filters=64,kernel_size=(3,3),strides=1,padding='same',dropout=0.4,recurrent_dropout=0.3,return_sequences=True))
	    model.add(ConvLSTM2D(filters=32,kernel_size=(3,3),strides=1,padding='same',dropout=0.3,return_sequences=True))
	    model.add(ConvLSTM2D(filters=64,kernel_size=(3,3),strides=1,return_sequences=True, padding='same',dropout=0.5))

	   model.add(Conv3DTranspose(filters=128,kernel_size=(5,5,1),strides=(2,2,1),padding='valid',activation='tanh'))
	    model.add(Conv3DTranspose(filters=1,kernel_size=(11,11,1),strides=(4,4,1),padding='valid',activation='tanh'))

	    model.compile(optimizer='adam',loss='mean_squared_error',metrics=['accuracy'])

	    return model

**Comment by hgaiser** [comment]
Dude you seem to be lost... Why do you think this issue is in the correct repository?

**Comment by alaa-Mz** [comment]
actually, I am stuck in this error for almost three weeks I do not where is the problem and what should I do

**Comment by hgaiser** [comment]
Try the Keras support channels, this is the issue page for keras-retinanet, which it seems has nothing to do with your issue. It's a bit rude to try to get help here and even more rude not to mention it.

**Comment by alaa-Mz** [comment]
I am new in Keras and I do not know there is a different channel for that, anyway thanks for your time

**Comment by abhishekpopli** [comment]
> I am new in Keras and I do not know there is a different channel for that, anyway thanks for your time

I am working on the same repo and faced the same error.
Update to keras 2.1.1 and it works fine.
[https://github.com/blackeagle01/Abnormal_Event_Detection/issues/23](url)
