### ISSUE TITLE
I have a Pascal VOC format folder which has images and annotations. The problem is annotations xml file doesn't have truncated and difficulty tag

### ISSUE THREAD

**Issue by PJ-N2804** [fizyr/keras-retinanet#926]
I get the following error when i start training the model.
Epoch 1/50
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/rootpj28-04meta-session/Downloads/keras-retinanet-master/y35/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/rootpj28-04meta-session/Downloads/keras-retinanet-master/y35/lib/python3.5/site-packages/keras/utils/data_utils.py", line 401, in get_index
    return _SHARED_SEQUENCES[uid][i]
  File "/home/rootpj28-04meta-session/Downloads/keras-retinanet-master/y35/lib/python3.5/site-packages/keras_retinanet-0.5.0-py3.5-linux-x86_64.egg/keras_retinanet/preprocessing/generator.py", line 334, in __getitem__
    inputs, targets = self.compute_input_output(group)
  File "/home/rootpj28-04meta-session/Downloads/keras-retinanet-master/y35/lib/python3.5/site-packages/keras_retinanet-0.5.0-py3.5-linux-x86_64.egg/keras_retinanet/preprocessing/generator.py", line 303, in compute_input_output
    annotations_group = self.load_annotations_group(group)
  File "/home/rootpj28-04meta-session/Downloads/keras-retinanet-master/y35/lib/python3.5/site-packages/keras_retinanet-0.5.0-py3.5-linux-x86_64.egg/keras_retinanet/preprocessing/generator.py", line 142, in load_annotations_group
    annotations_group = [self.load_annotations(image_index) for image_index in group]
  File "/home/rootpj28-04meta-session/Downloads/keras-retinanet-master/y35/lib/python3.5/site-packages/keras_retinanet-0.5.0-py3.5-linux-x86_64.egg/keras_retinanet/preprocessing/generator.py", line 142, in <listcomp>
    annotations_group = [self.load_annotations(image_index) for image_index in group]
  File "/home/rootpj28-04meta-session/Downloads/keras-retinanet-master/y35/lib/python3.5/site-packages/keras_retinanet-0.5.0-py3.5-linux-x86_64.egg/keras_retinanet/preprocessing/pascal_voc.py", line 199, in load_annotations
    raise_from(ValueError('invalid annotations file: {}: {}'.format(filename, e)), None)
  File "<string>", line 3, in raise_from
ValueError: invalid annotations file: 000001284.xml: could not parse object #0: missing element 'truncated'
"""

**Comment by de-vri-es** [comment]
You already indicate the exact problem in the title of the issue. It should be a simple matter for you to fix the problem in your dataset.

If you feel there is a problem with the VOC generator, feel free to open a pull request.

**Comment by PJ-N2804** [comment]
I have like thousands of xml files.So is there something I could change in VOC generator, to skip checking for truncated and difficult tags?
