### ISSUE TITLE
Error when running train_csv with validation set

### ISSUE THREAD

**Issue by Checksum** [fizyr/keras-retinanet#93]
I tried running the master version today with a validation set and it always errors out in the last by one step of the first epoch. Seems to run fine without the validation dataset though.

```
Epoch 1/20
11/12 [==========================>...] - ETA: 1s - loss: 1.6621 - regression_loss: 0.4868 - classification_loss: 1.1753Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\srinath\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\srinath\AppData\Local\Programs\Python\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\srinath\.virtualenv\tensorflow-gpu\lib\site-packages\keras\utils\data_utils.py", line 579, in data_generator_task
    generator_output = next(self._generator)
  File "d:\github\keras-retinanet\keras_retinanet\preprocessing\generator.py", line 189, in __next__
    return self.next()
  File "d:\github\keras-retinanet\keras_retinanet\preprocessing\generator.py", line 200, in next
    return self.compute_input_output(group_index)
  File "d:\github\keras-retinanet\keras_retinanet\preprocessing\generator.py", line 178, in compute_input_output
    image_group, annotations_group = self.preprocess_group(image_group, annotations_group)
  File "d:\github\keras-retinanet\keras_retinanet\preprocessing\generator.py", line 94, in preprocess_group
    image, annotations = random_transform(image, annotations, self.image_data_generator)
  File "d:\github\keras-retinanet\keras_retinanet\utils\image.py", line 70, in random_transform
    boxes[index, 0] = float(min(j))
ValueError: min() arg is an empty sequence

Traceback (most recent call last):
  File "examples\train_csv.py", line 117, in <module>
    keras.callbacks.ReduceLROnPlateau(monitor='loss', factor=0.1, patience=2, verbose=1, mode='auto', epsilon=0.0001, cooldown=0, min_lr=0),
  File "C:\Users\srinath\.virtualenv\tensorflow-gpu\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\srinath\.virtualenv\tensorflow-gpu\lib\site-packages\keras\engine\training.py", line 2099, in fit_generator
    use_multiprocessing=use_multiprocessing)
  File "C:\Users\srinath\.virtualenv\tensorflow-gpu\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\srinath\.virtualenv\tensorflow-gpu\lib\site-packages\keras\engine\training.py", line 2195, in evaluate_generator
    generator_output = next(output_generator)
StopIteration
```

**Comment by hgaiser** [comment]
It seems you have defined bounding boxes with no area (for example `(0, 0, 0, 0)`). Check the annotations of your validation set, something is wrong there.

**Comment by Checksum** [comment]
Yep, that was it. There wasn't any invalid bounding box though, and I couldn't identify which sample(s) caused the issue.

Is there any way to print debug info to identify which entries cause error in particular?

**Comment by hgaiser** [comment]
[This](https://github.com/fizyr/keras-retinanet/pull/96) PR will hopefully give you more debug info on what is going wrong. For now I'll close this issue since it appears to be resolved.

**Comment by Checksum** [comment]
Awesome, that’s exactly what I needed. Thanks for all your hard work!

**Comment by alexiskattan** [comment]
I'm getting this same error when I train on the coco dataset.  I update the software but am still getting it.
