### ISSUE TITLE
Module not found issue

### ISSUE THREAD

**Issue by momo1986** [fizyr/keras-retinanet#933]
Using TensorFlow backend.
Traceback (most recent call last):
  File "train.py", line 35, in <module>
    from .. import layers  # noqa: F401
  File "../../keras_retinanet/layers/__init__.py", line 1, in <module>
    from ._misc import RegressBoxes, UpsampleLike, Anchors, ClipBoxes  # noqa: F401
  File "../../keras_retinanet/layers/_misc.py", line 19, in <module>
    from ..utils import anchors as utils_anchors
  File "../../keras_retinanet/utils/anchors.py", line 20, in <module>
    from ..utils.compute_overlap import compute_overlap
ModuleNotFoundError: No module named 'keras_retinanet.utils.compute_overlap'

**Comment by hgaiser** [comment]
Check the [README](https://github.com/fizyr/keras-retinanet/blob/master/README.md).
