### ISSUE TITLE
train  wrong

### ISSUE THREAD

**Issue by HuangQinJian** [fizyr/keras-retinanet#934]
when I train the model with my dataset（use validation）,the code  stop trainning in the epoch 2....Lasting one night！

But when I do not use validation,it is OK?Why?

```
python keras_retinanet/bin/train.py --steps 1000 csv keras_retinanet/CSV/train_annotations.csv keras_retinanet/CSV/classes.csv --val-annotations keras_retinanet/CSV/val_annotations.csv
```

```
None
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
Epoch 1/50
1000/1000 [==============================] - 343s 343ms/step - loss: 3.3668 - regression_loss: 2.5670 - classification_loss: 0.7998
Running network: 100% (382 of 382) |################################################################################################################| Elapsed Time: 0:00:36 Time:  0:00:36
Parsing annotations: 100% (382 of 382) |############################################################################################################| Elapsed Time: 0:00:00 Time:  0:00:00
32 instances of class tieke with average precision: 0.0079
174 instances of class heiding with average precision: 0.0335
84 instances of class daoju with average precision: 0.0340
162 instances of class dian with average precision: 0.0101
80 instances of class jiandao with average precision: 0.0212
mAP: 0.0213

Epoch 00001: saving model to ./snapshots/resnet50_csv_01.h5
Epoch 2/50
 942/1000 [===========================>..] - ETA: 14s - loss: 2.6230 - regression_loss: 2.0926 - classification_loss: 0.5304
```

**Comment by hgaiser** [comment]
Could you try to figure out on which image it is hanging? Probably the simplest way is to add some print statements in the generator so that you know which images are being loaded. See if you can find a pattern there. I'm guessing some image(s) fail to load, which causes the system to hang.

**Comment by sUtomorrow** [comment]
I met the similar issue when I run train.py with --val-annotations param. 
my python version is 3.6.4，but when I run the code on python version 3.6.2 it works well.
I guess the python version cause this issue, but it also may be caused by some package difference in my two python environment.

**Comment by LaurensHagendoorn** [comment]
It is interesting that this does not happen when you don't use validation. Mine completely freezes randomly when I use multiple workers, but runs normally when I set workers to 0. When you google for this it is a known issue with keras, known in the sense that more people have this issue, unfortunately not in the sense that people know how to fix it. (something about mutex locks)

**Comment by ggghh** [comment]
I have the same problem when adding validation file the train stopped after first epoch without any action, just stuck!
![gggg (1)](https://user-images.githubusercontent.com/16995533/56217663-e619f380-6063-11e9-9532-28ba680e4515.jpg)

**Comment by hgaiser** [comment]
That is a good suggestion @LaurensHagendoorn , @ggghh could you try setting `--workers 0` ?

**Comment by LaurensHagendoorn** [comment]
Like I said, when I set the workers to 0 everything is fine. It's definitely some kind of race condition, I think, but without workers the generator cannot keep up with the GPU, so that kinda sucks

**Comment by danijames** [comment]
set --workers 0, still the problem still persists

**Comment by hgaiser** [comment]
Did you try figuring out if it is a certain image where it is stuck at? To be honest, I don't know what could cause your issue.

**Comment by danijames** [comment]
doing training and validation separately gives output. But training along with validation is getting stuck. Don't know the reason still.

**Comment by ggghh** [comment]
@danijames   doing training and validation separately gives output. But training along with validation is getting stuck. Don't know the reason still.
The problem is resolved.
Because the size of the validation data was large and took some time to calculate, it takes almost two hours.

**Comment by danijames** [comment]
> @danijames doing training and validation separately gives output. But training along with validation is getting stuck. Don't know the reason still.
> The problem is resolved.
> Because the size of the validation data was large and took some time to calculate, it takes almost two hours.

Why it is taking so much time to calculate even training is much faster than that i think?

**Comment by ggghh** [comment]
the fast depended on the GPU data size, I have NVIDIA 1080Ti and used big data

**Comment by tseth92** [comment]
I have an issue not exactly same but very much similar and guess reason would be same. 
When running with --val-annotations, I am getting below error:

```
Running network: N/A% (0 of 5095) |                                                        | Elapsed Time: 0:00:00 ETA:  --:--:--Traceback (most recent call last):
  File "keras_retinanet/bin/train.py", line 514, in <module>
    main()
  File "keras_retinanet/bin/train.py", line 509, in main
    validation_data=validation_generator
  File "/root/.local/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/root/.local/lib/python3.5/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/root/.local/lib/python3.5/site-packages/keras/engine/training_generator.py", line 251, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/root/.local/lib/python3.5/site-packages/keras/callbacks.py", line 79, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "keras_retinanet/bin/../../keras_retinanet/callbacks/common.py", line 31, in on_epoch_end
    self.callback.on_epoch_end(epoch, logs=logs)
  File "keras_retinanet/bin/../../keras_retinanet/callbacks/eval.py", line 69, in on_epoch_end
    save_path=self.save_path
  File "keras_retinanet/bin/../../keras_retinanet/utils/eval.py", line 168, in evaluate
    all_detections     = _get_detections(generator, model, score_threshold=score_threshold, max_detections=max_detections, save_path=save_path)
  File "keras_retinanet/bin/../../keras_retinanet/utils/eval.py", line 115, in _get_detections
    all_detections[i][label] = image_detections[image_detections[:, -1] == label, :-1]
IndexError: list assignment index out of range
```

This happens exactly when all steps are over .

**Comment by hgaiser** [comment]
Closing due to inactivity.
