### ISSUE TITLE
run "retinanet-train csv annotations.csv classes.csv" error

### ISSUE THREAD

**Issue by zaizhizhuang** [fizyr/keras-retinanet#938]
retinanet-train csv annotations.csv classes.csv
Using TensorFlow backend.
2019-03-09 23:23:02.505250: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Creating model, this may take a second...
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to
==================================================================================================
input_1 (InputLayer)            (None, None, None, 3 0
__________________________________________________________________________________________________
padding_conv1 (ZeroPadding2D)   (None, None, None, 3 0           input_1[0][0]

......
......
......

__________________________________________________________________________________________________
None
Epoch 1/50
Exception in thread Thread-2:
Traceback (most recent call last):
  File "d:\program files\python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "d:\program files\python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "d:\program files\python36\lib\site-packages\keras\utils\data_utils.py", line 565, in _run
    with closing(self.executor_fn(_SHARED_SEQUENCES)) as executor:
  File "d:\program files\python36\lib\site-packages\keras\utils\data_utils.py", line 548, in <lambda>
    initargs=(seqs,))
  File "d:\program files\python36\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "d:\program files\python36\lib\multiprocessing\pool.py", line 174, in __init__
    self._repopulate_pool()
  File "d:\program files\python36\lib\multiprocessing\pool.py", line 239, in _repopulate_pool
    w.start()
  File "d:\program files\python36\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "d:\program files\python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "d:\program files\python36\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "d:\program files\python36\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle generator objects

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "d:\program files\python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "d:\program files\python36\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

 os:
windows10

>python
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>pip list
Package             Version
------------------- --------
absl-py             0.7.0
astor               0.7.1
Cython              0.29.6
gast                0.2.2
grpcio              1.19.0
h5py                2.9.0
Keras               2.2.4
Keras-Applications  1.0.7
Keras-Preprocessing 1.0.9
keras-resnet        0.1.0
keras-retinanet     0.5.0
Markdown            3.0.1
numpy               1.14.5
opencv-python       4.0.0.21
Pillow              5.4.1
pip                 18.1
progressbar2        3.39.2
protobuf            3.7.0
python-utils        2.3.0
PyYAML              3.13
scipy               1.2.1
setuptools          39.1.0
six                 1.12.0
tensorboard         1.10.0
tensorflow          1.10.0
termcolor           1.1.0
Werkzeug            0.14.1
wheel               0.33.1

**Comment by akashjjohn** [comment]
had a similar error
check this out https://github.com/fizyr/keras-retinanet/issues/857#issuecomment-451363022
this sort of solved it for me
