### ISSUE TITLE
OpenCV error when using data augmentation such as zoom_range, width_shift_range etc

### ISSUE THREAD

**Issue by tt-leader** [fizyr/keras-retinanet#97]
I'm using the script `train_csv.py` to train on my own dataset, using online data augmentation with the following code: 
```python
train_image_data_generator = keras.preprocessing.image.ImageDataGenerator(
    rotation_range=90,
    zoom_range=0.1,
    horizontal_flip=True,
)
```
but it will appear the following error message:
```bash
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "build/bdist.linux-x86_64/egg/keras/utils/data_utils.py", line 579, in data_generator_task
    generator_output = next(self._generator)
  File "/home/deepcare/workspace/keras-retinanet/keras_retinanet/preprocessing/generator.py", line 140, in next
    image_group, annotations_group = self.preprocess_group(image_group, annotations_group)
  File "/home/deepcare/workspace/keras-retinanet/keras_retinanet/preprocessing/generator.py", line 94, in preprocess_group
    image, annotations = random_transform(image, annotations, self.image_data_generator)
  File "/home/deepcare/workspace/keras-retinanet/keras_retinanet/utils/image.py", line 64, in random_transform
    cv2.rectangle(mask, (b[0], b[1]), (b[2], b[3]), (255,) * image.shape[-1], -1)
TypeError: Layout of the output array img is incompatible with cv::Mat (step[ndims-1] != elemsize or step[1] != elemsize*nchannels)
```

My opencv-python version is 3.3.0, and I also search and find a solution to solve this problem:

modify [this line](https://github.com/fizyr/keras-retinanet/blob/master/keras_retinanet/utils/image.py#L62) to 
```python
mask = np.zeros_like(image, dtype=np.uint8).copy()
```

it seems a opencv bug, could you figure this problems out? thanks.

**Comment by hgaiser** [comment]
It seems weird to me that a newly created array is already not contiguous (I believe that is what the error refers to, I could be wrong). Do you have an explanation for why this is an issue, and why copying it would resolve it?

**Comment by hgaiser** [comment]
Is this still an issue for you?

**Comment by hgaiser** [comment]
Can you try with the latest `master`? Let me know if it is still an issue.

**Comment by tt-leader** [comment]
Thanks, you have solved my problems.
