### ISSUE TITLE
Path to a configuration parameters .ini file

### ISSUE THREAD

**Issue by UESTCshiny** [fizyr/keras-retinanet#971]
Excuse me, I don't know the meanin of 'parser.add_argument('--config',           help='Path to a configuration parameters .ini file.')' in train.py. what is the args.config?
when I run train.py on my own dataset, the error occurs:
```
[r:0,c:1,out] Using TensorFlow backend.
[r:0,c:1,out] Traceback (most recent call last):
[r:0,c:1,out]   File "keras_retinanet/bin/train.py", line 513, in <module>
[r:0,c:1,out]     main()
[r:0,c:1,out]   File "keras_retinanet/bin/train.py", line 440, in main
[r:0,c:1,out]     args.config = read_config_file(args.config)
[r:0,c:1,out]   File "keras_retinanet/bin/../../keras_retinanet/utils/config.py"
, line 25, in read_config_file
[r:0,c:1,out]     config.read(config_path)
[r:0,c:1,out]   File "/usr/lib/python3.5/configparser.py", line 693, in read
[r:0,c:1,out]     for filename in filenames:
[r:0,c:1,out] TypeError: 'NoneType' object is not iterable
```
Appreciate for your reply.

**Comment by hgaiser** [comment]
The configuration file allows to modify some values inside the network (currently only the anchor generation arguments).
